"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'annotate_open_reading_frames',
        "description": "Find all Open Reading Frames (ORFs) in a DNA sequence using Biopython. Searches both forward and reverse complement strands. Args: sequence (str): DNA sequence min_length (int): Minimum length of ORF in nucleotides search_reverse (bool): Whether to search the reverse complement strand (default: False unless you want to search for reverse ORFs) filter_nested (bool): Whether to filter out ORFs with same end but later start (default: False unless you want to remove nested ORFs) Returns: dict: Dictionary containing: - explanation: Explanation of the output fields - summary_stats: Statistical overview of found ORFs - orfs: List of all found ORFs, where each ORF contains: - sequence: Nucleotide sequence of the ORF - aa_sequence: Translated amino acid sequence - start: Start position in original sequence (0-based) - end: End position in original sequence - strand: '+' for forward strand, '-' for reverse complement - frame: Reading frame (1,2,3 for forward; -1,-2,-3 for reverse)",
        "required_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'Parameter sequence',
                "default": None
            },
            {
                "name": 'min_length',
                "type": 'str',
                "description": 'Parameter min_length',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'search_reverse',
                "type": 'bool',
                "description": 'Parameter search_reverse',
                "default": False
            },
            {
                "name": 'filter_subsets',
                "type": 'bool',
                "description": 'Parameter filter_subsets',
                "default": False
            },
        ],
    },
    {
        "name": 'annotate_plasmid',
        "description": "Annotate a DNA sequence using pLannotate's command-line interface. Args: sequence (str): The DNA sequence to annotate is_circular (bool): Whether the sequence is circular (default: True) return_plot (bool): Whether to return the Bokeh plot object (default: False) Returns: Dict: Dictionary containing annotation results or None if annotation fails",
        "required_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'Parameter sequence',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'is_circular',
                "type": 'bool',
                "description": 'Parameter is_circular',
                "default": True
            },
        ],
    },
    {
        "name": 'get_gene_coding_sequence',
        "description": 'Retrieves the coding sequence(s) of a specified gene from NCBI Entrez. Args: gene_name: Name of the gene organism: Name of the organism email: Email address for NCBI Entrez (recommended) Returns: List of dictionaries containing: - refseq_id: RefSeq ID of the gene - sequence: Coding sequence of the gene',
        "required_parameters": [
            {
                "name": 'gene_name',
                "type": 'str',
                "description": 'Parameter gene_name',
                "default": None
            },
            {
                "name": 'organism',
                "type": 'str',
                "description": 'Parameter organism',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'email',
                "type": 'str',
                "description": 'Parameter email',
                "default": None
            },
        ],
    },
    {
        "name": 'get_plasmid_sequence',
        "description": 'Unified function to retrieve plasmid sequences from either Addgene or NCBI. If is_addgene is True or identifier is numeric, uses Addgene. Otherwise searches NCBI using the plasmid name. Args: identifier (str): Either an Addgene ID or plasmid name is_addgene (bool, optional): Force Addgene lookup if True, force NCBI if False. If None, attempts to auto-detect based on identifier format. Returns: Optional[Dict[str, Any]]: The plasmid sequence and metadata if found, None otherwise',
        "required_parameters": [
            {
                "name": 'identifier',
                "type": 'str',
                "description": 'Parameter identifier',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'is_addgene',
                "type": 'str',
                "description": 'Parameter is_addgene',
                "default": None
            },
        ],
    },
    {
        "name": 'align_sequences',
        "description": "Align short sequences (primers) to a longer sequence, allowing for one mismatch. Checks both forward and reverse complement strands. Args: long_seq (str): Target DNA sequence short_seqs (Union[str, List[str]]): Single primer or list of primers Returns: List[Dict]: List of alignment results for each short sequence, including: - explanation: Explanation of the output fields - sequence: the short sequence that was aligned - alignments: list of dictionaries containing: - position: 0-based start position in the target sequence - strand: '+' for forward strand, '-' for reverse complement - mismatches: list of tuples (position, expected_base, found_base) for any mismatches",
        "required_parameters": [
            {
                "name": 'long_seq',
                "type": 'str',
                "description": 'Parameter long_seq',
                "default": None
            },
            {
                "name": 'short_seqs',
                "type": 'str',
                "description": 'Parameter short_seqs',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'pcr_simple',
        "description": "Simulate PCR amplification with given primers and sequence. Args: sequence (str): Either a sequence string or path to plasmid file forward_primer (str): Forward primer sequence (5' to 3') reverse_primer (str): Reverse primer sequence (5' to 3') circular (bool): Whether the sequence is circular (default: False) Returns: dict: Results of PCR simulation including products and primer binding details",
        "required_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'Parameter sequence',
                "default": None
            },
            {
                "name": 'forward_primer',
                "type": 'str',
                "description": 'Parameter forward_primer',
                "default": None
            },
            {
                "name": 'reverse_primer',
                "type": 'str',
                "description": 'Parameter reverse_primer',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'circular',
                "type": 'bool',
                "description": 'Parameter circular',
                "default": False
            },
        ],
    },
    {
        "name": 'digest_sequence',
        "description": "Simulates restriction enzyme digestion using Biopython's catalyze method and returns the resulting DNA fragments. Args: enzyme_names (str | list): Name of the restriction enzyme or list of enzyme names dna_sequence (str): Input DNA sequence is_circular (bool): Whether the DNA sequence is circular (True) or linear (False) Returns: Dict: Dictionary containing the digestion fragments and their properties including positions",
        "required_parameters": [
            {
                "name": 'dna_sequence',
                "type": 'str',
                "description": 'Parameter dna_sequence',
                "default": None
            },
            {
                "name": 'enzyme_names',
                "type": 'str',
                "description": 'Parameter enzyme_names',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'is_circular',
                "type": 'bool',
                "description": 'Parameter is_circular',
                "default": True
            },
        ],
    },
    {
        "name": 'find_restriction_sites',
        "description": 'Identifies restriction enzyme sites in a given DNA sequence for specified enzymes. Args: dna_sequence (str): Complete input DNA sequence enzymes (List[str]): List of restriction enzyme names to check is_circular (bool): Whether the DNA sequence is circular (True) or linear (False) Returns: Dict: Dictionary containing all identified restriction sites',
        "required_parameters": [
            {
                "name": 'dna_sequence',
                "type": 'str',
                "description": 'Parameter dna_sequence',
                "default": None
            },
            {
                "name": 'enzymes',
                "type": 'str',
                "description": 'Parameter enzymes',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'is_circular',
                "type": 'bool',
                "description": 'Parameter is_circular',
                "default": True
            },
        ],
    },
    {
        "name": 'find_restriction_enzymes',
        "description": 'Finds common restriction enzyme sites in a DNA sequence. Args: sequence (str): DNA sequence to analyze is_circular (bool): Whether the sequence is circular (default: False) Returns: Dict[str, list]: Dictionary of enzymes and their cut positions',
        "required_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'Parameter sequence',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'is_circular',
                "type": 'bool',
                "description": 'Parameter is_circular',
                "default": False
            },
        ],
    },
    {
        "name": 'find_sequence_mutations',
        "description": 'Compare query sequence against reference sequence to identify mutations. Args: query_sequence (str): The sequence being analyzed reference_sequence (str): The reference sequence to compare against query_start (int): The start position of the query sequence Returns: list: List of mutations in format RefAA_Position_QueryAA Example: If query_sequence = "ACGT" and reference_sequence = "AGGT", the output would be ["A1C", "G2T"] indicating mutations at positions 1 and 2.',
        "required_parameters": [
            {
                "name": 'query_sequence',
                "type": 'str',
                "description": 'Parameter query_sequence',
                "default": None
            },
            {
                "name": 'reference_sequence',
                "type": 'str',
                "description": 'Parameter reference_sequence',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'query_start',
                "type": 'int',
                "description": 'Parameter query_start',
                "default": 1
            },
        ],
    },
    {
        "name": 'design_knockout_sgrna',
        "description": 'Design sgRNAs for CRISPR knockout by searching pre-computed sgRNA libraries. Returns optimized guide RNAs for targeting a specific gene. Args: gene_name (str): Target gene symbol/name (e.g., "EGFR", "TP53") species (str): Target organism species (default: "human") num_guides (int): Number of guides to return (default: 1) Returns: Dict: Dictionary containing: - explanation: Explanation of the output fields - gene_name: Target gene name - species: Target species - guides: List of sgRNA sequences',
        "required_parameters": [
            {
                "name": 'gene_name',
                "type": 'str',
                "description": 'Parameter gene_name',
                "default": None
            },
            {
                "name": 'data_lake_path',
                "type": 'str',
                "description": 'Parameter data_lake_path',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'species',
                "type": 'str',
                "description": 'Parameter species',
                "default": 'human'
            },
            {
                "name": 'num_guides',
                "type": 'int',
                "description": 'Parameter num_guides',
                "default": 1
            },
        ],
    },
    {
        "name": 'get_oligo_annealing_protocol',
        "description": 'Return a standard protocol for annealing oligonucleotides without phosphorylation. Returns: Dict: Dictionary containing detailed protocol steps for oligo annealing',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'get_golden_gate_assembly_protocol',
        "description": 'Return a customized protocol for Golden Gate assembly based on the number of inserts and specific DNA sequences. Args: num_inserts (int): Number of inserts to be assembled (default: 1) enzyme_name (str): Type IIS restriction enzyme to be used vector_length (int): Length of the destination vector in bp vector_amount_ng (float): Amount of vector to use in ng (default: 75.0) insert_lengths (List[int]): List of insert lengths in bp (optional) is_library_prep (bool): Whether this is for library preparation (default: False) Returns: Dict: Dictionary containing detailed protocol steps for Golden Gate assembly',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'num_inserts',
                "type": 'int',
                "description": 'Parameter num_inserts',
                "default": 1
            },
            {
                "name": 'enzyme_name',
                "type": 'str',
                "description": 'Parameter enzyme_name',
                "default": None
            },
            {
                "name": 'vector_length',
                "type": 'str',
                "description": 'Parameter vector_length',
                "default": None
            },
            {
                "name": 'vector_amount_ng',
                "type": 'float',
                "description": 'Parameter vector_amount_ng',
                "default": 75.0
            },
            {
                "name": 'insert_lengths',
                "type": 'str',
                "description": 'Parameter insert_lengths',
                "default": None
            },
            {
                "name": 'is_library_prep',
                "type": 'bool',
                "description": 'Parameter is_library_prep',
                "default": False
            },
        ],
    },
    {
        "name": 'get_bacterial_transformation_protocol',
        "description": 'Return a standard protocol for bacterial transformation. Args: antibiotic (str): Selection antibiotic (default: "ampicillin") is_repetitive (bool): Whether the sequence contains repetitive elements (default: False) Returns: Dict: Dictionary containing detailed protocol steps for bacterial transformation',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'antibiotic',
                "type": 'str',
                "description": 'Parameter antibiotic',
                "default": 'ampicillin'
            },
            {
                "name": 'is_repetitive',
                "type": 'bool',
                "description": 'Parameter is_repetitive',
                "default": False
            },
        ],
    },
    {
        "name": 'design_primer',
        "description": 'Design a single primer within the given sequence window. Args: sequence (str): Target DNA sequence start_pos (int): Starting position for primer search primer_length (int): Length of the primer to design (default: 20) min_gc (float): Minimum GC content (default: 0.4) max_gc (float): Maximum GC content (default: 0.6) min_tm (float): Minimum melting temperature in °C (default: 55.0) max_tm (float): Maximum melting temperature in °C (default: 65.0) search_window (int): Size of window to search for primers (default: 100) Returns: Optional[Dict[str, Any]]: Dictionary with primer information or None if no suitable primer found',
        "required_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'Parameter sequence',
                "default": None
            },
            {
                "name": 'start_pos',
                "type": 'str',
                "description": 'Parameter start_pos',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'primer_length',
                "type": 'int',
                "description": 'Parameter primer_length',
                "default": 20
            },
            {
                "name": 'min_gc',
                "type": 'float',
                "description": 'Parameter min_gc',
                "default": 0.4
            },
            {
                "name": 'max_gc',
                "type": 'float',
                "description": 'Parameter max_gc',
                "default": 0.6
            },
            {
                "name": 'min_tm',
                "type": 'float',
                "description": 'Parameter min_tm',
                "default": 55.0
            },
            {
                "name": 'max_tm',
                "type": 'float',
                "description": 'Parameter max_tm',
                "default": 65.0
            },
            {
                "name": 'search_window',
                "type": 'int',
                "description": 'Parameter search_window',
                "default": 100
            },
        ],
    },
    {
        "name": 'design_verification_primers',
        "description": 'Design Sanger sequencing primers to verify a specific region in a plasmid. First tries to use primers from an existing primer pool. If they cannot fully cover the region, designs additional primers as needed. Args: plasmid_sequence (str): The complete plasmid sequence target_region (Tuple[int, int]): Start and end positions to verify (0-based indexing) existing_primers (Optional[List[Dict[str, str]]]): List of existing primers with their sequences and optional names. If None, uses common lab primers. is_circular (bool): Whether the plasmid is circular (default: True) coverage_length (int): Typical read length for each primer (default: 800bp) primer_length (int): Length of newly designed primers (default: 20) min_gc (float): Minimum GC content for new primers (default: 0.4) max_gc (float): Maximum GC content for new primers (default: 0.6) min_tm (float): Minimum melting temperature in °C (default: 55.0) max_tm (float): Maximum melting temperature in °C (default: 65.0) Returns: Dict: Dictionary containing: - target_region: The region to be verified - recommended_primers: List of primers to use (from existing and/or newly designed) - coverage_map: How the primers cover the target region',
        "required_parameters": [
            {
                "name": 'plasmid_sequence',
                "type": 'str',
                "description": 'Parameter plasmid_sequence',
                "default": None
            },
            {
                "name": 'target_region',
                "type": 'str',
                "description": 'Parameter target_region',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'existing_primers',
                "type": 'str',
                "description": 'Parameter existing_primers',
                "default": None
            },
            {
                "name": 'is_circular',
                "type": 'bool',
                "description": 'Parameter is_circular',
                "default": True
            },
            {
                "name": 'coverage_length',
                "type": 'int',
                "description": 'Parameter coverage_length',
                "default": 800
            },
            {
                "name": 'primer_length',
                "type": 'int',
                "description": 'Parameter primer_length',
                "default": 20
            },
            {
                "name": 'min_gc',
                "type": 'float',
                "description": 'Parameter min_gc',
                "default": 0.4
            },
            {
                "name": 'max_gc',
                "type": 'float',
                "description": 'Parameter max_gc',
                "default": 0.6
            },
            {
                "name": 'min_tm',
                "type": 'float',
                "description": 'Parameter min_tm',
                "default": 55.0
            },
            {
                "name": 'max_tm',
                "type": 'float',
                "description": 'Parameter max_tm',
                "default": 65.0
            },
        ],
    },
    {
        "name": 'design_golden_gate_oligos',
        "description": 'Design oligos for Golden Gate assembly by identifying backbone overhangs and creating matching insert oligos. Args: backbone_sequence (str): The plasmid/backbone sequence insert_sequence (str): Sequence to be inserted enzyme_name (str): Type IIS restriction enzyme to be used is_circular (bool): Whether the backbone is circular (default: True) Returns: Dict: Dictionary containing overhang information and designed oligos',
        "required_parameters": [
            {
                "name": 'backbone_sequence',
                "type": 'str',
                "description": 'Parameter backbone_sequence',
                "default": None
            },
            {
                "name": 'insert_sequence',
                "type": 'str',
                "description": 'Parameter insert_sequence',
                "default": None
            },
            {
                "name": 'enzyme_name',
                "type": 'str',
                "description": 'Parameter enzyme_name',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'is_circular',
                "type": 'bool',
                "description": 'Parameter is_circular',
                "default": True
            },
        ],
    },
    {
        "name": 'golden_gate_assembly',
        "description": 'Simulate Golden Gate assembly to predict final construct sequences. Args: backbone_sequence (str): Complete backbone sequence enzyme_name (str): Type IIS restriction enzyme to be used (e.g., "BsmBI", "BsaI") fragments (List[Dict[str, str]]): List of fragments to insert, containing one of: - name + fwd_oligo + rev_oligo: Oligo pair with matching overhangs - name + sequence: Double-stranded DNA fragment containing restriction sites is_circular (bool): Whether the backbone is circular (default: True) Returns: Dict: Dictionary containing: - success: Boolean indicating if assembly was successful - assembled_sequence: The final assembled sequence - message: Error message if assembly failed',
        "required_parameters": [
            {
                "name": 'backbone_sequence',
                "type": 'str',
                "description": 'Parameter backbone_sequence',
                "default": None
            },
            {
                "name": 'enzyme_name',
                "type": 'str',
                "description": 'Parameter enzyme_name',
                "default": None
            },
            {
                "name": 'fragments',
                "type": 'str',
                "description": 'Parameter fragments',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'is_circular',
                "type": 'bool',
                "description": 'Parameter is_circular',
                "default": True
            },
        ],
    },
    {
        "name": 'find_orfs_in_frame',
        "description": 'Helper function to find ORFs in a specific frame.',
        "required_parameters": [
            {
                "name": 'seq_str',
                "type": 'str',
                "description": 'Parameter seq_str',
                "default": None
            },
            {
                "name": 'frame',
                "type": 'str',
                "description": 'Parameter frame',
                "default": None
            },
            {
                "name": 'strand',
                "type": 'str',
                "description": 'Parameter strand',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'search_gene',
        "description": 'Search for gene ID in NCBI database.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'get_refseq_id',
        "description": 'Get RefSeq ID from gene record.',
        "required_parameters": [
            {
                "name": 'gene_id',
                "type": 'str',
                "description": 'Parameter gene_id',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'get_coding_sequences',
        "description": 'Extract coding sequences from RefSeq record.',
        "required_parameters": [
            {
                "name": 'refseq_id',
                "type": 'str',
                "description": 'Parameter refseq_id',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'reverse_complement',
        "description": 'Helper function to get reverse complement of a sequence.',
        "required_parameters": [
            {
                "name": 'seq',
                "type": 'str',
                "description": 'Parameter seq',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'is_position_covered',
        "description": 'Check if a position is covered by any region.',
        "required_parameters": [
            {
                "name": 'pos',
                "type": 'str',
                "description": 'Parameter pos',
                "default": None
            },
            {
                "name": 'covered_regions',
                "type": 'str',
                "description": 'Parameter covered_regions',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'is_region_fully_covered',
        "description": 'Check if the target region is fully covered.',
        "required_parameters": [
            {
                "name": 'covered_regions',
                "type": 'str',
                "description": 'Parameter covered_regions',
                "default": None
            },
            {
                "name": 'start',
                "type": 'str',
                "description": 'Parameter start',
                "default": None
            },
            {
                "name": 'end',
                "type": 'str',
                "description": 'Parameter end',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'merge_overlapping_regions',
        "description": 'Merge overlapping regions in the list.',
        "required_parameters": [
            {
                "name": 'regions',
                "type": 'str',
                "description": 'Parameter regions',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'reverse_complement',
        "description": 'Get the reverse complement of a DNA sequence.',
        "required_parameters": [
            {
                "name": 'seq',
                "type": 'str',
                "description": 'Parameter seq',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'reverse_complement',
        "description": 'Get the reverse complement of a DNA sequence.',
        "required_parameters": [
            {
                "name": 'seq',
                "type": 'str',
                "description": 'Parameter seq',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
