"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'fetch_supplementary_info_from_doi',
        "description": 'Fetches supplementary information for a paper given its DOI and returns a research log. Args: doi: The paper DOI. output_dir: Directory to save supplementary files. Returns: dict: A dictionary containing a research log and the downloaded file paths.',
        "required_parameters": [
            {
                "name": 'doi',
                "type": 'str',
                "description": 'Parameter doi',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": 'supplementary_info'
            },
        ],
    },
    {
        "name": 'query_arxiv',
        "description": 'Query arXiv for papers based on the provided search query.',
        "required_parameters": [
            {
                "name": 'query',
                "type": 'str',
                "description": 'Parameter query',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'max_papers',
                "type": 'int',
                "description": 'Parameter max_papers',
                "default": 10
            },
        ],
    },
    {
        "name": 'query_scholar',
        "description": 'Query Google Scholar for papers based on the provided search query.',
        "required_parameters": [
            {
                "name": 'query',
                "type": 'str',
                "description": 'Parameter query',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'query_pubmed',
        "description": 'Query PubMed for papers based on the provided search query.',
        "required_parameters": [
            {
                "name": 'query',
                "type": 'str',
                "description": 'Parameter query',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'max_papers',
                "type": 'int',
                "description": 'Parameter max_papers',
                "default": 10
            },
            {
                "name": 'max_retries',
                "type": 'int',
                "description": 'Parameter max_retries',
                "default": 3
            },
        ],
    },
    {
        "name": 'search_google',
        "description": 'Search using Google search. Args: query (str): The search query (e.g., "protocol text or seach question") num_results (int): Number of results to return (default: 10) language (str): Language code for search results (default: \'en\') pause (float): Pause between searches to avoid rate limiting (default: 2.0 seconds) Returns: List[dict]: List of dictionaries containing search results with title and URL',
        "required_parameters": [
            {
                "name": 'query',
                "type": 'str',
                "description": 'Parameter query',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'num_results',
                "type": 'int',
                "description": 'Parameter num_results',
                "default": 3
            },
            {
                "name": 'language',
                "type": 'str',
                "description": 'Parameter language',
                "default": 'en'
            },
        ],
    },
    {
        "name": 'advanced_web_search_claude',
        "description": 'Initiate an advanced web search by launching a specialized agent to collect relevant information and citations through multiple rounds of web searches for a given query. Craft the query carefully for the search agent to find the most relevant information.',
        "required_parameters": [
            {
                "name": 'query',
                "type": 'str',
                "description": 'The search phrase you want Claude to look up.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'max_searches',
                "type": 'int',
                "description": 'Upper-bound on searches Claude may issue inside this request.',
                "default": 1
            },
            {
                "name": 'max_retries',
                "type": 'int',
                "description": 'Maximum number of retry attempts with exponential backoff.',
                "default": 3
            },
        ],
    },
    {
        "name": 'extract_url_content',
        "description": 'Extract the text content of a webpage using requests and BeautifulSoup. Args: url: Webpage URL to extract content from Returns: Text content of the webpage',
        "required_parameters": [
            {
                "name": 'url',
                "type": 'str',
                "description": 'Parameter url',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'extract_pdf_content',
        "description": 'Extract the text content of a PDF file given its URL. Args: url: URL of the PDF file to extract text from Returns: The extracted text content from the PDF',
        "required_parameters": [
            {
                "name": 'url',
                "type": 'str',
                "description": 'Parameter url',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
