"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'engineer_bacterial_genome_for_therapeutic_delivery',
        "description": 'Engineer a bacterial genome by integrating therapeutic genetic parts for therapeutic delivery.',
        "required_parameters": [
            {
                "name": 'bacterial_genome_file',
                "type": 'str',
                "description": 'Path to the file containing the bacterial genome sequence in FASTA format',
                "default": None
            },
            {
                "name": 'genetic_parts',
                "type": 'dict',
                "description": "Dictionary containing genetic parts to be integrated:: { 'promoters': list of dict with 'name', 'sequence', and 'position', 'genes': list of dict with 'name', 'sequence', and 'position', 'terminators': list of dict with 'name', 'sequence', and 'position', 'cargo': dict with 'name' and 'sequence' of the therapeutic cargo }",
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'analyze_bacterial_growth_rate',
        "description": 'Analyze bacterial growth data and extract growth parameters from OD600 measurements.',
        "required_parameters": [
            {
                "name": 'time_points',
                "type": 'list or numpy.ndarray',
                "description": 'Time points at which OD600 measurements were taken (in hours)',
                "default": None
            },
            {
                "name": 'od_measurements',
                "type": 'list or numpy.ndarray',
                "description": 'Optical density (OD600) measurements corresponding to each time point',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'strain_name',
                "type": 'str',
                "description": 'Name of the bacterial strain being analyzed, default is "Unknown strain"',
                "default": 'Unknown strain'
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where to save the output files, default is current directory',
                "default": './'
            },
        ],
    },
    {
        "name": 'analyze_barcode_sequencing_data',
        "description": 'Analyze sequencing data to extract, quantify and determine lineage relationships of barcodes.',
        "required_parameters": [
            {
                "name": 'input_file',
                "type": 'str',
                "description": 'Path to the input sequencing file in FASTQ or FASTA format',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'barcode_pattern',
                "type": 'str',
                "description": 'Regular expression pattern to identify barcodes. If None, will use flanking sequences',
                "default": None
            },
            {
                "name": 'flanking_seq_5prime',
                "type": 'str',
                "description": "5' flanking sequence of the barcode region",
                "default": None
            },
            {
                "name": 'flanking_seq_3prime',
                "type": 'str',
                "description": "3' flanking sequence of the barcode region",
                "default": None
            },
            {
                "name": 'min_count',
                "type": 'int',
                "description": 'Minimum count threshold for considering a barcode',
                "default": 5
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files',
                "default": './results'
            },
        ],
    },
    {
        "name": 'analyze_bifurcation_diagram',
        "description": 'Performs bifurcation analysis on a dynamical system and generates a bifurcation diagram.',
        "required_parameters": [
            {
                "name": 'time_series_data',
                "type": 'numpy.ndarray',
                "description": 'A 2D array where each row represents a time series for a specific parameter value. Shape should be (n_parameter_values, n_time_points).',
                "default": None
            },
            {
                "name": 'parameter_values',
                "type": 'numpy.ndarray',
                "description": '1D array of parameter values corresponding to each time series. Shape should be (n_parameter_values,).',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'system_name',
                "type": 'str',
                "description": 'Name of the dynamical system being analyzed, used for plot titles.',
                "default": 'Dynamical System'
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save the output files.',
                "default": './'
            },
        ],
    },
    {
        "name": 'create_biochemical_network_sbml_model',
        "description": 'Generate a mathematical model of a biochemical network in SBML format.',
        "required_parameters": [
            {
                "name": 'reaction_network',
                "type": 'list of dict',
                "description": "List of dictionaries, each representing a reaction with keys: - 'id': Reaction identifier - 'name': Reaction name - 'reactants': Dict of reactant species IDs and their stoichiometry - 'products': Dict of product species IDs and their stoichiometry - 'reversible': Boolean indicating if reaction is reversible",
                "default": None
            },
            {
                "name": 'kinetic_parameters',
                "type": 'dict',
                "description": "Dictionary mapping reaction IDs to their kinetic law parameters. Each entry should contain: - 'law_type': Type of kinetic law (e.g., 'mass_action', 'michaelis_menten') - 'parameters': Dict of parameter names and values",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'File path to save the SBML model (default: "biochemical_model.xml")',
                "default": 'biochemical_model.xml'
            },
        ],
    },
    {
        "name": 'optimize_codons_for_heterologous_expression',
        "description": 'Analyzes and optimizes a DNA/RNA sequence for improved expression in a heterologous host organism.',
        "required_parameters": [
            {
                "name": 'target_sequence',
                "type": 'str',
                "description": 'The DNA or RNA sequence of the target gene to be optimized. Should contain complete codons (length divisible by 3).',
                "default": None
            },
            {
                "name": 'host_codon_usage',
                "type": 'dict',
                "description": 'Dictionary mapping codons to their usage frequency in the host organism.',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'simulate_gene_circuit_with_growth_feedback',
        "description": 'Simulate gene regulatory circuit dynamics with growth feedback.',
        "required_parameters": [
            {
                "name": 'circuit_topology',
                "type": 'numpy.ndarray',
                "description": 'Adjacency matrix representing the gene circuit topology. Positive values indicate activation, negative values indicate repression. Shape should be (n_genes, n_genes) where n_genes is the number of genes in the circuit.',
                "default": None
            },
            {
                "name": 'kinetic_params',
                "type": 'dict',
                "description": "Dictionary containing kinetic parameters: - 'basal_rates': list of basal expression rates for each gene - 'degradation_rates': list of degradation rates for each gene - 'hill_coefficients': list of Hill coefficients for regulatory interactions - 'threshold_constants': list of threshold constants for regulatory interactions",
                "default": None
            },
            {
                "name": 'growth_params',
                "type": 'dict',
                "description": "Dictionary containing growth-related parameters: - 'max_growth_rate': maximum cell growth rate - 'growth_inhibition': how gene expression affects growth - 'gene_growth_weights': weights for how each gene affects growth",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'simulation_time',
                "type": 'float',
                "description": 'Total simulation time (default: 100)',
                "default": 100
            },
            {
                "name": 'time_points',
                "type": 'int',
                "description": 'Number of time points to sample (default: 1000)',
                "default": 1000
            },
        ],
    },
    {
        "name": 'identify_fas_functional_domains',
        "description": 'Identifies functional domains within a Fatty Acid Synthase (FAS) sequence and predicts their roles.',
        "required_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'The nucleotide or protein sequence of a FAS gene',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'sequence_type',
                "type": 'str',
                "description": 'Type of sequence provided - "protein" or "nucleotide" (default: "protein")',
                "default": 'protein'
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Name of the output file to save the detailed domain report (default: "fas_domains_report.txt")',
                "default": 'fas_domains_report.txt'
            },
        ],
    },
    {
        "name": 'gompertz_model',
        "description": 'Gompertz growth model.',
        "required_parameters": [
            {
                "name": 't',
                "type": 'time points',
                "description": '',
                "default": None
            },
            {
                "name": 'lag',
                "type": 'lag time (hours)',
                "description": '',
                "default": None
            },
            {
                "name": 'mu_max',
                "type": 'maximum growth rate (per hour)',
                "description": '',
                "default": None
            },
            {
                "name": 'A',
                "type": 'carrying capacity (maximum OD)',
                "description": '',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'gene_circuit_odes',
        "description": 'Function gene_circuit_odes',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'state',
                "type": 'str',
                "description": 'Parameter state',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'hamming_distance',
        "description": 'Function hamming_distance',
        "required_parameters": [
            {
                "name": 's1',
                "type": 'str',
                "description": 'Parameter s1',
                "default": None
            },
            {
                "name": 's2',
                "type": 'str',
                "description": 'Parameter s2',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
