"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'optimize_anaerobic_digestion_process',
        "description": 'Optimize anaerobic digestion process conditions to maximize VFA production or methane yield.',
        "required_parameters": [
            {
                "name": 'waste_characteristics',
                "type": 'dict',
                "description": 'Dictionary containing waste characteristics such as: - total_solids (float): Total solids content (%) - volatile_solids (float): Volatile solids content (%) - cod (float): Chemical oxygen demand (mg/L)',
                "default": None
            },
            {
                "name": 'operational_parameters',
                "type": 'dict',
                "description": 'Dictionary containing operational parameters and their ranges: - hrt (tuple): Hydraulic retention time range in days (min, max) - olr (tuple): Organic loading rate range in kg VS/(m³·d) (min, max) - if_ratio (tuple): Inoculum-to-feedstock ratio range (min, max) - temperature (tuple): Temperature range in °C (min, max) - ph (tuple): pH range (min, max)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'target_output',
                "type": 'str',
                "description": "Target output to maximize, either 'vfa_production' or 'methane_yield'. Default is 'methane_yield'.",
                "default": 'methane_yield'
            },
            {
                "name": 'optimization_method',
                "type": 'str',
                "description": "Method used for optimization, either 'rsm' (Response Surface Methodology) or 'genetic' (Genetic Algorithm). Default is 'rsm'.",
                "default": 'rsm'
            },
        ],
    },
    {
        "name": 'analyze_arsenic_speciation_hplc_icpms',
        "description": 'Analyzes arsenic speciation in liquid samples using HPLC-ICP-MS technique.',
        "required_parameters": [
            {
                "name": 'sample_data',
                "type": 'dict',
                "description": 'Dictionary containing sample data with keys as sample IDs and values as dictionaries with retention times (in minutes) as keys and signal intensities as values.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'sample_name',
                "type": 'str',
                "description": 'Name of the sample being analyzed (default: "Unknown Sample")',
                "default": 'Unknown Sample'
            },
            {
                "name": 'calibration_data',
                "type": 'dict',
                "description": 'Dictionary containing calibration standards data with known concentrations for each arsenic species. If None, default calibration values will be used.',
                "default": None
            },
        ],
    },
    {
        "name": 'count_bacterial_colonies',
        "description": 'Count bacterial colonies from an image of agar plate using computer vision techniques.',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Path to the image file containing bacterial colonies on agar plate',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'dilution_factor',
                "type": 'float',
                "description": 'Dilution factor of the plated sample (default=1)',
                "default": 1
            },
            {
                "name": 'plate_area_cm2',
                "type": 'float',
                "description": 'Area of the agar plate in square centimeters (default=65.0, standard Petri dish)',
                "default": 65.0
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output images and results (default="./output")',
                "default": './output'
            },
        ],
    },
    {
        "name": 'annotate_bacterial_genome',
        "description": 'Annotate a bacterial genome using Prokka to identify genes, proteins, and functional features.',
        "required_parameters": [
            {
                "name": 'genome_file_path',
                "type": 'str',
                "description": 'Path to the assembled genome sequence file in FASTA format',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where annotation results will be saved (default: "annotation_results")',
                "default": 'annotation_results'
            },
            {
                "name": 'genus',
                "type": 'str',
                "description": 'Genus name for the organism (default: "")',
                "default": ''
            },
            {
                "name": 'species',
                "type": 'str',
                "description": 'Species name for the organism (default: "")',
                "default": ''
            },
            {
                "name": 'strain',
                "type": 'str',
                "description": 'Strain identifier (default: "")',
                "default": ''
            },
            {
                "name": 'prefix',
                "type": 'str',
                "description": 'Prefix for output files (default: "")',
                "default": ''
            },
        ],
    },
    {
        "name": 'enumerate_bacterial_cfu_by_serial_dilution',
        "description": 'Quantify bacterial concentration (CFU/mL) using serial dilutions and spot plating.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'initial_sample_volume_ml',
                "type": 'float',
                "description": 'Volume of the initial bacterial sample in milliliters',
                "default": 1.0
            },
            {
                "name": 'estimated_concentration',
                "type": 'float',
                "description": 'Estimated concentration of bacteria in the initial sample (CFU/mL)',
                "default": 100000000.0
            },
            {
                "name": 'dilution_factor',
                "type": 'int',
                "description": 'Factor by which each dilution reduces the concentration (typically 10)',
                "default": 10
            },
            {
                "name": 'num_dilutions',
                "type": 'int',
                "description": 'Number of serial dilutions to perform',
                "default": 8
            },
            {
                "name": 'spots_per_dilution',
                "type": 'int',
                "description": 'Number of replicate spots to plate for each dilution',
                "default": 3
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Filename to save the CFU enumeration results',
                "default": 'cfu_enumeration_results.csv'
            },
        ],
    },
    {
        "name": 'model_bacterial_growth_dynamics',
        "description": 'Model bacterial population dynamics over time using ordinary differential equations.',
        "required_parameters": [
            {
                "name": 'initial_population',
                "type": 'float',
                "description": 'Initial bacterial population size (CFU/ml or cells)',
                "default": None
            },
            {
                "name": 'growth_rate',
                "type": 'float',
                "description": 'Bacterial growth rate (per hour)',
                "default": None
            },
            {
                "name": 'clearance_rate',
                "type": 'float',
                "description": 'Rate at which bacteria are cleared from the system (per hour)',
                "default": None
            },
            {
                "name": 'niche_size',
                "type": 'float',
                "description": 'Maximum carrying capacity of the environment (CFU/ml or cells)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'simulation_time',
                "type": 'float',
                "description": 'Total simulation time in hours (default: 24)',
                "default": 24
            },
            {
                "name": 'time_step',
                "type": 'float',
                "description": 'Time step for simulation output (default: 0.1)',
                "default": 0.1
            },
        ],
    },
    {
        "name": 'quantify_biofilm_biomass_crystal_violet',
        "description": 'Quantifies biofilm biomass using crystal violet staining assay data.',
        "required_parameters": [
            {
                "name": 'od_values',
                "type": 'list or numpy.ndarray',
                "description": 'Optical density measurements from crystal violet staining. Each value represents the absorbance reading for a sample.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'sample_names',
                "type": 'list',
                "description": 'Names of the biofilm samples corresponding to od_values. If None, samples will be labeled as Sample 1, Sample 2, etc.',
                "default": None
            },
            {
                "name": 'control_index',
                "type": 'int',
                "description": 'Index of the negative control sample in od_values. Default is 0.',
                "default": 0
            },
            {
                "name": 'save_path',
                "type": 'str',
                "description": "Path to save the results. If None, results won't be saved to a file.",
                "default": None
            },
        ],
    },
    {
        "name": 'segment_and_analyze_microbial_cells',
        "description": 'Perform automated cell segmentation and quantify morphological metrics from fluorescence microscopy images.',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Path to the fluorescence microscopy image file',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": "Directory to save output files (default: './output')",
                "default": './output'
            },
            {
                "name": 'min_cell_size',
                "type": 'int',
                "description": 'Minimum cell size in pixels to filter noise (default: 50)',
                "default": 50
            },
        ],
    },
    {
        "name": 'segment_cells_with_deep_learning',
        "description": 'Perform cell segmentation on fluorescence microscopy images using deep learning. Uses pre-trained models from the Cellpose/Omnipose library to identify and segment individual cells in fluorescence microscopy images.',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Path to the fluorescence microscopy image file',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'model_type',
                "type": 'str',
                "description": "Name of the pre-trained model to use (default: 'bact_fluor_omni') Options include: 'bact_fluor_omni', 'cyto', 'nuclei', etc.",
                "default": 'bact_fluor_omni'
            },
            {
                "name": 'diameter',
                "type": 'float',
                "description": 'Expected diameter of cells in pixels. If None, diameter is automatically estimated.',
                "default": None
            },
            {
                "name": 'save_dir',
                "type": 'str',
                "description": "Directory to save segmentation results (default: 'segmentation_results')",
                "default": 'segmentation_results'
            },
        ],
    },
    {
        "name": 'simulate_generalized_lotka_volterra_dynamics',
        "description": 'Simulate microbial community dynamics using the Generalized Lotka-Volterra (gLV) model.',
        "required_parameters": [
            {
                "name": 'initial_abundances',
                "type": 'numpy.ndarray',
                "description": 'Initial abundances of each microbial species (1D array)',
                "default": None
            },
            {
                "name": 'growth_rates',
                "type": 'numpy.ndarray',
                "description": 'Intrinsic growth rates for each microbial species (1D array)',
                "default": None
            },
            {
                "name": 'interaction_matrix',
                "type": 'numpy.ndarray',
                "description": 'Matrix of interaction coefficients where A[i,j] represents the effect of species j on species i (2D array)',
                "default": None
            },
            {
                "name": 'time_points',
                "type": 'numpy.ndarray',
                "description": 'Time points at which to evaluate the model',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Filename to save the simulation results (default: "glv_simulation_results.csv")',
                "default": 'glv_simulation_results.csv'
            },
        ],
    },
    {
        "name": 'predict_rna_secondary_structure',
        "description": 'Predict the secondary structure of an RNA molecule using ViennaRNA.',
        "required_parameters": [
            {
                "name": 'rna_sequence',
                "type": 'str',
                "description": 'The RNA sequence (consisting of A, U, G, C nucleotides)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_prefix',
                "type": 'str',
                "description": 'Prefix for output files (default: "rna_structure")',
                "default": 'rna_structure'
            },
        ],
    },
    {
        "name": 'simulate_microbial_population_dynamics',
        "description": 'Performs stochastic simulation of microbial population dynamics using the Gillespie algorithm.',
        "required_parameters": [
            {
                "name": 'initial_populations',
                "type": 'list of int',
                "description": 'Initial population sizes for each microbial species',
                "default": None
            },
            {
                "name": 'growth_rates',
                "type": 'list of float',
                "description": 'Per capita growth rates for each species',
                "default": None
            },
            {
                "name": 'clearance_rates',
                "type": 'list of float',
                "description": 'Per capita death/clearance rates for each species',
                "default": None
            },
            {
                "name": 'carrying_capacities',
                "type": 'list of float',
                "description": 'Maximum sustainable population for each species',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'max_time',
                "type": 'float',
                "description": 'Maximum simulation time (default: 100)',
                "default": 100
            },
            {
                "name": 'num_simulations',
                "type": 'int',
                "description": 'Number of stochastic simulations to run (default: 100)',
                "default": 100
            },
            {
                "name": 'time_points',
                "type": 'int',
                "description": 'Number of time points to record for trajectories (default: 100)',
                "default": 100
            },
        ],
    },
    {
        "name": 'vfa_production_model',
        "description": 'Function vfa_production_model',
        "required_parameters": [
            {
                "name": 'params',
                "type": 'str',
                "description": 'Parameter params',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'methane_yield_model',
        "description": 'Function methane_yield_model',
        "required_parameters": [
            {
                "name": 'params',
                "type": 'str',
                "description": 'Parameter params',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'bacterial_dynamics',
        "description": 'Function bacterial_dynamics',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'N',
                "type": 'str',
                "description": 'Parameter N',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'glv_equations',
        "description": 'Function glv_equations',
        "required_parameters": [
            {
                "name": 'abundances',
                "type": 'str',
                "description": 'Parameter abundances',
                "default": None
            },
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'growth_rates',
                "type": 'str',
                "description": 'Parameter growth_rates',
                "default": None
            },
            {
                "name": 'interaction_matrix',
                "type": 'str',
                "description": 'Parameter interaction_matrix',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
