"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'liftover_coordinates',
        "description": "Perform liftover of genomic coordinates between hg19 and hg38 formats with detailed intermediate steps. Args: chromosome (str): Chromosome number (e.g., '1', 'X'). position (int): Genomic position. input_format (str): Input genome build ('hg19' or 'hg38'). output_format (str): Output genome build ('hg19' or 'hg38'). data_path (str): Path to liftover chain files. Returns: str: A detailed string explaining the steps and the final result or any error encountered.",
        "required_parameters": [
            {
                "name": 'chromosome',
                "type": 'str',
                "description": 'Parameter chromosome',
                "default": None
            },
            {
                "name": 'position',
                "type": 'str',
                "description": 'Parameter position',
                "default": None
            },
            {
                "name": 'input_format',
                "type": 'str',
                "description": 'Parameter input_format',
                "default": None
            },
            {
                "name": 'output_format',
                "type": 'str',
                "description": 'Parameter output_format',
                "default": None
            },
            {
                "name": 'data_path',
                "type": 'str',
                "description": 'Parameter data_path',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'bayesian_finemapping_with_deep_vi',
        "description": 'Performs Bayesian fine-mapping from GWAS summary statistics using deep variational inference. This function implements a deep neural network-based variational inference approach to compute posterior inclusion probabilities (PIPs) and credible sets for putative causal variants from GWAS summary statistics and linkage disequilibrium (LD) information.',
        "required_parameters": [
            {
                "name": 'gwas_summary_path',
                "type": 'str',
                "description": "Path to CSV or TSV file containing GWAS summary statistics. Expected columns: - 'variant_id': Identifier for each variant - 'effect_size': Effect size (beta) for each variant - 'pvalue': P-value for each variant - 'se': Standard error for each variant (optional)",
                "default": None
            },
            {
                "name": 'ld_matrix',
                "type": 'numpy.ndarray',
                "description": 'Linkage disequilibrium matrix with pairwise correlations between variants.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'n_iterations',
                "type": 'int',
                "description": 'Number of training iterations for the variational inference algorithm. Default is 5000.',
                "default": 5000
            },
            {
                "name": 'learning_rate',
                "type": 'float',
                "description": 'Learning rate for the optimization algorithm. Default is 0.01.',
                "default": 0.01
            },
            {
                "name": 'hidden_dim',
                "type": 'int',
                "description": 'Hidden dimension size for the neural network. Default is 64.',
                "default": 64
            },
            {
                "name": 'credible_threshold',
                "type": 'float',
                "description": 'Threshold for defining the credible set (e.g., 0.95 for a 95% credible set). Default is 0.95.',
                "default": 0.95
            },
        ],
    },
    {
        "name": 'analyze_cas9_mutation_outcomes',
        "description": 'Analyzes and categorizes mutations induced by Cas9 at target sites.',
        "required_parameters": [
            {
                "name": 'reference_sequences',
                "type": 'dict',
                "description": 'Dictionary mapping sequence IDs to reference DNA sequences (strings)',
                "default": None
            },
            {
                "name": 'edited_sequences',
                "type": 'dict of dict',
                "description": 'Nested dictionary: {sequence_id: {read_id: sequence}} Contains the edited/mutated sequences for each reference',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'cell_line_info',
                "type": 'dict',
                "description": 'Dictionary mapping sequence IDs to cell line information (e.g., wildtype, knockout gene)',
                "default": None
            },
            {
                "name": 'output_prefix',
                "type": 'str',
                "description": 'Prefix for output files',
                "default": 'cas9_mutation_analysis'
            },
        ],
    },
    {
        "name": 'analyze_crispr_genome_editing',
        "description": 'Analyzes CRISPR-Cas9 genome editing results by comparing original and edited sequences.',
        "required_parameters": [
            {
                "name": 'original_sequence',
                "type": 'str',
                "description": 'The original DNA sequence before CRISPR-Cas9 editing',
                "default": None
            },
            {
                "name": 'edited_sequence',
                "type": 'str',
                "description": 'The DNA sequence after CRISPR-Cas9 editing',
                "default": None
            },
            {
                "name": 'guide_rna',
                "type": 'str',
                "description": 'The CRISPR guide RNA (crRNA) sequence used for targeting',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'repair_template',
                "type": 'str',
                "description": 'The homology-directed repair template sequence, if used',
                "default": None
            },
        ],
    },
    {
        "name": 'simulate_demographic_history',
        "description": 'Simulate DNA sequences with specified demographic and coalescent histories using msprime.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'num_samples',
                "type": 'int',
                "description": 'Number of sample sequences to simulate',
                "default": 10
            },
            {
                "name": 'sequence_length',
                "type": 'int',
                "description": 'Length of the simulated sequence in base pairs',
                "default": 100000
            },
            {
                "name": 'recombination_rate',
                "type": 'float',
                "description": 'Per-base recombination rate',
                "default": 1e-08
            },
            {
                "name": 'mutation_rate',
                "type": 'float',
                "description": 'Per-base mutation rate',
                "default": 1e-08
            },
            {
                "name": 'demographic_model',
                "type": 'str',
                "description": 'Type of demographic model to simulate. Options: - "constant": Constant population size - "bottleneck": Population bottleneck - "expansion": Population expansion - "contraction": Population contraction - "sawtooth": Sawtooth pattern of population size changes',
                "default": 'constant'
            },
            {
                "name": 'demographic_params',
                "type": 'dict',
                "description": 'Parameters specific to the chosen demographic model. Supported formats:: - For "constant": {"N": population size} - For "bottleneck": { "N_initial": initial pop size, "N_bottleneck": bottleneck pop size, "T_bottleneck": time of bottleneck (generations ago), "T_recovery": time of recovery (generations ago) } - For "expansion": {"N_initial": initial pop size, "N_final": final pop size, "T_expansion": time of expansion (generations ago)} - For "contraction": {"N_initial": initial pop size, "N_final": final pop size, "T_contraction": time of contraction (generations ago)} - For "sawtooth": {"N_values": list of population sizes, "times": list of times for changes}',
                "default": None
            },
            {
                "name": 'coalescent_model',
                "type": 'str',
                "description": 'Type of coalescent model to use. Options: - "kingman": Standard Kingman coalescent - "beta": Beta-coalescent model',
                "default": 'kingman'
            },
            {
                "name": 'beta_coalescent_param',
                "type": 'float',
                "description": 'Parameter for beta-coalescent model (required if coalescent_model="beta")',
                "default": None
            },
            {
                "name": 'random_seed',
                "type": 'int',
                "description": 'Seed for random number generator (for reproducibility)',
                "default": None
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Filename to save the simulated sequences (VCF format)',
                "default": 'simulated_sequences.vcf'
            },
        ],
    },
    {
        "name": 'identify_transcription_factor_binding_sites',
        "description": 'Identifies binding sites for a specific transcription factor in a genomic sequence.',
        "required_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'The genomic DNA sequence to analyze',
                "default": None
            },
            {
                "name": 'tf_name',
                "type": 'str',
                "description": "Name of the transcription factor to search for (e.g., 'Hsf1', 'GATA1')",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'threshold',
                "type": 'float',
                "description": 'Minimum score threshold for reporting binding sites (0.0-1.0, default: 0.8)',
                "default": 0.8
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Path to save the results (default: None, results only in log)',
                "default": None
            },
        ],
    },
    {
        "name": 'fit_genomic_prediction_model',
        "description": 'Fit a linear mixed model for genomic prediction using genotype and phenotype data.',
        "required_parameters": [
            {
                "name": 'genotypes',
                "type": 'numpy.ndarray',
                "description": 'Matrix of genotype data, with individuals in rows and markers in columns. Values are typically coded as 0, 1, 2 for additive models or with specific encoding for dominance effects.',
                "default": None
            },
            {
                "name": 'phenotypes',
                "type": 'numpy.ndarray',
                "description": 'Vector or matrix of phenotype data, with individuals in rows and traits in columns.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'fixed_effects',
                "type": 'numpy.ndarray',
                "description": 'Matrix of fixed effects (e.g., environment, management), with individuals in rows and effects in columns.',
                "default": None
            },
            {
                "name": 'model_type',
                "type": 'str',
                "description": 'Type of genetic model to fit: "additive" or "additive_dominance".',
                "default": 'additive'
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'File name to save the results.',
                "default": 'genomic_prediction_results.csv'
            },
        ],
    },
    {
        "name": 'perform_pcr_and_gel_electrophoresis',
        "description": 'Performs PCR amplification of a target transgene and visualizes results using agarose gel electrophoresis.',
        "required_parameters": [
            {
                "name": 'genomic_dna',
                "type": 'str',
                "description": 'Path to file containing genomic DNA sequence in FASTA format or the sequence itself',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'forward_primer',
                "type": 'str',
                "description": 'Forward primer sequence. If not provided, will be designed based on target_region',
                "default": None
            },
            {
                "name": 'reverse_primer',
                "type": 'str',
                "description": 'Reverse primer sequence. If not provided, will be designed based on target_region',
                "default": None
            },
            {
                "name": 'target_region',
                "type": 'tuple',
                "description": 'Tuple of (start, end) positions for the target region in the genomic DNA',
                "default": None
            },
            {
                "name": 'annealing_temp',
                "type": 'float',
                "description": 'Annealing temperature for PCR in °C',
                "default": 58
            },
            {
                "name": 'extension_time',
                "type": 'int',
                "description": 'Extension time in seconds',
                "default": 30
            },
            {
                "name": 'cycles',
                "type": 'int',
                "description": 'Number of PCR cycles',
                "default": 35
            },
            {
                "name": 'gel_percentage',
                "type": 'float',
                "description": 'Percentage of agarose gel',
                "default": 2.0
            },
            {
                "name": 'output_prefix',
                "type": 'str',
                "description": 'Prefix for output files',
                "default": 'pcr_result'
            },
        ],
    },
    {
        "name": 'analyze_protein_phylogeny',
        "description": 'Perform phylogenetic analysis on a set of protein sequences. This function takes protein sequences in FASTA format, performs multiple sequence alignment, constructs a phylogenetic tree, and visualizes the evolutionary relationships.',
        "required_parameters": [
            {
                "name": 'fasta_sequences',
                "type": 'str',
                "description": 'Path to a FASTA file containing protein sequences or a string with FASTA-formatted sequences',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: current directory)',
                "default": './'
            },
            {
                "name": 'alignment_method',
                "type": 'str',
                "description": 'Method for sequence alignment: "clustalw", "muscle", or "pre-aligned" (default: "clustalw")',
                "default": 'clustalw'
            },
            {
                "name": 'tree_method',
                "type": 'str',
                "description": 'Method for tree construction: "iqtree" (default: "iqtree")',
                "default": 'fasttree'
            },
        ],
    },
    {
        "name": 'forward',
        "description": 'Function forward',
        "required_parameters": [
            {
                "name": 'x',
                "type": 'str',
                "description": 'Parameter x',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'elbo_loss',
        "description": 'Function elbo_loss',
        "required_parameters": [
            {
                "name": 'z_scores',
                "type": 'str',
                "description": 'Parameter z_scores',
                "default": None
            },
            {
                "name": 'ld_matrix',
                "type": 'str',
                "description": 'Parameter ld_matrix',
                "default": None
            },
            {
                "name": 'pips',
                "type": 'str',
                "description": 'Parameter pips',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'n_samples',
                "type": 'int',
                "description": 'Parameter n_samples',
                "default": 10
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
