"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'get_hpo_names',
        "description": "Retrieve the names of given HPO terms. Args: hpo_terms (List[str]): A list of HPO terms (e.g., ['HP:0001250']). Returns: List[str]: A list of corresponding HPO term names.",
        "required_parameters": [
            {
                "name": 'hpo_terms',
                "type": 'str',
                "description": 'Parameter hpo_terms',
                "default": None
            },
            {
                "name": 'data_lake_path',
                "type": 'str',
                "description": 'Parameter data_lake_path',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'query_uniprot',
        "description": 'Query the UniProt REST API using either natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 5
            },
        ],
    },
    {
        "name": 'query_alphafold',
        "description": 'Query the AlphaFold Database API for protein structure predictions.',
        "required_parameters": [
            {
                "name": 'uniprot_id',
                "type": 'str',
                "description": 'Parameter uniprot_id',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": 'prediction'
            },
            {
                "name": 'residue_range',
                "type": 'str',
                "description": 'Parameter residue_range',
                "default": None
            },
            {
                "name": 'download',
                "type": 'bool',
                "description": 'Parameter download',
                "default": False
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
            {
                "name": 'file_format',
                "type": 'str',
                "description": 'Parameter file_format',
                "default": 'pdb'
            },
            {
                "name": 'model_version',
                "type": 'str',
                "description": 'Parameter model_version',
                "default": 'v4'
            },
            {
                "name": 'model_number',
                "type": 'int',
                "description": 'Parameter model_number',
                "default": 1
            },
        ],
    },
    {
        "name": 'query_interpro',
        "description": 'Query the InterPro REST API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 3
            },
        ],
    },
    {
        "name": 'query_pdb',
        "description": 'Query the RCSB PDB database using natural language or a direct structured query.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'query',
                "type": 'str',
                "description": 'Parameter query',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 3
            },
        ],
    },
    {
        "name": 'query_pdb_identifiers',
        "description": 'Retrieve detailed data and/or download files for PDB identifiers.',
        "required_parameters": [
            {
                "name": 'identifiers',
                "type": 'list of str',
                "description": 'List of PDB identifiers string. Pass a list even for a single identifier.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'return_type',
                "type": 'str',
                "description": 'Parameter return_type',
                "default": 'entry'
            },
            {
                "name": 'download',
                "type": 'bool',
                "description": 'Parameter download',
                "default": False
            },
            {
                "name": 'attributes',
                "type": 'list of str',
                "description": 'List of attributes to retrieve. Pass a list even for a single attribute.',
                "default": None
            },
        ],
    },
    {
        "name": 'query_kegg',
        "description": 'Take a natural language prompt and convert it to a structured KEGG API query.',
        "required_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_stringdb',
        "description": 'Query the STRING protein interaction database using natural language or direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'download_image',
                "type": 'bool',
                "description": 'Parameter download_image',
                "default": False
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_iucn',
        "description": 'Query the IUCN Red List API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'token',
                "type": 'str',
                "description": 'Parameter token',
                "default": ''
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_paleobiology',
        "description": 'Query the Paleobiology Database (PBDB) API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_jaspar',
        "description": 'Query the JASPAR REST API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_worms',
        "description": 'Query the World Register of Marine Species (WoRMS) REST API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_cbioportal',
        "description": 'Query the cBioPortal REST API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_clinvar',
        "description": 'Take a natural language prompt and convert it to a structured ClinVar query.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'search_term',
                "type": 'str',
                "description": 'Parameter search_term',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 3
            },
        ],
    },
    {
        "name": 'query_geo',
        "description": 'Query the NCBI Gene Expression Omnibus (GEO) using natural language or a direct search term.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'search_term',
                "type": 'str',
                "description": 'Parameter search_term',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 3
            },
        ],
    },
    {
        "name": 'query_dbsnp',
        "description": 'Query the NCBI dbSNP database using natural language or a direct search term.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'search_term',
                "type": 'str',
                "description": 'Parameter search_term',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 3
            },
        ],
    },
    {
        "name": 'query_ucsc',
        "description": 'Query the UCSC Genome Browser API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_ensembl',
        "description": 'Query the Ensembl REST API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_opentarget',
        "description": 'Query the OpenTargets Platform API using natural language or a direct GraphQL query.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'query',
                "type": 'str',
                "description": 'Parameter query',
                "default": None
            },
            {
                "name": 'variables',
                "type": 'str',
                "description": 'Parameter variables',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": False
            },
        ],
    },
    {
        "name": 'query_monarch',
        "description": 'Query the Monarch Initiative API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 2
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": False
            },
        ],
    },
    {
        "name": 'query_openfda',
        "description": 'Query the OpenFDA API using natural language or direct parameters.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 100
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
            {
                "name": 'search_params',
                "type": 'str',
                "description": 'Parameter search_params',
                "default": None
            },
            {
                "name": 'sort_params',
                "type": 'str',
                "description": 'Parameter sort_params',
                "default": None
            },
            {
                "name": 'count_params',
                "type": 'str',
                "description": 'Parameter count_params',
                "default": None
            },
            {
                "name": 'skip_results',
                "type": 'int',
                "description": 'Parameter skip_results',
                "default": 0
            },
        ],
    },
    {
        "name": 'query_gwas_catalog',
        "description": 'Query the GWAS Catalog API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 3
            },
        ],
    },
    {
        "name": 'query_gnomad',
        "description": 'Query gnomAD for variants in a gene using natural language or direct gene symbol.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'gene_symbol',
                "type": 'str',
                "description": 'Parameter gene_symbol',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'blast_sequence',
        "description": 'Identifies a DNA sequence using NCBI BLAST with improved error handling, timeout management, and debugging. Args: sequence (str): The sequence to identify. If DNA, use database: core_nt, program: blastn; if protein, use database: nr, program: blastp database (str): The BLAST database to search against program (str): The BLAST program to use Returns: dict: A dictionary containing the title, e-value, identity percentage, and coverage percentage of the best alignment',
        "required_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'Parameter sequence',
                "default": None
            },
            {
                "name": 'database',
                "type": 'str',
                "description": 'Parameter database',
                "default": None
            },
            {
                "name": 'program',
                "type": 'str',
                "description": 'Parameter program',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'query_reactome',
        "description": 'Query the Reactome database using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'download',
                "type": 'bool',
                "description": 'Parameter download',
                "default": False
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_regulomedb',
        "description": 'Query the RegulomeDB database using natural language or direct variant/coordinate specification.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": False
            },
        ],
    },
    {
        "name": 'query_pride',
        "description": 'Query the PRIDE (PRoteomics IDEntifications) database using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 3
            },
        ],
    },
    {
        "name": 'query_gtopdb',
        "description": 'Query the Guide to PHARMACOLOGY database (GtoPdb) using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'region_to_ccre_screen',
        "description": "Given starting and ending coordinates, this function retrieves information of intersecting cCREs. Args: assembly (str): Assembly of the genome, formatted like 'GRCh38'. Default is 'GRCh38'. coord_chrom (str): Chromosome of the gene, formatted like 'chr12'. coord_start (int): Starting chromosome coordinate. coord_end (int): Ending chromosome coordinate. Returns: str: A detailed string explaining the steps and the intersecting cCRE data or any error encountered.",
        "required_parameters": [
            {
                "name": 'coord_chrom',
                "type": 'str',
                "description": 'Parameter coord_chrom',
                "default": None
            },
            {
                "name": 'coord_start',
                "type": 'str',
                "description": 'Parameter coord_start',
                "default": None
            },
            {
                "name": 'coord_end',
                "type": 'str',
                "description": 'Parameter coord_end',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'assembly',
                "type": 'str',
                "description": 'Parameter assembly',
                "default": 'GRCh38'
            },
        ],
    },
    {
        "name": 'get_genes_near_ccre',
        "description": 'Given a cCRE (Candidate cis-Regulatory Element), this function returns a string containing the steps it performs and the k nearest genes sorted by distance.',
        "required_parameters": [
            {
                "name": 'accession',
                "type": 'str',
                "description": 'Parameter accession',
                "default": None
            },
            {
                "name": 'assembly',
                "type": 'str',
                "description": 'Parameter assembly',
                "default": None
            },
            {
                "name": 'chromosome',
                "type": 'str',
                "description": 'Parameter chromosome',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'k',
                "type": 'int',
                "description": 'Parameter k',
                "default": 10
            },
        ],
    },
    {
        "name": 'query_remap',
        "description": 'Query the ReMap database for regulatory elements and transcription factor binding sites.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_mpd',
        "description": 'Query the Mouse Phenome Database (MPD) for mouse strain phenotype data.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_emdb',
        "description": 'Query the Electron Microscopy Data Bank (EMDB) for 3D macromolecular structures.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_synapse',
        "description": 'Query Synapse REST API for biomedical datasets and files. Synapse is a platform for sharing and analyzing biomedical data, particularly genomics and clinical research datasets. Supports optional authentication via SYNAPSE_AUTH_TOKEN environment variable for access to private datasets.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Natural language query about biomedical data (e.g., "Find drug screening datasets")',
                "default": None
            },
            {
                "name": 'query_term',
                "type": 'str or list of str',
                "description": 'Specific search terms for Synapse search. When multiple terms are provided as a list, they are combined with AND logic (more terms = more restrictive). Start with 1-2 most relevant search terms.',
                "default": None
            },
            {
                "name": 'return_fields',
                "type": 'list of str',
                "description": 'Fields to return in results. Default: ["name", "node_type", "description"]',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Maximum number of results to return. Default 20 is optimal for most searches. Use up to 50 if extensive results are desired for comprehensive analysis.',
                "default": 20
            },
            {
                "name": 'query_type',
                "type": 'str',
                "description": 'Type of entity to search for ("dataset", "file", "folder")',
                "default": 'dataset'
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Whether to return full API response or formatted results',
                "default": True
            },
        ],
    },
    {
        "name": 'query_pubchem',
        "description": 'Query the PubChem PUG-REST API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 5
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_chembl',
        "description": 'Query the ChEMBL REST API using natural language, direct endpoint, or specific identifiers.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'chembl_id',
                "type": 'str',
                "description": 'Parameter chembl_id',
                "default": None
            },
            {
                "name": 'smiles',
                "type": 'str',
                "description": 'Parameter smiles',
                "default": None
            },
            {
                "name": 'molecule_name',
                "type": 'str',
                "description": 'Parameter molecule_name',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 20
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_unichem',
        "description": 'Query the UniChem 2.0 REST API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_clinicaltrials',
        "description": 'Query the ClinicalTrials.gov API v2 using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 10
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_dailymed',
        "description": 'Query the DailyMed RESTful API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'format',
                "type": 'str',
                "description": 'Parameter format',
                "default": 'json'
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_quickgo',
        "description": 'Query the QuickGO API using natural language or a direct endpoint.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 25
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'query_encode',
        "description": 'Query the ENCODE Portal API to help users locate functional genomics data. This function is designed to help users find and explore ENCODE data including: - Experiments (ChIP-seq, RNA-seq, ATAC-seq, DNase-seq, WGBS, etc.) - Files (BAM, BED, bigWig, fastq, etc.) - Biosamples (cell lines, tissues, primary cells) - Datasets and replicates',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'prompt',
                "type": 'str',
                "description": 'Parameter prompt',
                "default": None
            },
            {
                "name": 'endpoint',
                "type": 'str',
                "description": 'Parameter endpoint',
                "default": None
            },
            {
                "name": 'max_results',
                "type": 'int',
                "description": 'Parameter max_results',
                "default": 25
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
        ],
    },
    {
        "name": 'reduce_tokens',
        "description": 'Function reduce_tokens',
        "required_parameters": [
            {
                "name": 'res_json',
                "type": 'str',
                "description": 'Parameter res_json',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
