"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'split_modalities',
        "description": 'Convenience function for splitting modalities',
        "required_parameters": [
            {
                "name": 'input_file',
                "type": 'str',
                "description": 'Parameter input_file',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'case_name',
                "type": 'str',
                "description": 'Parameter case_name',
                "default": 'BRAT'
            },
        ],
    },
    {
        "name": 'prepare_input_for_nnunet',
        "description": 'Convenience function for preparing nnUNet input',
        "required_parameters": [
            {
                "name": 'input_path',
                "type": 'str',
                "description": 'Parameter input_path',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'case_name',
                "type": 'str',
                "description": 'Parameter case_name',
                "default": 'BRAT'
            },
        ],
    },
    {
        "name": 'segment_with_nn_unet',
        "description": 'Convenience function for nnUNet segmentation',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Parameter image_path',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
            {
                "name": 'task_id',
                "type": 'str',
                "description": 'Parameter task_id',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'model_type',
                "type": 'str',
                "description": 'Parameter model_type',
                "default": '3d_fullres'
            },
            {
                "name": 'folds',
                "type": 'str',
                "description": 'Parameter folds',
                "default": None
            },
            {
                "name": 'use_tta',
                "type": 'bool',
                "description": 'Parameter use_tta',
                "default": False
            },
            {
                "name": 'num_threads',
                "type": 'int',
                "description": 'Parameter num_threads',
                "default": 1
            },
            {
                "name": 'mixed_precision',
                "type": 'bool',
                "description": 'Parameter mixed_precision',
                "default": True
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
            {
                "name": 'auto_prepare_input',
                "type": 'bool',
                "description": 'Parameter auto_prepare_input',
                "default": True
            },
            {
                "name": 'results_folder',
                "type": 'str',
                "description": 'Parameter results_folder',
                "default": None
            },
        ],
    },
    {
        "name": 'create_segmentation_visualization',
        "description": 'Convenience function for segmentation visualization',
        "required_parameters": [
            {
                "name": 'original_mri',
                "type": 'str',
                "description": 'Parameter original_mri',
                "default": None
            },
            {
                "name": 'segmentation',
                "type": 'str',
                "description": 'Parameter segmentation',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": './visualization_output'
            },
        ],
    },
    {
        "name": 'preprocess_image',
        "description": 'Standalone image preprocessing function for Biomni integration. Args: image_path: Path to input image output_path: Path to save preprocessed image denoise: Whether to apply denoising (default: True) normalize: Whether to apply normalization (default: True) Returns: Path to the saved preprocessed image',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Parameter image_path',
                "default": None
            },
            {
                "name": 'output_path',
                "type": 'str',
                "description": 'Parameter output_path',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'denoise',
                "type": 'bool',
                "description": 'Parameter denoise',
                "default": True
            },
            {
                "name": 'normalize',
                "type": 'bool',
                "description": 'Parameter normalize',
                "default": True
            },
        ],
    },
    {
        "name": 'quick_rigid_registration',
        "description": 'Quick rigid registration function for Biomni integration. Args: fixed_image_path: Path to reference image moving_image_path: Path to image to register output_dir: Directory to save results metric: Similarity metric optimizer: Optimization method preprocess: Whether to preprocess images create_visualizations: Whether to create visualizations learning_rate: Learning rate for optimizer number_of_iterations: Maximum iterations gradient_convergence_tolerance: Convergence tolerance Returns: Dictionary with registration results',
        "required_parameters": [
            {
                "name": 'fixed_image_path',
                "type": 'str',
                "description": 'Parameter fixed_image_path',
                "default": None
            },
            {
                "name": 'moving_image_path',
                "type": 'str',
                "description": 'Parameter moving_image_path',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'metric',
                "type": 'str',
                "description": 'Parameter metric',
                "default": 'mutual_information'
            },
            {
                "name": 'optimizer',
                "type": 'str',
                "description": 'Parameter optimizer',
                "default": 'gradient_descent'
            },
            {
                "name": 'preprocess',
                "type": 'bool',
                "description": 'Parameter preprocess',
                "default": True
            },
            {
                "name": 'create_visualizations',
                "type": 'bool',
                "description": 'Parameter create_visualizations',
                "default": True
            },
            {
                "name": 'learning_rate',
                "type": 'float',
                "description": 'Parameter learning_rate',
                "default": 0.01
            },
            {
                "name": 'number_of_iterations',
                "type": 'int',
                "description": 'Parameter number_of_iterations',
                "default": 100
            },
            {
                "name": 'gradient_convergence_tolerance',
                "type": 'float',
                "description": 'Parameter gradient_convergence_tolerance',
                "default": 1e-06
            },
        ],
    },
    {
        "name": 'quick_affine_registration',
        "description": 'Quick affine registration function for Biomni integration. Args: fixed_image_path: Path to reference image moving_image_path: Path to image to register output_dir: Directory to save results metric: Similarity metric optimizer: Optimization method preprocess: Whether to preprocess images create_visualizations: Whether to create visualizations learning_rate: Learning rate for optimizer number_of_iterations: Maximum iterations gradient_convergence_tolerance: Convergence tolerance Returns: Dictionary with registration results',
        "required_parameters": [
            {
                "name": 'fixed_image_path',
                "type": 'str',
                "description": 'Parameter fixed_image_path',
                "default": None
            },
            {
                "name": 'moving_image_path',
                "type": 'str',
                "description": 'Parameter moving_image_path',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'metric',
                "type": 'str',
                "description": 'Parameter metric',
                "default": 'mutual_information'
            },
            {
                "name": 'optimizer',
                "type": 'str',
                "description": 'Parameter optimizer',
                "default": 'gradient_descent'
            },
            {
                "name": 'preprocess',
                "type": 'bool',
                "description": 'Parameter preprocess',
                "default": True
            },
            {
                "name": 'create_visualizations',
                "type": 'bool',
                "description": 'Parameter create_visualizations',
                "default": True
            },
            {
                "name": 'learning_rate',
                "type": 'float',
                "description": 'Parameter learning_rate',
                "default": 0.01
            },
            {
                "name": 'number_of_iterations',
                "type": 'int',
                "description": 'Parameter number_of_iterations',
                "default": 100
            },
            {
                "name": 'gradient_convergence_tolerance',
                "type": 'float',
                "description": 'Parameter gradient_convergence_tolerance',
                "default": 1e-06
            },
        ],
    },
    {
        "name": 'quick_deformable_registration',
        "description": 'Quick deformable registration function for Biomni integration. Args: fixed_image_path: Path to reference image moving_image_path: Path to image to register output_dir: Directory to save results metric: Similarity metric optimizer: Optimization method preprocess: Whether to preprocess images create_visualizations: Whether to create visualizations learning_rate: Learning rate for optimizer number_of_iterations: Maximum iterations gradient_convergence_tolerance: Convergence tolerance number_of_control_points: Number of B-spline control points Returns: Dictionary with registration results',
        "required_parameters": [
            {
                "name": 'fixed_image_path',
                "type": 'str',
                "description": 'Parameter fixed_image_path',
                "default": None
            },
            {
                "name": 'moving_image_path',
                "type": 'str',
                "description": 'Parameter moving_image_path',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'metric',
                "type": 'str',
                "description": 'Parameter metric',
                "default": 'mutual_information'
            },
            {
                "name": 'optimizer',
                "type": 'str',
                "description": 'Parameter optimizer',
                "default": 'gradient_descent'
            },
            {
                "name": 'preprocess',
                "type": 'bool',
                "description": 'Parameter preprocess',
                "default": True
            },
            {
                "name": 'create_visualizations',
                "type": 'bool',
                "description": 'Parameter create_visualizations',
                "default": True
            },
            {
                "name": 'learning_rate',
                "type": 'float',
                "description": 'Parameter learning_rate',
                "default": 0.01
            },
            {
                "name": 'number_of_iterations',
                "type": 'int',
                "description": 'Parameter number_of_iterations',
                "default": 100
            },
            {
                "name": 'gradient_convergence_tolerance',
                "type": 'float',
                "description": 'Parameter gradient_convergence_tolerance',
                "default": 1e-06
            },
            {
                "name": 'number_of_control_points',
                "type": 'int',
                "description": 'Parameter number_of_control_points',
                "default": 4
            },
        ],
    },
    {
        "name": 'batch_register_images',
        "description": "Batch registration of multiple images to a single reference. Args: fixed_image_path: Path to reference image moving_images_dir: Directory containing images to register output_dir: Directory to save results transform_type: Type of registration ('rigid', 'affine', 'deformable') metric: Similarity metric optimizer: Optimization method preprocess: Whether to preprocess images create_visualizations: Whether to create visualizations learning_rate: Learning rate for optimizer number_of_iterations: Maximum iterations gradient_convergence_tolerance: Convergence tolerance Returns: Dictionary with batch registration results",
        "required_parameters": [
            {
                "name": 'fixed_image_path',
                "type": 'str',
                "description": 'Parameter fixed_image_path',
                "default": None
            },
            {
                "name": 'moving_images_dir',
                "type": 'str',
                "description": 'Parameter moving_images_dir',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'transform_type',
                "type": 'str',
                "description": 'Parameter transform_type',
                "default": 'rigid'
            },
            {
                "name": 'metric',
                "type": 'str',
                "description": 'Parameter metric',
                "default": 'mutual_information'
            },
            {
                "name": 'optimizer',
                "type": 'str',
                "description": 'Parameter optimizer',
                "default": 'gradient_descent'
            },
            {
                "name": 'preprocess',
                "type": 'bool',
                "description": 'Parameter preprocess',
                "default": True
            },
            {
                "name": 'create_visualizations',
                "type": 'bool',
                "description": 'Parameter create_visualizations',
                "default": True
            },
            {
                "name": 'learning_rate',
                "type": 'float',
                "description": 'Parameter learning_rate',
                "default": 0.01
            },
            {
                "name": 'number_of_iterations',
                "type": 'int',
                "description": 'Parameter number_of_iterations',
                "default": 100
            },
            {
                "name": 'gradient_convergence_tolerance',
                "type": 'float',
                "description": 'Parameter gradient_convergence_tolerance',
                "default": 1e-06
            },
        ],
    },
    {
        "name": 'calculate_similarity_metrics',
        "description": 'Calculate similarity metrics between two images. Args: image1_path: Path to first image image2_path: Path to second image Returns: Dictionary of similarity metrics',
        "required_parameters": [
            {
                "name": 'image1_path',
                "type": 'str',
                "description": 'Parameter image1_path',
                "default": None
            },
            {
                "name": 'image2_path',
                "type": 'str',
                "description": 'Parameter image2_path',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'split_modalities',
        "description": 'Split a 4D NIfTI file into separate modality files for nnUNet Args: input_file: Path to the 4D NIfTI file output_dir: Directory to save the split files case_name: Base name for the case (default: BRAT) Returns: output_dir: Path to directory containing split modality files',
        "required_parameters": [
            {
                "name": 'input_file',
                "type": 'str',
                "description": 'Parameter input_file',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'case_name',
                "type": 'str',
                "description": 'Parameter case_name',
                "default": 'BRAT'
            },
        ],
    },
    {
        "name": 'prepare_input_for_nnunet',
        "description": 'Prepare input data for nnUNet by handling both 4D and pre-split modality files Args: input_path: Path to input file or directory output_dir: Directory to save prepared files case_name: Base name for the case (default: BRAT) Returns: prepared_dir: Path to directory with nnUNet-ready files',
        "required_parameters": [
            {
                "name": 'input_path',
                "type": 'str',
                "description": 'Parameter input_path',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'case_name',
                "type": 'str',
                "description": 'Parameter case_name',
                "default": 'BRAT'
            },
        ],
    },
    {
        "name": 'setup_nnunet_environment',
        "description": 'Setup nnU-Net environment variables according to official documentation Args: results_folder: Path to nnUNet results folder (default: ~/nnUNet_results) raw_data_base: Path to raw data base (default: ~/nnUNet_raw_data_base) preprocessed: Path to preprocessed data (default: ~/nnUNet_preprocessed)',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'results_folder',
                "type": 'str',
                "description": 'Parameter results_folder',
                "default": None
            },
            {
                "name": 'raw_data_base',
                "type": 'str',
                "description": 'Parameter raw_data_base',
                "default": None
            },
            {
                "name": 'preprocessed',
                "type": 'str',
                "description": 'Parameter preprocessed',
                "default": None
            },
        ],
    },
    {
        "name": 'segment_with_nn_unet',
        "description": "Segment images using nnUNet with proper environment setup and automatic model downloading Args: image_path: Path to input image file or directory output_dir: Directory to save segmentation results task_id: Task identifier (e.g., 'Task001_BrainTumour') model_type: Model type (default: '3d_fullres') folds: Model folds to use (default: [0, 1, 2, 3, 4]) use_tta: Use test time augmentation (default: False) num_threads: Number of threads for preprocessing (default: 1) mixed_precision: Use mixed precision (default: True) verbose: Verbose logging (default: True) auto_prepare_input: Automatically prepare input for nnUNet (default: True) results_folder: Path to nnUNet results folder (default: None, will use environment variable or default) auto_download: Automatically download missing models (default: True)",
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Parameter image_path',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
            {
                "name": 'task_id',
                "type": 'str',
                "description": 'Parameter task_id',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'model_type',
                "type": 'str',
                "description": 'Parameter model_type',
                "default": '3d_fullres'
            },
            {
                "name": 'folds',
                "type": 'str',
                "description": 'Parameter folds',
                "default": None
            },
            {
                "name": 'use_tta',
                "type": 'bool',
                "description": 'Parameter use_tta',
                "default": False
            },
            {
                "name": 'num_threads',
                "type": 'int',
                "description": 'Parameter num_threads',
                "default": 1
            },
            {
                "name": 'mixed_precision',
                "type": 'bool',
                "description": 'Parameter mixed_precision',
                "default": True
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Parameter verbose',
                "default": True
            },
            {
                "name": 'auto_prepare_input',
                "type": 'bool',
                "description": 'Parameter auto_prepare_input',
                "default": True
            },
            {
                "name": 'results_folder',
                "type": 'str',
                "description": 'Parameter results_folder',
                "default": None
            },
            {
                "name": 'auto_download',
                "type": 'bool',
                "description": 'Parameter auto_download',
                "default": True
            },
        ],
    },
    {
        "name": 'create_segmentation_visualization',
        "description": 'Create and save visualization of segmentation results using nilearn Args: original_mri: Path to original MRI file segmentation: Path to segmentation file output_dir: Directory to save visualization images Returns: list: List of saved image file paths',
        "required_parameters": [
            {
                "name": 'original_mri',
                "type": 'str',
                "description": 'Parameter original_mri',
                "default": None
            },
            {
                "name": 'segmentation',
                "type": 'str',
                "description": 'Parameter segmentation',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": './visualization_output'
            },
        ],
    },
    {
        "name": 'load_image',
        "description": 'Load a medical image using SimpleITK. Args: image_path: Path to the image file Returns: SimpleITK Image object',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Parameter image_path',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'save_image',
        "description": 'Save a SimpleITK image to file. Args: image: SimpleITK Image object output_path: Path to save the image (must include filename and extension)',
        "required_parameters": [
            {
                "name": 'image',
                "type": 'str',
                "description": 'Parameter image',
                "default": None
            },
            {
                "name": 'output_path',
                "type": 'str',
                "description": 'Parameter output_path',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'preprocess_image',
        "description": 'Preprocess an image with denoising and normalization. Args: image: Input SimpleITK image denoise: Whether to apply denoising normalize: Whether to apply normalization Returns: Preprocessed SimpleITK image',
        "required_parameters": [
            {
                "name": 'image',
                "type": 'str',
                "description": 'Parameter image',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'denoise',
                "type": 'bool',
                "description": 'Parameter denoise',
                "default": True
            },
            {
                "name": 'normalize',
                "type": 'bool',
                "description": 'Parameter normalize',
                "default": True
            },
        ],
    },
    {
        "name": 'create_rigid_transform',
        "description": 'Create a rigid transform for image registration. Args: fixed_image: Reference (fixed) image moving_image: Image to be registered initial_transform: Optional initial transform Returns: Rigid transform object',
        "required_parameters": [
            {
                "name": 'fixed_image',
                "type": 'str',
                "description": 'Parameter fixed_image',
                "default": None
            },
            {
                "name": 'moving_image',
                "type": 'str',
                "description": 'Parameter moving_image',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'initial_transform',
                "type": 'str',
                "description": 'Parameter initial_transform',
                "default": None
            },
        ],
    },
    {
        "name": 'create_affine_transform',
        "description": 'Create an affine transform for image registration. Args: fixed_image: Reference (fixed) image moving_image: Image to be registered initial_transform: Optional initial transform Returns: Affine transform object',
        "required_parameters": [
            {
                "name": 'fixed_image',
                "type": 'str',
                "description": 'Parameter fixed_image',
                "default": None
            },
            {
                "name": 'moving_image',
                "type": 'str',
                "description": 'Parameter moving_image',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'initial_transform',
                "type": 'str',
                "description": 'Parameter initial_transform',
                "default": None
            },
        ],
    },
    {
        "name": 'create_deformable_transform',
        "description": 'Create a deformable (B-spline) transform for image registration. Args: fixed_image: Reference (fixed) image moving_image: Image to be registered number_of_control_points: Number of B-spline control points per dimension Returns: Deformable transform object',
        "required_parameters": [
            {
                "name": 'fixed_image',
                "type": 'str',
                "description": 'Parameter fixed_image',
                "default": None
            },
            {
                "name": 'moving_image',
                "type": 'str',
                "description": 'Parameter moving_image',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'number_of_control_points',
                "type": 'int',
                "description": 'Parameter number_of_control_points',
                "default": 4
            },
        ],
    },
    {
        "name": 'setup_registration_method',
        "description": 'Setup the registration method with specified parameters. Args: transform: Transform object metric: Similarity metric name optimizer: Optimizer name learning_rate: Learning rate for gradient descent number_of_iterations: Maximum number of iterations gradient_convergence_tolerance: Convergence tolerance Returns: Configured registration method',
        "required_parameters": [
            {
                "name": 'transform',
                "type": 'str',
                "description": 'Parameter transform',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'metric',
                "type": 'str',
                "description": 'Parameter metric',
                "default": 'mutual_information'
            },
            {
                "name": 'optimizer',
                "type": 'str',
                "description": 'Parameter optimizer',
                "default": 'gradient_descent'
            },
            {
                "name": 'learning_rate',
                "type": 'float',
                "description": 'Parameter learning_rate',
                "default": 0.01
            },
            {
                "name": 'number_of_iterations',
                "type": 'int',
                "description": 'Parameter number_of_iterations',
                "default": 100
            },
            {
                "name": 'gradient_convergence_tolerance',
                "type": 'float',
                "description": 'Parameter gradient_convergence_tolerance',
                "default": 1e-06
            },
        ],
    },
    {
        "name": 'register_images',
        "description": 'Perform image registration. Args: fixed_image: Reference (fixed) image moving_image: Image to be registered transform: Transform object registration_method: Configured registration method Returns: Tuple of (final_transform, registered_image)',
        "required_parameters": [
            {
                "name": 'fixed_image',
                "type": 'str',
                "description": 'Parameter fixed_image',
                "default": None
            },
            {
                "name": 'moving_image',
                "type": 'str',
                "description": 'Parameter moving_image',
                "default": None
            },
            {
                "name": 'transform',
                "type": 'str',
                "description": 'Parameter transform',
                "default": None
            },
            {
                "name": 'registration_method',
                "type": 'str',
                "description": 'Parameter registration_method',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'calculate_similarity_metrics',
        "description": 'Calculate similarity metrics between two images. Args: image1: First image image2: Second image Returns: Dictionary of similarity metrics',
        "required_parameters": [
            {
                "name": 'image1',
                "type": 'str',
                "description": 'Parameter image1',
                "default": None
            },
            {
                "name": 'image2',
                "type": 'str',
                "description": 'Parameter image2',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'verify_nifti_input',
        "description": 'Function verify_nifti_input',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Parameter image_path',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'check_model_files_exist',
        "description": 'Check if actual model weight files exist for the specified folds',
        "required_parameters": [
            {
                "name": 'model_folder',
                "type": 'str',
                "description": 'Parameter model_folder',
                "default": None
            },
            {
                "name": 'folds',
                "type": 'str',
                "description": 'Parameter folds',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'patched_torch_load',
        "description": 'Function patched_torch_load',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'command_iteration',
        "description": 'Function command_iteration',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
