"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'run_diffdock_with_smiles',
        "description": 'Function run_diffdock_with_smiles',
        "required_parameters": [
            {
                "name": 'pdb_path',
                "type": 'str',
                "description": 'Parameter pdb_path',
                "default": None
            },
            {
                "name": 'smiles_string',
                "type": 'str',
                "description": 'Parameter smiles_string',
                "default": None
            },
            {
                "name": 'local_output_dir',
                "type": 'str',
                "description": 'Parameter local_output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'gpu_device',
                "type": 'int',
                "description": 'Parameter gpu_device',
                "default": 0
            },
            {
                "name": 'use_gpu',
                "type": 'bool',
                "description": 'Parameter use_gpu',
                "default": True
            },
        ],
    },
    {
        "name": 'docking_autodock_vina',
        "description": 'Dock one or more small molecules into a receptor protein structure with AutoDock Vina and return binding scores.',
        "required_parameters": [
            {
                "name": 'smiles_list',
                "type": 'list of str',
                "description": 'List of SMILES strings, one entry per compound to dock (e.g. ["CCO", "c1ccccc1O"]). Pass a list even for a single molecule.',
                "default": None
            },
            {
                "name": 'receptor_pdb_file',
                "type": 'str',
                "description": 'Path to the receptor protein structure PDB file',
                "default": None
            },
            {
                "name": 'box_center',
                "type": 'list of float',
                "description": '[x, y, z] coordinates of the docking box center, in Angstroms (e.g. [10.0, 12.5, -3.0]).',
                "default": None
            },
            {
                "name": 'box_size',
                "type": 'list of float',
                "description": '[x, y, z] dimensions of the docking box, in Angstroms (e.g. [20.0, 20.0, 20.0]).',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'ncpu',
                "type": 'int',
                "description": 'Number of CPU cores to use for docking',
                "default": 1
            },
        ],
    },
    {
        "name": 'run_autosite',
        "description": 'Function run_autosite',
        "required_parameters": [
            {
                "name": 'pdb_file',
                "type": 'str',
                "description": 'Parameter pdb_file',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'spacing',
                "type": 'float',
                "description": 'Parameter spacing',
                "default": 1.0
            },
        ],
    },
    {
        "name": 'retrieve_topk_repurposing_drugs_from_disease_txgnn',
        "description": 'This function computes TxGNN model predictions for drug repurposing. It takes in the paths to the data, the disease name, and returns a summary of the top K predicted drugs with their sigmoid-transformed scores. Args: - disease_name (str): The name of the disease for which the drug predictions are to be retrieved. - data_lake_path (str): The path to the data lake containing the TxGNN predictions. - k (int, optional): The number of top drug predictions to return. Defaults to 5. Returns: - str: A summary of the steps and the top K drug predictions with their scores.',
        "required_parameters": [
            {
                "name": 'disease_name',
                "type": 'str',
                "description": 'Parameter disease_name',
                "default": None
            },
            {
                "name": 'data_lake_path',
                "type": 'str',
                "description": 'Parameter data_lake_path',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'k',
                "type": 'int',
                "description": 'Parameter k',
                "default": 5
            },
        ],
    },
    {
        "name": 'predict_admet_properties',
        "description": 'Predict ADMET (absorption, distribution, metabolism, excretion, toxicity) properties for one or more compounds using pretrained DeepPurpose models (e.g. aqueous solubility, Caco-2, HIA, P-gp, bioavailability, BBB, PPBR, CYP450 isoforms, ClinTox, lipophilicity, half-life, clearance).',
        "required_parameters": [
            {
                "name": 'smiles_list',
                "type": 'list',
                "description": 'List of SMILES strings, one entry per compound (e.g. ["CCO", "c1ccccc1O"]). Pass a list even for a single molecule, e.g. ["CCO"]; do not pass a bare SMILES string.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'ADMET_model_type',
                "type": 'str',
                "description": 'Model architecture for the pretrained ADMET predictors. One of "MPNN", "CNN", or "Morgan".',
                "default": 'MPNN'
            },
        ],
    },
    {
        "name": 'predict_binding_affinity_protein_1d_sequence',
        "description": 'Predict drug-target binding affinity between one or more compounds and a protein target (given as a 1D amino-acid sequence) using a pretrained DeepPurpose DTI model.',
        "required_parameters": [
            {
                "name": 'smiles_list',
                "type": 'list',
                "description": 'List of SMILES strings, one entry per compound (e.g. ["CCO", "c1ccccc1O"]). Pass a list even for a single molecule, e.g. ["CCO"]; do not pass a bare SMILES string.',
                "default": None
            },
            {
                "name": 'amino_acid_sequence',
                "type": 'str',
                "description": 'Target protein sequence as a single-letter amino-acid string (e.g. "MKTAYIAKQR..."). Affinity is predicted for every compound in smiles_list against this target.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'affinity_model_type',
                "type": 'str',
                "description": 'Pretrained DeepPurpose DTI model encoder to use (e.g. "MPNN-CNN").',
                "default": 'MPNN-CNN'
            },
        ],
    },
    {
        "name": 'analyze_accelerated_stability_of_pharmaceutical_formulations',
        "description": 'Analyzes the stability of pharmaceutical formulations under accelerated storage conditions.',
        "required_parameters": [
            {
                "name": 'formulations',
                "type": 'list of dict',
                "description": "List of formulation dictionaries, each containing: - 'name': str, name of the formulation - 'active_ingredient': str, name of the active pharmaceutical ingredient - 'concentration': float, concentration in mg/mL - 'excipients': list, list of excipients",
                "default": None
            },
            {
                "name": 'storage_conditions',
                "type": 'list of dict',
                "description": 'List of storage condition dictionaries, each containing: - \'temperature\': float, temperature in °C - \'humidity\': float, relative humidity in percentage (optional for solid dosage forms) - \'description\': str, description of storage condition (e.g., "Room Temperature", "Accelerated")',
                "default": None
            },
            {
                "name": 'time_points',
                "type": 'list of int',
                "description": 'List of time points in days to evaluate stability',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'run_3d_chondrogenic_aggregate_assay',
        "description": "Generates a detailed protocol for performing a 3D chondrogenic aggregate culture assay to evaluate compounds' effects on chondrogenesis.",
        "required_parameters": [
            {
                "name": 'chondrocyte_cells',
                "type": 'dict',
                "description": "Dictionary with cell information including 'source', 'passage_number', and 'cell_density'",
                "default": None
            },
            {
                "name": 'test_compounds',
                "type": 'list of dict',
                "description": "List of compounds to test, each with 'name', 'concentration', and 'vehicle' keys",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'culture_duration_days',
                "type": 'int',
                "description": 'Total duration of the culture period in days (default: 21)',
                "default": 21
            },
            {
                "name": 'measurement_intervals',
                "type": 'int',
                "description": 'Interval in days between measurements (default: 7)',
                "default": 7
            },
        ],
    },
    {
        "name": 'grade_adverse_events_using_vcog_ctcae',
        "description": 'Grade and monitor adverse events in animal studies using the VCOG-CTCAE standard.',
        "required_parameters": [
            {
                "name": 'clinical_data_file',
                "type": 'str',
                "description": 'Path to a CSV file containing clinical evaluation data with columns: subject_id, time_point, symptom, severity, measurement (optional)',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'analyze_radiolabeled_antibody_biodistribution',
        "description": 'Analyze biodistribution and pharmacokinetic profile of radiolabeled antibodies.',
        "required_parameters": [
            {
                "name": 'time_points',
                "type": 'list or numpy.ndarray',
                "description": 'Time points (hours) at which measurements were taken',
                "default": None
            },
            {
                "name": 'tissue_data',
                "type": 'dict',
                "description": "Dictionary where keys are tissue names and values are lists/arrays of %IA/g measurements corresponding to time_points. Must include 'tumor' as one of the keys.",
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'estimate_alpha_particle_radiotherapy_dosimetry',
        "description": 'Estimate radiation absorbed doses to tumor and normal organs for alpha-particle radiotherapeutics. This function implements the Medical Internal Radiation Dose (MIRD) schema to calculate absorbed doses based on biodistribution data from healthy mice and radiation transport parameters.',
        "required_parameters": [
            {
                "name": 'biodistribution_data',
                "type": 'dict',
                "description": "Dictionary containing organ/tissue names as keys and a list of time-activity measurements as values. Each measurement should be a tuple of (time_hours, percent_injected_activity). Must include entries for all relevant organs including 'tumor'.",
                "default": None
            },
            {
                "name": 'radiation_parameters',
                "type": 'dict',
                "description": "Dictionary containing radiation parameters for the alpha-emitting radionuclide: - 'radionuclide': str - Name of the radionuclide (e.g., 'Ac-225') - 'half_life_hours': float - Physical half-life in hours - 'energy_per_decay_MeV': float - Energy released per decay in MeV - 'radiation_weighting_factor': float - Radiation weighting factor for alpha particles - 'S_factors': dict - S-factors (Gy/Bq-s) for each source-target organ pair",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Filename to save the dosimetry results (default: "dosimetry_results.csv")',
                "default": 'dosimetry_results.csv'
            },
        ],
    },
    {
        "name": 'perform_mwas_cyp2c19_metabolizer_status',
        "description": 'Perform a Methylome-wide Association Study (MWAS) to identify CpG sites significantly associated with CYP2C19 metabolizer status.',
        "required_parameters": [
            {
                "name": 'methylation_data_path',
                "type": 'str',
                "description": 'Path to CSV or TSV file containing DNA methylation beta values. Rows should be samples, columns should be CpG sites.',
                "default": None
            },
            {
                "name": 'metabolizer_status_path',
                "type": 'str',
                "description": 'Path to CSV or TSV file containing CYP2C19 metabolizer status for each sample. Should have a sample ID column and a status column (e.g., poor, intermediate, normal, rapid, ultrarapid).',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'covariates_path',
                "type": 'str',
                "description": 'Path to CSV or TSV file containing covariates to adjust for in the regression model (e.g., age, sex, smoking status).',
                "default": None
            },
            {
                "name": 'pvalue_threshold',
                "type": 'float',
                "description": 'P-value threshold for significance after multiple testing correction. Default is 0.05.',
                "default": 0.05
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Filename to save significant CpG sites. Default is "significant_cpg_sites.csv".',
                "default": 'significant_cpg_sites.csv'
            },
        ],
    },
    {
        "name": 'calculate_physicochemical_properties',
        "description": 'Calculate key physicochemical properties of a drug candidate molecule.',
        "required_parameters": [
            {
                "name": 'smiles_string',
                "type": 'str',
                "description": 'The molecular structure in SMILES format',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'analyze_xenograft_tumor_growth_inhibition',
        "description": 'Analyze tumor growth inhibition in xenograft models across different treatment groups.',
        "required_parameters": [
            {
                "name": 'data_path',
                "type": 'str',
                "description": 'Path to CSV or TSV file containing tumor volume measurements. The file should have columns for time, volume, treatment group, and subject ID',
                "default": None
            },
            {
                "name": 'time_column',
                "type": 'str',
                "description": "Name of the column containing time points (e.g., 'Day', 'Time')",
                "default": None
            },
            {
                "name": 'volume_column',
                "type": 'str',
                "description": 'Name of the column containing tumor volume measurements',
                "default": None
            },
            {
                "name": 'group_column',
                "type": 'str',
                "description": 'Name of the column containing treatment group labels',
                "default": None
            },
            {
                "name": 'subject_column',
                "type": 'str',
                "description": 'Name of the column containing subject/mouse identifiers',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: "./results")',
                "default": './results'
            },
        ],
    },
    {
        "name": 'analyze_western_blot',
        "description": 'Performs densitometric analysis of Western blot images to quantify relative protein expression.',
        "required_parameters": [
            {
                "name": 'blot_image_path',
                "type": 'str',
                "description": 'Path to the Western blot image file',
                "default": None
            },
            {
                "name": 'target_bands',
                "type": 'list of dict',
                "description": "List of dictionaries containing information about target protein bands Each dict should have 'name', 'roi' (region of interest as [x, y, width, height])",
                "default": None
            },
            {
                "name": 'loading_control_band',
                "type": 'dict',
                "description": "Dictionary with 'name' and 'roi' for the loading control protein (e.g., β-actin, GAPDH)",
                "default": None
            },
            {
                "name": 'antibody_info',
                "type": 'dict',
                "description": "Dictionary containing information about antibodies used Should have 'primary' and 'secondary' keys with antibody details",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": "Directory to save output files, defaults to './results'",
                "default": './results'
            },
        ],
    },
    {
        "name": 'query_drug_interactions',
        "description": 'Query drug-drug interactions from DDInter database.',
        "required_parameters": [
            {
                "name": 'drug_names',
                "type": 'list of str',
                "description": 'List of drug names to query for interactions',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'interaction_types',
                "type": 'list of str',
                "description": "Filter by interaction types (e.g., ['synergistic', 'antagonistic'])",
                "default": None
            },
            {
                "name": 'severity_levels',
                "type": 'list of str',
                "description": "Filter by severity levels (e.g., ['Major', 'Moderate', 'Minor'])",
                "default": None
            },
            {
                "name": 'data_lake_path',
                "type": 'str',
                "description": 'Path to data lake directory containing DDInter data',
                "default": None
            },
        ],
    },
    {
        "name": 'check_drug_combination_safety',
        "description": 'Analyze safety of a drug combination for potential interactions.',
        "required_parameters": [
            {
                "name": 'drug_list',
                "type": 'list of str',
                "description": 'List of drugs to analyze for combination safety',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'include_mechanisms',
                "type": 'bool',
                "description": 'Include interaction mechanism descriptions',
                "default": True
            },
            {
                "name": 'include_management',
                "type": 'bool',
                "description": 'Include management recommendations',
                "default": True
            },
            {
                "name": 'data_lake_path',
                "type": 'str',
                "description": 'Path to data lake directory containing DDInter data',
                "default": None
            },
        ],
    },
    {
        "name": 'analyze_interaction_mechanisms',
        "description": 'Analyze interaction mechanisms between two specific drugs.',
        "required_parameters": [
            {
                "name": 'drug_pair',
                "type": 'tuple of str',
                "description": 'Pair of drug names to analyze (drug1, drug2)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'detailed_analysis',
                "type": 'bool',
                "description": 'Include detailed mechanistic information',
                "default": True
            },
            {
                "name": 'data_lake_path',
                "type": 'str',
                "description": 'Path to data lake directory containing DDInter data',
                "default": None
            },
        ],
    },
    {
        "name": 'find_alternative_drugs_ddinter',
        "description": "Find alternative drugs that don't interact with contraindicated drugs.",
        "required_parameters": [
            {
                "name": 'target_drug',
                "type": 'str',
                "description": 'Drug to find alternatives for',
                "default": None
            },
            {
                "name": 'contraindicated_drugs',
                "type": 'list of str',
                "description": 'List of drugs to avoid interactions with',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'therapeutic_class',
                "type": 'str',
                "description": 'Limit search to specific therapeutic class',
                "default": None
            },
            {
                "name": 'data_lake_path',
                "type": 'str',
                "description": 'Path to data lake directory containing DDInter data',
                "default": None
            },
        ],
    },
    {
        "name": 'query_fda_adverse_events',
        "description": 'Query FDA adverse event reports for specific drugs. Args: drug_name: Name of the drug to query date_range: Optional date range as (start_date, end_date) in YYYY-MM-DD format severity_filter: Optional filter by severity levels ["serious", "non_serious"] outcome_filter: Optional filter by outcomes ["life_threatening", "hospitalization", "death"] limit: Maximum number of results to return Returns: Formatted string with adverse event analysis',
        "required_parameters": [
            {
                "name": 'drug_name',
                "type": 'str',
                "description": 'Parameter drug_name',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'date_range',
                "type": 'str',
                "description": 'Parameter date_range',
                "default": None
            },
            {
                "name": 'severity_filter',
                "type": 'str',
                "description": 'Parameter severity_filter',
                "default": None
            },
            {
                "name": 'outcome_filter',
                "type": 'str',
                "description": 'Parameter outcome_filter',
                "default": None
            },
            {
                "name": 'limit',
                "type": 'int',
                "description": 'Parameter limit',
                "default": 100
            },
        ],
    },
    {
        "name": 'get_fda_drug_label_info',
        "description": 'Retrieve FDA drug label information. Args: drug_name: Name of the drug to query sections: Optional list of specific sections to retrieve ["indications_and_usage", "contraindications", "warnings", "dosage_and_administration"] Returns: Formatted string with drug label information',
        "required_parameters": [
            {
                "name": 'drug_name',
                "type": 'str',
                "description": 'Parameter drug_name',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'sections',
                "type": 'str',
                "description": 'Parameter sections',
                "default": None
            },
        ],
    },
    {
        "name": 'check_fda_drug_recalls',
        "description": 'Check for FDA drug recalls and enforcement actions. Args: drug_name: Name of the drug to check classification: Optional filter by recall class ["Class I", "Class II", "Class III"] date_range: Optional date range for recalls Returns: Formatted string with recall information',
        "required_parameters": [
            {
                "name": 'drug_name',
                "type": 'str',
                "description": 'Parameter drug_name',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'classification',
                "type": 'str',
                "description": 'Parameter classification',
                "default": None
            },
            {
                "name": 'date_range',
                "type": 'str',
                "description": 'Parameter date_range',
                "default": None
            },
        ],
    },
    {
        "name": 'analyze_fda_safety_signals',
        "description": 'Analyze safety signals across multiple drugs. Args: drug_list: List of drug names to analyze comparison_period: Optional comparison time period signal_threshold: Threshold for signal detection Returns: Formatted string with safety signal analysis',
        "required_parameters": [
            {
                "name": 'drug_list',
                "type": 'str',
                "description": 'Parameter drug_list',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'comparison_period',
                "type": 'str',
                "description": 'Parameter comparison_period',
                "default": None
            },
            {
                "name": 'signal_threshold',
                "type": 'float',
                "description": 'Parameter signal_threshold',
                "default": 2.0
            },
        ],
    },
    {
        "name": 'sigmoid',
        "description": 'Function sigmoid',
        "required_parameters": [
            {
                "name": 'x',
                "type": 'str',
                "description": 'Parameter x',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'apply_vcog_grade',
        "description": 'Apply VCOG-CTCAE grading criteria to an adverse event.',
        "required_parameters": [
            {
                "name": 'symptom',
                "type": 'str',
                "description": 'The type of adverse event',
                "default": None
            },
            {
                "name": 'severity',
                "type": 'str',
                "description": 'The severity description',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'measurement',
                "type": 'float or None',
                "description": 'Quantitative measurement related to the symptom, if available',
                "default": None
            },
        ],
    },
    {
        "name": 'bi_exp_model',
        "description": 'Function bi_exp_model',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'A',
                "type": 'str',
                "description": 'Parameter A',
                "default": None
            },
            {
                "name": 'alpha',
                "type": 'str',
                "description": 'Parameter alpha',
                "default": None
            },
            {
                "name": 'B',
                "type": 'str',
                "description": 'Parameter B',
                "default": None
            },
            {
                "name": 'beta',
                "type": 'str',
                "description": 'Parameter beta',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'query_adverse_events',
        "description": 'Query adverse events with robust error handling and validation.',
        "required_parameters": [
            {
                "name": 'drug_name',
                "type": 'str',
                "description": 'Parameter drug_name',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'limit',
                "type": 'int',
                "description": 'Parameter limit',
                "default": 100
            },
        ],
    },
    {
        "name": 'query_drug_labels',
        "description": 'Query FDA drug label information.',
        "required_parameters": [
            {
                "name": 'drug_name',
                "type": 'str',
                "description": 'Parameter drug_name',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'sections',
                "type": 'str',
                "description": 'Parameter sections',
                "default": None
            },
        ],
    },
    {
        "name": 'query_drug_recalls',
        "description": 'Query FDA drug recall and enforcement information.',
        "required_parameters": [
            {
                "name": 'drug_name',
                "type": 'str',
                "description": 'Parameter drug_name',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'classification',
                "type": 'str',
                "description": 'Parameter classification',
                "default": None
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
