"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'run_python_repl',
        "description": 'Executes Python code in a persistent environment. Pre-loaded data: adata_rna (scRNA AnnData), adata_atac (scATAC AnnData), adata_atac_backed (scATAC SnapATAC2 backed, read-only, if available), adata_combined (joint AnnData, if available). Variables persist across calls. Common libraries (sc, np, pd, plt, sns) are pre-imported.',
        "required_parameters": [
            {
                "name": 'command',
                "type": 'str',
                "description": 'Python code to execute',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'read_function_source_code',
        "description": 'Read the source code of a function from any module path.',
        "required_parameters": [
            {
                "name": 'function_name',
                "type": 'str',
                "description": 'Parameter function_name',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'run_terminal',
        "description": 'Install Python packages only: run pip install (e.g. "pip install scanpy", "pip install numpy"). Use this when a Python package is missing for analysis. NOT appropriate for other shell commands (no curl, git, apt-get, or arbitrary commands). Returns stdout, stderr, and exit code. Use non-interactive flags (e.g. pip install --quiet).',
        "required_parameters": [
            {
                "name": 'command',
                "type": 'str',
                "description": 'pip install command only (e.g. "pip install package-name")',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'cwd',
                "type": 'str',
                "description": 'Working directory for the command. If omitted, uses current directory.',
                "default": None
            },
            {
                "name": 'timeout',
                "type": 'int',
                "description": 'Timeout in seconds (default 120). Command is killed if it runs longer.',
                "default": 120
            },
        ],
    },
    {
        "name": 'download_synapse_data',
        "description": 'Download data from Synapse using entity IDs. Uses the synapse CLI to download files, folders, or projects from Synapse. Requires SYNAPSE_AUTH_TOKEN environment variable for authentication. Automatically installs synapseclient if not available. CRITICAL: Always check entity type from query_synapse() search results or user hints and pass the correct entity_type! The default entity_type="dataset" may not be appropriate for your entity. IMPORTANT: Multiple entity IDs are only supported for entity_type="file". For datasets, folders, and projects, only a single entity_id is supported.',
        "required_parameters": [
            {
                "name": 'entity_ids',
                "type": 'str or list of str',
                "description": 'Synapse entity ID(s) to download. - For files: Can be a single ID string or list of ID strings - For datasets/folders/projects: Must be a single ID string only',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'download_location',
                "type": 'str',
                "description": 'Directory where files will be downloaded (current directory by default)',
                "default": '.'
            },
            {
                "name": 'follow_link',
                "type": 'bool',
                "description": 'Whether to follow links to download the linked entity',
                "default": False
            },
            {
                "name": 'recursive',
                "type": 'bool',
                "description": 'Whether to recursively download folders and their contents ONLY valid for entity_type="folder" - ignored for other types',
                "default": False
            },
            {
                "name": 'timeout',
                "type": 'int',
                "description": 'Timeout in seconds for each download operation',
                "default": 300
            },
            {
                "name": 'entity_type',
                "type": 'str',
                "description": 'Type of Synapse entity ("dataset", "file", "folder", "project") MUST match the actual entity type from search results or user hints! The default "dataset" should only be used for actual datasets. Check the \'node_type\' field in search results to determine correct type.',
                "default": 'dataset'
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
