"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'query_chatnt',
        "description": 'Call ChatNT to answer a question about a DNA sequence.',
        "required_parameters": [
            {
                "name": 'question',
                "type": 'str',
                "description": 'Question to ask about the DNA sequence',
                "default": None
            },
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'DNA sequence to analyze',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'device',
                "type": 'int',
                "description": 'Device to use for the ChatNT model. Default is -1 (CPU).',
                "default": -1
            },
        ],
    },
    {
        "name": 'perform_flux_balance_analysis',
        "description": 'Perform Flux Balance Analysis (FBA) on a genome-scale metabolic network model. FBA is a computational technique that predicts metabolic flux distributions by formulating and solving a linear optimization problem.',
        "required_parameters": [
            {
                "name": 'model_file',
                "type": 'str',
                "description": 'Path to the metabolic model file (SBML or JSON format)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'constraints',
                "type": 'dict',
                "description": 'Dictionary of reaction constraints where keys are reaction IDs and values are tuples of (lower_bound, upper_bound)',
                "default": None
            },
            {
                "name": 'objective_reaction',
                "type": 'str',
                "description": "Reaction ID to use as the objective function (e.g., biomass reaction) If None, uses the model's default objective",
                "default": None
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'File name to save the flux distribution results',
                "default": 'fba_results.csv'
            },
        ],
    },
    {
        "name": 'model_protein_dimerization_network',
        "description": 'Model protein dimerization networks to find equilibrium concentrations of dimers.',
        "required_parameters": [
            {
                "name": 'monomer_concentrations',
                "type": 'dict',
                "description": 'Dictionary mapping monomer names to their initial concentrations (in arbitrary units)',
                "default": None
            },
            {
                "name": 'dimerization_affinities',
                "type": 'dict',
                "description": "Dictionary mapping dimer names (as 'A-B' strings) to their association constants (Ka)",
                "default": None
            },
            {
                "name": 'network_topology',
                "type": 'list of tuples',
                "description": 'List of (monomer1, monomer2) pairs that can form dimers',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'simulate_metabolic_network_perturbation',
        "description": 'Construct and simulate kinetic models of metabolic networks and analyze their responses to perturbations.',
        "required_parameters": [
            {
                "name": 'model_file',
                "type": 'str',
                "description": 'Path to the COBRA model file (SBML format)',
                "default": None
            },
            {
                "name": 'initial_concentrations',
                "type": 'dict',
                "description": 'Dictionary mapping metabolite IDs to their initial concentrations',
                "default": None
            },
            {
                "name": 'perturbation_params',
                "type": 'dict',
                "description": "Dictionary with the following keys: - 'time': float, time at which perturbation is applied - 'metabolite': str, ID of the metabolite to perturb - 'factor': float, multiplication factor for the metabolite concentration",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'simulation_time',
                "type": 'float',
                "description": 'Total simulation time (default: 100)',
                "default": 100
            },
            {
                "name": 'time_points',
                "type": 'int',
                "description": 'Number of time points to simulate (default: 1000)',
                "default": 1000
            },
        ],
    },
    {
        "name": 'simulate_protein_signaling_network',
        "description": 'Simulate protein signaling network dynamics using ODE-based logic modeling with normalized Hill functions.',
        "required_parameters": [
            {
                "name": 'network_structure',
                "type": 'dict',
                "description": 'Dictionary defining the network topology. Each key is a target protein and its value is a list of tuples (regulator, regulation_type) where regulation_type is 1 for activation and -1 for inhibition.',
                "default": None
            },
            {
                "name": 'reaction_params',
                "type": 'dict',
                "description": "Dictionary of reaction parameters. Keys are tuples (regulator, target) and values are dictionaries with keys 'W' (weight), 'n' (Hill coefficient), and 'EC50' (half-maximal effective concentration).",
                "default": None
            },
            {
                "name": 'species_params',
                "type": 'dict',
                "description": "Dictionary of species parameters. Keys are protein names and values are dictionaries with keys 'tau' (time constant), 'y0' (initial concentration), and 'ymax' (maximum concentration).",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'simulation_time',
                "type": 'float',
                "description": 'Total simulation time in arbitrary time units. Default is 100.',
                "default": 100
            },
            {
                "name": 'time_points',
                "type": 'int',
                "description": 'Number of time points for the simulation. Default is 1000.',
                "default": 1000
            },
        ],
    },
    {
        "name": 'compare_protein_structures',
        "description": 'Compares two protein structures to identify structural differences and conformational changes.',
        "required_parameters": [
            {
                "name": 'pdb_file1',
                "type": 'str',
                "description": 'Path to the first PDB file',
                "default": None
            },
            {
                "name": 'pdb_file2',
                "type": 'str',
                "description": 'Path to the second PDB file',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'chain_id1',
                "type": 'str',
                "description": "Chain ID to analyze in the first structure (default: 'A')",
                "default": 'A'
            },
            {
                "name": 'chain_id2',
                "type": 'str',
                "description": "Chain ID to analyze in the second structure (default: 'A')",
                "default": 'A'
            },
            {
                "name": 'output_prefix',
                "type": 'str',
                "description": 'Prefix for output files (default: "protein_comparison")',
                "default": 'protein_comparison'
            },
        ],
    },
    {
        "name": 'simulate_renin_angiotensin_system_dynamics',
        "description": 'Simulate the time-dependent concentrations of renin-angiotensin system (RAS) components.',
        "required_parameters": [
            {
                "name": 'initial_concentrations',
                "type": 'dict',
                "description": "Initial concentrations of RAS components with keys: 'renin', 'angiotensinogen', 'angiotensin_I', 'angiotensin_II', 'ACE2_angiotensin_II', 'angiotensin_1_7'",
                "default": None
            },
            {
                "name": 'rate_constants',
                "type": 'dict',
                "description": "Kinetic rate constants with keys: 'k_ren' (renin production), 'k_agt' (angiotensinogen production), 'k_ace' (ACE conversion rate), 'k_ace2' (ACE2 conversion rate), 'k_at1r' (AT1R binding rate), 'k_mas' (Mas receptor binding rate)",
                "default": None
            },
            {
                "name": 'feedback_params',
                "type": 'dict',
                "description": "Parameters controlling feedback mechanisms with keys: 'fb_ang_II' (angiotensin II feedback), 'fb_ace2' (ACE2 feedback)",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'simulation_time',
                "type": 'float',
                "description": 'Total simulation time in hours (default: 48)',
                "default": 48
            },
            {
                "name": 'time_points',
                "type": 'int',
                "description": 'Number of time points to evaluate (default: 100)',
                "default": 100
            },
        ],
    },
    {
        "name": 'dimerization_odes',
        "description": 'Function dimerization_odes',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'y',
                "type": 'str',
                "description": 'Parameter y',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'mass_action_kinetics',
        "description": 'Function mass_action_kinetics',
        "required_parameters": [
            {
                "name": 'reaction',
                "type": 'str',
                "description": 'Parameter reaction',
                "default": None
            },
            {
                "name": 'concentrations',
                "type": 'str',
                "description": 'Parameter concentrations',
                "default": None
            },
            {
                "name": 'metabolite_ids',
                "type": 'str',
                "description": 'Parameter metabolite_ids',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'ode_system',
        "description": 'Function ode_system',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'concentrations',
                "type": 'str',
                "description": 'Parameter concentrations',
                "default": None
            },
            {
                "name": 'metabolite_ids',
                "type": 'str',
                "description": 'Parameter metabolite_ids',
                "default": None
            },
            {
                "name": 'reactions',
                "type": 'str',
                "description": 'Parameter reactions',
                "default": None
            },
            {
                "name": 'perturbation',
                "type": 'str',
                "description": 'Parameter perturbation',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'hill_function',
        "description": 'Function hill_function',
        "required_parameters": [
            {
                "name": 'x',
                "type": 'str',
                "description": 'Parameter x',
                "default": None
            },
            {
                "name": 'n',
                "type": 'str',
                "description": 'Parameter n',
                "default": None
            },
            {
                "name": 'ec50',
                "type": 'str',
                "description": 'Parameter ec50',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'ode_system',
        "description": 'Function ode_system',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'y',
                "type": 'str',
                "description": 'Parameter y',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'ras_ode_system',
        "description": 'Function ras_ode_system',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'y',
                "type": 'str',
                "description": 'Parameter y',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
