"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'quantify_cell_cycle_phases_from_microscopy',
        "description": 'Quantify the percentage of cells in each cell cycle phase using Calcofluor white stained microscopy images. This function processes microscopy images where cell walls/septa are stained with Calcofluor white, segments individual cells, extracts features, and classifies each cell into G1, S, or G2/M phase.',
        "required_parameters": [
            {
                "name": 'image_paths',
                "type": 'list of str',
                "description": 'List of file paths to microscopy images of cells stained with Calcofluor white',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": "Directory to save results (default: './results')",
                "default": './results'
            },
        ],
    },
    {
        "name": 'quantify_and_cluster_cell_motility',
        "description": 'Quantify cell motility features from time-lapse microscopy images and cluster cells based on motility patterns.',
        "required_parameters": [
            {
                "name": 'image_sequence_path',
                "type": 'str',
                "description": 'Path to directory containing time-lapse microscopy images in sequential order',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: "./results")',
                "default": './results'
            },
            {
                "name": 'num_clusters',
                "type": 'int',
                "description": 'Number of motility pattern clusters to identify (default: 3)',
                "default": 3
            },
        ],
    },
    {
        "name": 'perform_facs_cell_sorting',
        "description": 'Performs Fluorescence-Activated Cell Sorting (FACS) to enrich cell populations based on fluorescence characteristics.',
        "required_parameters": [
            {
                "name": 'cell_suspension_data',
                "type": 'str',
                "description": 'Path to the FCS file containing flow cytometry data',
                "default": None
            },
            {
                "name": 'fluorescence_parameter',
                "type": 'str',
                "description": "The fluorescence parameter to use for sorting (e.g., 'GFP', 'FITC', 'PE')",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'threshold_min',
                "type": 'float',
                "description": 'Minimum threshold for the fluorescence parameter. Cells below this value will be excluded',
                "default": None
            },
            {
                "name": 'threshold_max',
                "type": 'float',
                "description": 'Maximum threshold for the fluorescence parameter. Cells above this value will be excluded',
                "default": None
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Filename to save the sorted cell population data',
                "default": 'sorted_cells.csv'
            },
        ],
    },
    {
        "name": 'analyze_flow_cytometry_immunophenotyping',
        "description": 'Analyze flow cytometry data to identify and quantify specific cell populations based on surface markers.',
        "required_parameters": [
            {
                "name": 'fcs_file_path',
                "type": 'str',
                "description": 'Path to the FCS file containing flow cytometry data',
                "default": None
            },
            {
                "name": 'gating_strategy',
                "type": 'dict',
                "description": "Dictionary defining the gating strategy. Each key is a population name, and each value is a list of tuples (marker, operator, threshold). For example: {'HSCs': [('Lin', '<', 100), ('Sca1', '>', 1000), ...]}",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'compensation_matrix',
                "type": 'numpy.ndarray',
                "description": 'Spillover/compensation matrix to correct for fluorescence overlap',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save the results',
                "default": './results'
            },
        ],
    },
    {
        "name": 'analyze_mitochondrial_morphology_and_potential',
        "description": 'Quantifies metrics of mitochondrial morphology and membrane potential from fluorescence microscopy images.',
        "required_parameters": [
            {
                "name": 'morphology_image_path',
                "type": 'str',
                "description": 'Path to the fluorescence microscopy image showing mitochondrial morphology (e.g., MTS-GFP)',
                "default": None
            },
            {
                "name": 'potential_image_path',
                "type": 'str',
                "description": 'Path to the fluorescence microscopy image showing mitochondrial membrane potential (e.g., TMRE staining)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files, default is "./output"',
                "default": './output'
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
