"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'get_pylabrobot_documentation_liquid',
        "description": 'Get the documentation for a specific section of the PyLabRobot tutorial.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'get_pylabrobot_documentation_material',
        "description": 'Function get_pylabrobot_documentation_material',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'test_pylabrobot_script',
        "description": 'Test a PyLabRobot script using simulation and validation. Uses PyLabRobot\'s ChatterboxBackend and tracking systems to validate generated scripts without requiring physical hardware. Args: script_input (str): Either the PyLabRobot script code as a string, or a file path to a .py file enable_tracking (bool): Enable tip and volume tracking for error detection timeout_seconds (int): Maximum execution time before timeout save_test_report (bool): Whether to save detailed test results to file test_report_dir (str, optional): Directory to save test reports Returns: dict: Dictionary containing: - success (bool): Whether the script passed all tests - test_results (dict): Detailed test results for each validation step - execution_summary (dict): Summary of operations performed - errors (list): List of errors encountered - warnings (list): List of warnings - test_report_path (str): Path to saved report if requested Example: >>> # Test with script content string >>> script = "async def main(): ..." >>> result = test_pylabrobot_script(script) >>> # Test with file path >>> result = test_pylabrobot_script("/path/to/script.py") >>> if result["success"]: ...     print("Test passed!") ... else: ...     print(f"Test failed: {result[\'errors\']}")',
        "required_parameters": [
            {
                "name": 'script_input',
                "type": 'str',
                "description": 'Parameter script_input',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'enable_tracking',
                "type": 'bool',
                "description": 'Parameter enable_tracking',
                "default": False
            },
            {
                "name": 'timeout_seconds',
                "type": 'int',
                "description": 'Parameter timeout_seconds',
                "default": 60
            },
            {
                "name": 'save_test_report',
                "type": 'bool',
                "description": 'Parameter save_test_report',
                "default": False
            },
            {
                "name": 'test_report_dir',
                "type": 'str',
                "description": 'Parameter test_report_dir',
                "default": None
            },
        ],
    },
    {
        "name": 'pick_first',
        "description": 'Function pick_first',
        "required_parameters": [
            {
                "name": 'keywords',
                "type": 'str',
                "description": 'Parameter keywords',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'target',
        "description": 'Function target',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'run_async',
        "description": 'Function run_async',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
