"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'unsupervised_celltype_transfer_between_scRNA_datasets',
        "description": 'Function unsupervised_celltype_transfer_between_scRNA_datasets',
        "required_parameters": [
            {
                "name": 'path_to_annotated_h5ad',
                "type": 'str',
                "description": 'Parameter path_to_annotated_h5ad',
                "default": None
            },
            {
                "name": 'path_to_not_annotated_h5ad',
                "type": 'str',
                "description": 'Parameter path_to_not_annotated_h5ad',
                "default": None
            },
            {
                "name": 'ref_labels_key',
                "type": 'str',
                "description": 'Parameter ref_labels_key',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'query_batch_key',
                "type": 'str',
                "description": 'Parameter query_batch_key',
                "default": None
            },
            {
                "name": 'ref_batch_key',
                "type": 'str',
                "description": 'Parameter ref_batch_key',
                "default": None
            },
            {
                "name": 'CELLTYPIST',
                "type": 'bool',
                "description": 'Parameter CELLTYPIST',
                "default": False
            },
            {
                "name": 'KNN_BBKNN',
                "type": 'bool',
                "description": 'Parameter KNN_BBKNN',
                "default": False
            },
            {
                "name": 'KNN_HARMONY',
                "type": 'bool',
                "description": 'Parameter KNN_HARMONY',
                "default": False
            },
            {
                "name": 'KNN_SCANORAMA',
                "type": 'bool',
                "description": 'Parameter KNN_SCANORAMA',
                "default": False
            },
            {
                "name": 'KNN_SCVI',
                "type": 'bool',
                "description": 'Parameter KNN_SCVI',
                "default": False
            },
            {
                "name": 'ONCLASS',
                "type": 'bool',
                "description": 'Parameter ONCLASS',
                "default": False
            },
            {
                "name": 'Random_Forest',
                "type": 'bool',
                "description": 'Parameter Random_Forest',
                "default": False
            },
            {
                "name": 'SCANVI_POPV',
                "type": 'bool',
                "description": 'Parameter SCANVI_POPV',
                "default": True
            },
            {
                "name": 'Support_Vector',
                "type": 'bool',
                "description": 'Parameter Support_Vector',
                "default": False
            },
            {
                "name": 'XGboost',
                "type": 'bool',
                "description": 'Parameter XGboost',
                "default": False
            },
            {
                "name": 'n_jobs',
                "type": 'int',
                "description": 'Parameter n_jobs',
                "default": 1
            },
            {
                "name": 'output_folder',
                "type": 'str',
                "description": 'Parameter output_folder',
                "default": './tmp/'
            },
            {
                "name": 'n_samples_per_label',
                "type": 'int',
                "description": 'Parameter n_samples_per_label',
                "default": 10
            },
        ],
    },
    {
        "name": 'interspecies_gene_conversion',
        "description": 'Convert ENSEMBL gene IDs between different species using BioMart homology mapping. This function converts a list of ENSEMBL gene IDs from one species to their homologous counterparts in another species using the Ensembl BioMart database. The conversion is based on one-to-one ortholog mappings between species.',
        "required_parameters": [
            {
                "name": 'gene_list',
                "type": 'list[str]',
                "description": "List of ENSEMBL gene IDs to convert (e.g., ['ENSG00000007372', 'ENSG00000181449'])",
                "default": None
            },
            {
                "name": 'source_species',
                "type": 'str',
                "description": 'Source species name. Supported species: human, mouse, rat, zebrafish, fly, drosophila, worm, yeast, chicken, pig, cow, dog, macaque',
                "default": None
            },
            {
                "name": 'target_species',
                "type": 'str',
                "description": 'Target species name. Same supported species as source_species.',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'generate_gene_embeddings_with_ESM_models',
        "description": 'Generate average protein embeddings for a list of Ensembl gene IDs. Memory-friendly implementation with rolling averages and small batch processing. Embeddings are automatically saved to disk with a default filename if no save_path is provided. Args: ensembl_gene_ids: List of Ensembl gene IDs (e.g., ["ENSG00000012048", ...]) model_name: ESM model name to use (default: "esm2_t6_8M_UR50D") layer: Which layer to extract embeddings from (default: 6) save_path: Optional path to save embeddings as PyTorch dict. If None, uses default filename format: "esm_embeddings_{model_name}_{gene_list}.pt" (default: None) batch_size: Number of sequences to process at once (default: 1) max_sequence_length: Maximum sequence length to process (default: 1024) Returns: String containing the steps performed during the embedding generation process',
        "required_parameters": [
            {
                "name": 'ensembl_gene_ids',
                "type": 'str',
                "description": 'Parameter ensembl_gene_ids',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'model_name',
                "type": 'str',
                "description": 'Parameter model_name',
                "default": 'esm2_t6_8M_UR50D'
            },
            {
                "name": 'layer',
                "type": 'int',
                "description": 'Parameter layer',
                "default": 6
            },
            {
                "name": 'save_path',
                "type": 'str',
                "description": 'Parameter save_path',
                "default": None
            },
            {
                "name": 'batch_size',
                "type": 'int',
                "description": 'Parameter batch_size',
                "default": 1
            },
            {
                "name": 'max_sequence_length',
                "type": 'int',
                "description": 'Parameter max_sequence_length',
                "default": 1024
            },
        ],
    },
    {
        "name": 'annotate_celltype_scRNA',
        "description": 'Annotate cell types based on gene markers and transferred labels using LLM. After leiden clustering, annotate clusters using differentially expressed genes and optionally incorporate transferred labels from reference datasets.',
        "required_parameters": [
            {
                "name": 'adata_filename',
                "type": 'str',
                "description": 'Parameter adata_filename',
                "default": None
            },
            {
                "name": 'data_dir',
                "type": 'str',
                "description": 'Parameter data_dir',
                "default": None
            },
            {
                "name": 'data_info',
                "type": 'str',
                "description": 'Parameter data_info',
                "default": None
            },
            {
                "name": 'data_lake_path',
                "type": 'str',
                "description": 'Parameter data_lake_path',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'cluster',
                "type": 'str',
                "description": 'Parameter cluster',
                "default": 'leiden'
            },
            {
                "name": 'llm',
                "type": 'str',
                "description": 'Parameter llm',
                "default": 'claude-3-5-sonnet-20241022'
            },
            {
                "name": 'composition',
                "type": 'str',
                "description": 'Parameter composition',
                "default": None
            },
        ],
    },
    {
        "name": 'annotate_celltype_with_panhumanpy',
        "description": 'Perform hierarchical cell type annotation using panhumanpy and Azimuth Neural Network. This function implements the panhumanpy workflow for cell type annotation using the Azimuth Neural Network, providing hierarchical cell type labels with confidence scores.',
        "required_parameters": [
            {
                "name": 'adata_path',
                "type": 'str',
                "description": 'Path to the AnnData file containing scRNA-seq data',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'feature_names_col',
                "type": 'str',
                "description": 'Column name in adata.var containing gene names (default: None, uses index)',
                "default": None
            },
            {
                "name": 'refine',
                "type": 'bool',
                "description": 'Whether to perform label refinement for consistent granularity (default: True)',
                "default": True
            },
            {
                "name": 'umap',
                "type": 'bool',
                "description": 'Whether to generate ANN embeddings and UMAP (default: True)',
                "default": True
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save results (default: "./output")',
                "default": './output'
            },
        ],
    },
    {
        "name": 'create_scvi_embeddings_scRNA',
        "description": 'Function create_scvi_embeddings_scRNA',
        "required_parameters": [
            {
                "name": 'adata_filename',
                "type": 'str',
                "description": 'Parameter adata_filename',
                "default": None
            },
            {
                "name": 'batch_key',
                "type": 'str',
                "description": 'Parameter batch_key',
                "default": None
            },
            {
                "name": 'label_key',
                "type": 'str',
                "description": 'Parameter label_key',
                "default": None
            },
            {
                "name": 'data_dir',
                "type": 'str',
                "description": 'Parameter data_dir',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'create_harmony_embeddings_scRNA',
        "description": 'Function create_harmony_embeddings_scRNA',
        "required_parameters": [
            {
                "name": 'adata_filename',
                "type": 'str',
                "description": 'Parameter adata_filename',
                "default": None
            },
            {
                "name": 'batch_key',
                "type": 'str',
                "description": 'Parameter batch_key',
                "default": None
            },
            {
                "name": 'data_dir',
                "type": 'str',
                "description": 'Parameter data_dir',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'get_uce_embeddings_scRNA',
        "description": 'The UCE embeddings are usually our default tools to get cell embeddings, we map UCE embeddings to IMA referece dataset and get the cell types for a better understanding. The custom_args is a list of strings that will be passed as command line arguments to the UCE script, like ["--adata_path", adata_file, "--dir", output_dir]. The default value is None.',
        "required_parameters": [
            {
                "name": 'adata_filename',
                "type": 'str',
                "description": 'Parameter adata_filename',
                "default": None
            },
            {
                "name": 'data_dir',
                "type": 'str',
                "description": 'Parameter data_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'DATA_ROOT',
                "type": 'str',
                "description": 'Parameter DATA_ROOT',
                "default": '/dfs/project/bioagentos/data/singlecell/'
            },
            {
                "name": 'custom_args',
                "type": 'str',
                "description": 'Parameter custom_args',
                "default": None
            },
        ],
    },
    {
        "name": 'map_to_ima_interpret_scRNA',
        "description": 'Map cell embeddings from the input dataset to the Integrated Megascale Atlas reference dataset using UCE embeddings.',
        "required_parameters": [
            {
                "name": 'adata_filename',
                "type": 'str',
                "description": 'Parameter adata_filename',
                "default": None
            },
            {
                "name": 'data_dir',
                "type": 'str',
                "description": 'Parameter data_dir',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'custom_args',
                "type": 'str',
                "description": 'Parameter custom_args',
                "default": None
            },
        ],
    },
    {
        "name": 'get_rna_seq_archs4',
        "description": 'Given a gene name, this function returns the steps it performs and the max K transcripts-per-million (TPM) per tissue from the RNA-seq expression.',
        "required_parameters": [
            {
                "name": 'gene_name',
                "type": 'str',
                "description": 'Parameter gene_name',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'K',
                "type": 'int',
                "description": 'Parameter K',
                "default": 10
            },
        ],
    },
    {
        "name": 'get_gene_set_enrichment_analysis_supported_database_list',
        "description": 'Function get_gene_set_enrichment_analysis_supported_database_list',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'gene_set_enrichment_analysis',
        "description": 'Perform enrichment analysis for a list of genes, with optional background gene set and plotting functionality.',
        "required_parameters": [
            {
                "name": 'genes',
                "type": 'str',
                "description": 'Parameter genes',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'top_k',
                "type": 'int',
                "description": 'Parameter top_k',
                "default": 10
            },
            {
                "name": 'database',
                "type": 'str',
                "description": 'Parameter database',
                "default": 'ontology'
            },
            {
                "name": 'background_list',
                "type": 'str',
                "description": 'Parameter background_list',
                "default": None
            },
            {
                "name": 'plot',
                "type": 'bool',
                "description": 'Parameter plot',
                "default": False
            },
        ],
    },
    {
        "name": 'analyze_chromatin_interactions',
        "description": 'Analyze chromatin interactions from Hi-C data to identify enhancer-promoter interactions and TADs.',
        "required_parameters": [
            {
                "name": 'hic_file_path',
                "type": 'str',
                "description": 'Path to the Hi-C data file (.cool or .hic format)',
                "default": None
            },
            {
                "name": 'regulatory_elements_bed',
                "type": 'str',
                "description": 'Path to BED file containing genomic coordinates of regulatory elements (enhancers, promoters, CTCF sites, etc.)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: "./output")',
                "default": './output'
            },
        ],
    },
    {
        "name": 'analyze_comparative_genomics_and_haplotypes',
        "description": 'Perform comparative genomics and haplotype analysis on multiple genome samples. This function aligns multiple genome samples to a reference, identifies variants, analyzes shared and unique genomic regions, and determines haplotype structure.',
        "required_parameters": [
            {
                "name": 'sample_fasta_files',
                "type": 'list of str',
                "description": 'Paths to FASTA files containing whole-genome sequences to be analyzed',
                "default": None
            },
            {
                "name": 'reference_genome_path',
                "type": 'str',
                "description": 'Path to the reference genome FASTA file',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to store output files (default: "./output")',
                "default": './output'
            },
        ],
    },
    {
        "name": 'perform_chipseq_peak_calling_with_macs2',
        "description": 'Perform ChIP-seq peak calling using MACS2 to identify genomic regions with significant binding.',
        "required_parameters": [
            {
                "name": 'chip_seq_file',
                "type": 'str',
                "description": 'Path to the ChIP-seq read data file (BAM, BED, or other supported format)',
                "default": None
            },
            {
                "name": 'control_file',
                "type": 'str',
                "description": 'Path to the control/input data file (BAM, BED, or other supported format)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_name',
                "type": 'str',
                "description": 'Prefix for output files (default: "macs2_output")',
                "default": 'macs2_output'
            },
            {
                "name": 'genome_size',
                "type": 'str',
                "description": 'Effective genome size shorthand: \'hs\' for human, \'mm\' for mouse, etc. (default: "hs")',
                "default": 'hs'
            },
            {
                "name": 'q_value',
                "type": 'float',
                "description": 'q-value (minimum FDR) cutoff for peak calling (default: 0.05)',
                "default": 0.05
            },
        ],
    },
    {
        "name": 'find_enriched_motifs_with_homer',
        "description": 'Find DNA sequence motifs enriched in genomic regions using the HOMER motif discovery software.',
        "required_parameters": [
            {
                "name": 'peak_file',
                "type": 'str',
                "description": 'Path to peak file in BED format containing genomic regions to analyze for motif enrichment',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'genome',
                "type": 'str',
                "description": 'Reference genome for sequence extraction (default: "hg38")',
                "default": 'hg38'
            },
            {
                "name": 'background_file',
                "type": 'str',
                "description": 'Path to BED file with background regions for comparison. If None, HOMER will generate random background sequences automatically (default: None)',
                "default": None
            },
            {
                "name": 'motif_length',
                "type": 'str',
                "description": 'Comma-separated list of motif lengths to discover (default: "8,10,12")',
                "default": '8,10,12'
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: "./homer_motifs")',
                "default": './homer_motifs'
            },
            {
                "name": 'num_motifs',
                "type": 'int',
                "description": 'Number of motifs to find (default: 10)',
                "default": 10
            },
            {
                "name": 'threads',
                "type": 'int',
                "description": 'Number of CPU threads to use (default: 4)',
                "default": 4
            },
        ],
    },
    {
        "name": 'analyze_genomic_region_overlap',
        "description": 'Analyze overlaps between two or more sets of genomic regions.',
        "required_parameters": [
            {
                "name": 'region_sets',
                "type": 'list',
                "description": 'List of genomic region sets. Each item can be either: - A string path to a BED file - A list of tuples/lists with format (chrom, start, end) or (chrom, start, end, name)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_prefix',
                "type": 'str',
                "description": 'Prefix for output files (default: "overlap_analysis")',
                "default": 'overlap_analysis'
            },
        ],
    },
    {
        "name": 'generate_embeddings_with_state',
        "description": 'Generate State embeddings for single-cell RNA-seq data using the SE-600M model. This function downloads the SE-600M model from Hugging Face, installs required dependencies, and generates embeddings for the input AnnData object.',
        "required_parameters": [
            {
                "name": 'adata_filename',
                "type": 'str',
                "description": 'Name of the input AnnData file (.h5ad format)',
                "default": None
            },
            {
                "name": 'data_dir',
                "type": 'str',
                "description": 'Directory containing the input data file',
                "default": None
            },
            {
                "name": 'model_folder',
                "type": 'str',
                "description": 'Directory where the SE-600M model will be downloaded and stored',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_filename',
                "type": 'str',
                "description": "Name of the output file. If None, will use input filename with '_state_embeddings' suffix",
                "default": None
            },
            {
                "name": 'checkpoint',
                "type": 'str',
                "description": 'Path to the specific model checkpoint. If None, uses the latest checkpoint in model_folder',
                "default": None
            },
            {
                "name": 'embed_key',
                "type": 'str',
                "description": 'Name of key to store embeddings in the output AnnData object',
                "default": 'X_state'
            },
            {
                "name": 'protein_embeddings',
                "type": 'str',
                "description": 'Path to protein embeddings override (.pt). If omitted, auto-detects in model folder',
                "default": None
            },
            {
                "name": 'batch_size',
                "type": 'int',
                "description": 'Batch size for embedding forward pass. Increase to use more VRAM and speed up embedding',
                "default": 500
            },
        ],
    },
    {
        "name": 'generate_transcriptformer_embeddings',
        "description": 'Generate Transcriptformer embeddings for single-cell RNA-seq data.',
        "required_parameters": [
            {
                "name": 'adata_filename',
                "type": 'str',
                "description": 'Name of the input AnnData file (.h5ad format)',
                "default": None
            },
            {
                "name": 'data_dir',
                "type": 'str',
                "description": 'Directory containing the input data file',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_filename',
                "type": 'str',
                "description": "Name of the output embeddings file. If None, will use input filename with '_transcriptformer_embeddings' suffix",
                "default": None
            },
            {
                "name": 'model_type',
                "type": 'str',
                "description": 'Type of transcriptformer model to download and use. Options: "tf-sapiens", "tf-exemplar", "tf-metazoa" (default: "tf-sapiens")',
                "default": 'tf-sapiens'
            },
            {
                "name": 'checkpoint_path',
                "type": 'str',
                "description": 'Path to the transcriptformer checkpoint directory. If None, will use "./checkpoints/{model_type}" (default: None)',
                "default": None
            },
            {
                "name": 'batch_size',
                "type": 'int',
                "description": 'Batch size for inference (default: 8)',
                "default": 8
            },
            {
                "name": 'precision',
                "type": 'str',
                "description": 'Precision for inference. Options: "16-mixed", "32" (default: "16-mixed")',
                "default": '16-mixed'
            },
            {
                "name": 'clip_counts',
                "type": 'int',
                "description": 'Maximum count value to clip to (default: 30)',
                "default": 30
            },
            {
                "name": 'embedding_layer_index',
                "type": 'int',
                "description": 'Which layer to extract embeddings from (default: -1, last layer)',
                "default": -1
            },
            {
                "name": 'num_gpus',
                "type": 'int',
                "description": 'Number of GPUs to use (default: 1)',
                "default": 1
            },
            {
                "name": 'n_data_workers',
                "type": 'int',
                "description": 'Number of data loading workers (default: 0)',
                "default": 0
            },
            {
                "name": 'gene_col_name',
                "type": 'str',
                "description": 'Column name in AnnData.var containing gene identifiers (default: "ensembl_id")',
                "default": 'ensembl_id'
            },
            {
                "name": 'pretrained_embedding',
                "type": 'str',
                "description": 'Path to pretrained embeddings for out-of-distribution species (default: None)',
                "default": None
            },
            {
                "name": 'filter_to_vocabs',
                "type": 'bool',
                "description": 'Whether to filter genes to only those in the vocabulary (default: True)',
                "default": True
            },
            {
                "name": 'use_raw',
                "type": 'str',
                "description": 'Whether to use raw counts from AnnData.raw.X (True), adata.X (False), or auto-detect (None/auto) (default: "None")',
                "default": 'None'
            },
            {
                "name": 'emb_type',
                "type": 'str',
                "description": 'Type of embeddings to extract: \'cell\' for mean-pooled cell embeddings or \'cge\' for contextual gene embeddings (default: "cell")',
                "default": 'cell'
            },
            {
                "name": 'remove_duplicate_genes',
                "type": 'bool',
                "description": 'Remove duplicate genes if found instead of raising an error (default: False)',
                "default": False
            },
            {
                "name": 'oom_dataloader',
                "type": 'bool',
                "description": 'Use map-style out-of-memory DataLoader (DistributedSampler-friendly) (default: False)',
                "default": False
            },
        ],
    },
    {
        "name": 'conda_env_exists',
        "description": 'Function conda_env_exists',
        "required_parameters": [
            {
                "name": 'env_name',
                "type": 'str',
                "description": 'Parameter env_name',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'create_panhumanpy_env',
        "description": 'Function create_panhumanpy_env',
        "required_parameters": [
            {
                "name": 'env_name',
                "type": 'str',
                "description": 'Parameter env_name',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'custom_mode',
        "description": 'Function custom_mode',
        "required_parameters": [
            {
                "name": 'x',
                "type": 'str',
                "description": 'Parameter x',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'get_matrix',
        "description": 'Function get_matrix',
        "required_parameters": [
            {
                "name": 'chrom',
                "type": 'str',
                "description": 'Parameter chrom',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'balance_if_possible',
                "type": 'bool',
                "description": 'Parameter balance_if_possible',
                "default": True
            },
        ],
    },
    {
        "name": 'is_model_downloaded',
        "description": 'Check if model is already downloaded by looking for key files',
        "required_parameters": [
            {
                "name": 'checkpoint_path',
                "type": 'str',
                "description": 'Parameter checkpoint_path',
                "default": None
            },
            {
                "name": 'model_type',
                "type": 'str',
                "description": 'Parameter model_type',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'check_ensembl_patterns',
        "description": 'Function check_ensembl_patterns',
        "required_parameters": [
            {
                "name": 'gene_index',
                "type": 'str',
                "description": 'Parameter gene_index',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
