"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'analyze_circular_dichroism_spectra',
        "description": 'Analyzes circular dichroism (CD) spectroscopy data to determine secondary structure and thermal stability.',
        "required_parameters": [
            {
                "name": 'sample_name',
                "type": 'str',
                "description": 'Name of the biomolecule sample (e.g., "Znf706", "G-quadruplex")',
                "default": None
            },
            {
                "name": 'sample_type',
                "type": 'str',
                "description": 'Type of biomolecule ("protein" or "nucleic_acid")',
                "default": None
            },
            {
                "name": 'wavelength_data',
                "type": 'list or numpy.ndarray',
                "description": 'Wavelength values in nm for CD spectrum',
                "default": None
            },
            {
                "name": 'cd_signal_data',
                "type": 'list or numpy.ndarray',
                "description": 'CD signal intensity values (typically in mdeg or Δε)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'temperature_data',
                "type": 'list or numpy.ndarray',
                "description": 'Temperature values (°C) for thermal denaturation experiment',
                "default": None
            },
            {
                "name": 'thermal_cd_data',
                "type": 'list or numpy.ndarray',
                "description": 'CD signal values at specific wavelength across different temperatures',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save result files, defaults to current directory',
                "default": './'
            },
        ],
    },
    {
        "name": 'analyze_rna_secondary_structure_features',
        "description": 'Calculate numeric values for various structural features of an RNA secondary structure.',
        "required_parameters": [
            {
                "name": 'dot_bracket_structure',
                "type": 'str',
                "description": 'RNA secondary structure in dot-bracket notation (e.g., "(((...)))"). Parentheses represent base pairs, dots represent unpaired bases.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'sequence',
                "type": 'str',
                "description": 'The RNA sequence corresponding to the structure. If provided, sequence-dependent energy calculations will be performed.',
                "default": None
            },
        ],
    },
    {
        "name": 'analyze_protease_kinetics',
        "description": 'Analyze protease kinetics data from fluorogenic peptide cleavage assays. This function processes time-course fluorescence data from protease-mediated peptide cleavage assays, fits the data to Michaelis-Menten kinetics, and determines key kinetic parameters (kcat, KM, and catalytic efficiency).',
        "required_parameters": [
            {
                "name": 'time_points',
                "type": 'numpy.ndarray',
                "description": 'Array of time points (in seconds) at which measurements were taken',
                "default": None
            },
            {
                "name": 'fluorescence_data',
                "type": 'numpy.ndarray',
                "description": '2D array of fluorescence measurements where each row corresponds to a different substrate concentration and each column corresponds to a time point',
                "default": None
            },
            {
                "name": 'substrate_concentrations',
                "type": 'numpy.ndarray',
                "description": 'Array of substrate concentrations (in μM) corresponding to each row in fluorescence_data',
                "default": None
            },
            {
                "name": 'enzyme_concentration',
                "type": 'float',
                "description": 'Concentration of the protease enzyme (in μM)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_prefix',
                "type": 'str',
                "description": 'Prefix for output files (default: "protease_kinetics")',
                "default": 'protease_kinetics'
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: "./")',
                "default": './'
            },
        ],
    },
    {
        "name": 'analyze_enzyme_kinetics_assay',
        "description": 'Performs in vitro enzyme kinetics assay and analyzes the dose-dependent effects of modulators.',
        "required_parameters": [
            {
                "name": 'enzyme_name',
                "type": 'str',
                "description": 'Name of the purified enzyme being tested',
                "default": None
            },
            {
                "name": 'substrate_concentrations',
                "type": 'list or numpy.ndarray',
                "description": 'List of substrate concentrations in μM for kinetic analysis',
                "default": None
            },
            {
                "name": 'enzyme_concentration',
                "type": 'float',
                "description": 'Concentration of the enzyme in nM',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'modulators',
                "type": 'dict',
                "description": 'Dictionary of modulators where keys are modulator names and values are lists of concentrations in μM. Default is None (no modulators).',
                "default": None
            },
            {
                "name": 'time_points',
                "type": 'list or numpy.ndarray',
                "description": 'Time points in minutes for time-course measurements. Default is None, which uses [0, 5, 10, 15, 20, 30, 45, 60].',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files. Default is current directory.',
                "default": './'
            },
        ],
    },
    {
        "name": 'analyze_itc_binding_thermodynamics',
        "description": 'Analyzes isothermal titration calorimetry (ITC) data to determine binding affinity and thermodynamic parameters.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'itc_data_path',
                "type": 'str',
                "description": "Path to CSV or TSV file containing ITC thermogram data with columns for injection number, injection volume, and heat released/absorbed. Expected columns: 'injection', 'volume', 'heat'",
                "default": None
            },
            {
                "name": 'itc_data',
                "type": 'numpy.ndarray',
                "description": 'Raw ITC thermogram data as a numpy array. Expected shape: (n_injections, 3) with columns for injection number, injection volume, and heat This parameter is provided for backward compatibility and will be deprecated.',
                "default": None
            },
            {
                "name": 'temperature',
                "type": 'float',
                "description": 'Temperature in Kelvin at which the experiment was conducted. Default is 298.15 K (25°C).',
                "default": 298.15
            },
            {
                "name": 'protein_concentration',
                "type": 'float',
                "description": 'Initial concentration of protein in the cell in molar (M). Required for accurate fitting.',
                "default": None
            },
            {
                "name": 'ligand_concentration',
                "type": 'float',
                "description": 'Concentration of ligand in the syringe in molar (M). Required for accurate fitting.',
                "default": None
            },
        ],
    },
    {
        "name": 'analyze_protein_conservation',
        "description": 'Perform multiple sequence alignment and phylogenetic analysis to identify conserved protein regions.',
        "required_parameters": [
            {
                "name": 'protein_sequences',
                "type": 'list of str',
                "description": 'List of protein sequences in FASTA format from multiple organisms.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: "./output")',
                "default": './'
            },
        ],
    },
    {
        "name": 'michaelis_menten',
        "description": 'Function michaelis_menten',
        "required_parameters": [
            {
                "name": 's',
                "type": 'str',
                "description": 'Parameter s',
                "default": None
            },
            {
                "name": 'vmax',
                "type": 'str',
                "description": 'Parameter vmax',
                "default": None
            },
            {
                "name": 'km',
                "type": 'str',
                "description": 'Parameter km',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'michaelis_menten',
        "description": 'Function michaelis_menten',
        "required_parameters": [
            {
                "name": 's',
                "type": 'str',
                "description": 'Parameter s',
                "default": None
            },
            {
                "name": 'vmax',
                "type": 'str',
                "description": 'Parameter vmax',
                "default": None
            },
            {
                "name": 'km',
                "type": 'str',
                "description": 'Parameter km',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'one_site_model',
        "description": 'One-site binding model for ITC data.',
        "required_parameters": [
            {
                "name": 'x',
                "type": 'Molar ratio [ligand]/[protein]',
                "description": '',
                "default": None
            },
            {
                "name": 'Kd',
                "type": 'Dissociation constant (M)',
                "description": '',
                "default": None
            },
            {
                "name": 'dH',
                "type": 'Enthalpy change (cal/mol)',
                "description": '',
                "default": None
            },
            {
                "name": 'n',
                "type": 'Stoichiometry',
                "description": '',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'dose_response',
        "description": 'Function dose_response',
        "required_parameters": [
            {
                "name": 'x',
                "type": 'str',
                "description": 'Parameter x',
                "default": None
            },
            {
                "name": 'ic50',
                "type": 'str',
                "description": 'Parameter ic50',
                "default": None
            },
            {
                "name": 'hill',
                "type": 'str',
                "description": 'Parameter hill',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
