"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'reconstruct_3d_face_from_mri',
        "description": 'Generate a 3D model of facial anatomy from MRI scans of the head and neck.',
        "required_parameters": [
            {
                "name": 'mri_file_path',
                "type": 'str',
                "description": 'Path to the MRI scan file (NIfTI format: .nii or .nii.gz)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where output files will be saved',
                "default": './output'
            },
            {
                "name": 'subject_id',
                "type": 'str',
                "description": 'Identifier for the subject, used in output filenames',
                "default": 'subject'
            },
            {
                "name": 'threshold_value',
                "type": 'int',
                "description": 'Threshold value for initial segmentation of facial tissues',
                "default": 300
            },
        ],
    },
    {
        "name": 'analyze_abr_waveform_p1_metrics',
        "description": 'Extracts P1 amplitude and latency from Auditory Brainstem Response (ABR) waveform data. P1 (Wave I) is typically the first positive peak in the ABR waveform and is a critical marker for auditory function assessment.',
        "required_parameters": [
            {
                "name": 'time_ms',
                "type": 'array-like',
                "description": 'Time points of the ABR recording in milliseconds',
                "default": None
            },
            {
                "name": 'amplitude_uv',
                "type": 'array-like',
                "description": 'Amplitude values of the ABR recording in microvolts',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'analyze_ciliary_beat_frequency',
        "description": 'Analyze ciliary beat frequency from high-speed video microscopy data using FFT analysis.',
        "required_parameters": [
            {
                "name": 'video_path',
                "type": 'str',
                "description": 'Path to the high-speed video microscopy file of ciliary beating',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'roi_count',
                "type": 'int',
                "description": 'Number of regions of interest to analyze (default: 5)',
                "default": 5
            },
            {
                "name": 'min_freq',
                "type": 'float',
                "description": 'Minimum frequency to consider in Hz (default: 0)',
                "default": 0
            },
            {
                "name": 'max_freq',
                "type": 'float',
                "description": 'Maximum frequency to consider in Hz (default: 30)',
                "default": 30
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: current directory)',
                "default": './'
            },
        ],
    },
    {
        "name": 'analyze_protein_colocalization',
        "description": 'Analyze colocalization between two fluorescently labeled proteins in microscopy images.',
        "required_parameters": [
            {
                "name": 'channel1_path',
                "type": 'str',
                "description": 'Path to the first channel image file (fluorescent protein 1)',
                "default": None
            },
            {
                "name": 'channel2_path',
                "type": 'str',
                "description": 'Path to the second channel image file (fluorescent protein 2)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: "./output")',
                "default": './output'
            },
            {
                "name": 'threshold_method',
                "type": 'str',
                "description": 'Method for thresholding images (\'otsu\', \'li\', or \'yen\') (default: "otsu")',
                "default": 'otsu'
            },
        ],
    },
    {
        "name": 'perform_cosinor_analysis',
        "description": 'Performs cosinor analysis on physiological time series data to characterize circadian rhythms.',
        "required_parameters": [
            {
                "name": 'time_data',
                "type": 'array-like',
                "description": 'Time points of the measurements in hours',
                "default": None
            },
            {
                "name": 'physiological_data',
                "type": 'array-like',
                "description": 'Physiological measurements corresponding to each time point',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'period',
                "type": 'float',
                "description": 'Period of the rhythm in hours, default is 24 hours for circadian rhythms',
                "default": 24.0
            },
        ],
    },
    {
        "name": 'calculate_brain_adc_map',
        "description": 'Calculate Apparent Diffusion Coefficient (ADC) map from diffusion-weighted MRI data. This function fits the DW-MRI data to the monoexponential diffusion model: S = S0 * exp(-b * ADC), where S is the signal intensity, S0 is the signal without diffusion weighting, b is the b-value, and ADC is the apparent diffusion coefficient.',
        "required_parameters": [
            {
                "name": 'dwi_file_path',
                "type": 'str',
                "description": 'Path to the 4D NIfTI file containing diffusion-weighted MRI data, where the 4th dimension corresponds to different b-values.',
                "default": None
            },
            {
                "name": 'b_values',
                "type": 'list or numpy.ndarray',
                "description": 'List of b-values corresponding to each volume in the 4D DWI data.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_path',
                "type": 'str',
                "description": 'Path where the output ADC map will be saved (default: "adc_map.nii.gz").',
                "default": 'adc_map.nii.gz'
            },
            {
                "name": 'mask_file_path',
                "type": 'str',
                "description": 'Path to a binary mask file to limit ADC calculation to brain regions (default: None).',
                "default": None
            },
        ],
    },
    {
        "name": 'analyze_endolysosomal_calcium_dynamics',
        "description": 'Analyze calcium dynamics in endo-lysosomal compartments using ELGA/ELGA1 probe data.',
        "required_parameters": [
            {
                "name": 'time_points',
                "type": 'numpy.ndarray or list',
                "description": 'Time points of the measurements in seconds',
                "default": None
            },
            {
                "name": 'luminescence_values',
                "type": 'numpy.ndarray or list',
                "description": 'Luminescence intensity values from ELGA/ELGA1 probes corresponding to Ca2+ levels',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'treatment_time',
                "type": 'float',
                "description": 'Time point (in seconds) when treatment/stimulus was applied',
                "default": None
            },
            {
                "name": 'cell_type',
                "type": 'str',
                "description": 'Type of cells used in the experiment',
                "default": ''
            },
            {
                "name": 'treatment_name',
                "type": 'str',
                "description": 'Name of the treatment or stimulus applied',
                "default": ''
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Name of the file to save detailed analysis results',
                "default": 'calcium_analysis_results.txt'
            },
        ],
    },
    {
        "name": 'analyze_fatty_acid_composition_by_gc',
        "description": 'Analyzes fatty acid composition in tissue samples using gas chromatography data.',
        "required_parameters": [
            {
                "name": 'gc_data_file',
                "type": 'str',
                "description": "Path to the CSV file containing gas chromatography data with columns 'retention_time' and 'peak_area'.",
                "default": None
            },
            {
                "name": 'tissue_type',
                "type": 'str',
                "description": 'Type of tissue sample (e.g., liver, kidney, heart, muscle, adipose).',
                "default": None
            },
            {
                "name": 'sample_id',
                "type": 'str',
                "description": 'Identifier for the sample being analyzed.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_directory',
                "type": 'str',
                "description": 'Directory where result files will be saved (default: "./results").',
                "default": './results'
            },
        ],
    },
    {
        "name": 'analyze_hemodynamic_data',
        "description": 'Analyzes raw blood pressure data to calculate key hemodynamic parameters.',
        "required_parameters": [
            {
                "name": 'pressure_data',
                "type": 'numpy.ndarray',
                "description": 'Raw blood pressure measurements in mmHg',
                "default": None
            },
            {
                "name": 'sampling_rate',
                "type": 'float',
                "description": 'Data acquisition rate in Hz (samples per second)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Filename to save the calculated parameters, default is "hemodynamic_results.csv"',
                "default": 'hemodynamic_results.csv'
            },
        ],
    },
    {
        "name": 'simulate_thyroid_hormone_pharmacokinetics',
        "description": 'Simulates the transport and binding of thyroid hormones across different tissue compartments using an ODE-based pharmacokinetic model.',
        "required_parameters": [
            {
                "name": 'parameters',
                "type": 'dict',
                "description": 'Dictionary containing model parameters: - transport_rates : dict of rate constants for hormone transport between compartments - binding_constants : dict of association/dissociation constants for hormone-protein binding - metabolism_rates : dict of rate constants for hormone metabolism in different tissues - volumes : dict of compartment volumes',
                "default": None
            },
            {
                "name": 'initial_conditions',
                "type": 'dict',
                "description": 'Dictionary of initial concentrations for all molecular species in each compartment',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'time_span',
                "type": 'tuple',
                "description": 'Start and end time for simulation in hours (default: (0, 24))',
                "default": (0, 24)
            },
            {
                "name": 'time_points',
                "type": 'int',
                "description": 'Number of time points to output (default: 100)',
                "default": 100
            },
        ],
    },
    {
        "name": 'quantify_amyloid_beta_plaques',
        "description": 'Function quantify_amyloid_beta_plaques',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Parameter image_path',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Parameter output_dir',
                "default": './results'
            },
            {
                "name": 'threshold_method',
                "type": 'str',
                "description": 'Parameter threshold_method',
                "default": 'otsu'
            },
            {
                "name": 'min_plaque_size',
                "type": 'int',
                "description": 'Parameter min_plaque_size',
                "default": 50
            },
            {
                "name": 'manual_threshold',
                "type": 'int',
                "description": 'Parameter manual_threshold',
                "default": 127
            },
        ],
    },
    {
        "name": 'cosinor_model',
        "description": 'Cosine function with baseline (mesor), amplitude, and phase shift.',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'mesor',
                "type": 'str',
                "description": 'Parameter mesor',
                "default": None
            },
            {
                "name": 'amplitude',
                "type": 'str',
                "description": 'Parameter amplitude',
                "default": None
            },
            {
                "name": 'acrophase',
                "type": 'str',
                "description": 'Parameter acrophase',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'mono_exp_model',
        "description": 'Function mono_exp_model',
        "required_parameters": [
            {
                "name": 'b',
                "type": 'str',
                "description": 'Parameter b',
                "default": None
            },
            {
                "name": 'S0',
                "type": 'str',
                "description": 'Parameter S0',
                "default": None
            },
            {
                "name": 'ADC',
                "type": 'str',
                "description": 'Parameter ADC',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'pk_ode_system',
        "description": 'Function pk_ode_system',
        "required_parameters": [
            {
                "name": 't',
                "type": 'str',
                "description": 'Parameter t',
                "default": None
            },
            {
                "name": 'y',
                "type": 'str',
                "description": 'Parameter y',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
