"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'predict_protein_disorder_regions',
        "description": 'Predicts intrinsically disordered regions (IDRs) in a protein sequence using IUPred2A.',
        "required_parameters": [
            {
                "name": 'protein_sequence',
                "type": 'str',
                "description": 'The amino acid sequence of the protein to analyze',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'threshold',
                "type": 'float',
                "description": 'The disorder score threshold above which a residue is considered disordered (default: 0.5)',
                "default": 0.5
            },
            {
                "name": 'output_file',
                "type": 'str',
                "description": 'Filename to save the per-residue disorder scores (default: "disorder_prediction_results.csv")',
                "default": 'disorder_prediction_results.csv'
            },
        ],
    },
    {
        "name": 'analyze_cell_morphology_and_cytoskeleton',
        "description": 'Quantifies cell morphology and cytoskeletal organization from fluorescence microscopy images.',
        "required_parameters": [
            {
                "name": 'image_path',
                "type": 'str',
                "description": 'Path to the fluorescence microscopy image file',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": "Directory to save output files (default: './results')",
                "default": './results'
            },
            {
                "name": 'threshold_method',
                "type": 'str',
                "description": "Method for cell segmentation ('otsu', 'adaptive', or 'manual') (default: 'otsu')",
                "default": 'otsu'
            },
        ],
    },
    {
        "name": 'analyze_tissue_deformation_flow',
        "description": 'Quantify tissue deformation and flow dynamics from microscopy image sequence.',
        "required_parameters": [
            {
                "name": 'image_sequence',
                "type": 'list or numpy.ndarray',
                "description": 'Sequence of microscopy images (either a list of file paths or a 3D numpy array [time, height, width])',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save results (default: "results")',
                "default": 'results'
            },
            {
                "name": 'pixel_scale',
                "type": 'float',
                "description": 'Physical scale of pixels (e.g., μm/pixel) for proper scaling of metrics (default: 1.0)',
                "default": 1.0
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
