"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'analyze_ddr_network_in_cancer',
        "description": 'Analyze DNA Damage Response (DDR) network alterations and dependencies in cancer samples. This function reconstructs the DDR network from genomic data, identifies disruptions in the network, and analyzes dependencies between DDR pathway components in cancer.',
        "required_parameters": [
            {
                "name": 'expression_data_path',
                "type": 'str',
                "description": 'Path to gene expression data file (CSV format with genes as rows, samples as columns)',
                "default": None
            },
            {
                "name": 'mutation_data_path',
                "type": 'str',
                "description": 'Path to mutation data file (CSV format with genes as rows, samples as columns, values indicating mutation status)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files (default: "./results")',
                "default": './results'
            },
        ],
    },
    {
        "name": 'analyze_cell_senescence_and_apoptosis',
        "description": 'Analyze flow cytometry data to quantify senescent and apoptotic cell populations.',
        "required_parameters": [
            {
                "name": 'fcs_file_path',
                "type": 'str',
                "description": 'Path to the FCS file containing flow cytometry data with measurements for senescence-associated β-galactosidase (SA-β-Gal) and Annexin V/7-AAD staining',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'detect_and_annotate_somatic_mutations',
        "description": 'Detects and annotates somatic mutations in tumor samples compared to matched normal samples. This function uses GATK Mutect2 for variant calling, GATK FilterMutectCalls for filtering, and SnpEff for functional annotation of somatic mutations.',
        "required_parameters": [
            {
                "name": 'tumor_bam',
                "type": 'str',
                "description": 'Path to the tumor sample BAM file',
                "default": None
            },
            {
                "name": 'normal_bam',
                "type": 'str',
                "description": 'Path to the matched normal sample BAM file',
                "default": None
            },
            {
                "name": 'reference_genome',
                "type": 'str',
                "description": 'Path to the reference genome FASTA file',
                "default": None
            },
            {
                "name": 'output_prefix',
                "type": 'str',
                "description": 'Prefix for output files',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'snpeff_database',
                "type": 'str',
                "description": 'SnpEff database to use for annotation (default: "GRCh38.105")',
                "default": 'GRCh38.105'
            },
        ],
    },
    {
        "name": 'detect_and_characterize_structural_variations',
        "description": 'Detects and characterizes structural variations (SVs) in genomic sequencing data. This function uses LUMPY for SV detection followed by annotation with COSMIC and/or ClinVar databases to identify and characterize various types of structural variations including deletions, inversions, translocations, and duplications.',
        "required_parameters": [
            {
                "name": 'bam_file_path',
                "type": 'str',
                "description": 'Path to the aligned sequencing data in BAM format',
                "default": None
            },
            {
                "name": 'reference_genome_path',
                "type": 'str',
                "description": 'Path to the reference genome in FASTA format',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where results will be saved',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'cosmic_db_path',
                "type": 'str',
                "description": 'Path to the COSMIC database for cancer annotation',
                "default": None
            },
            {
                "name": 'clinvar_db_path',
                "type": 'str',
                "description": 'Path to the ClinVar database for clinical annotation',
                "default": None
            },
        ],
    },
    {
        "name": 'perform_gene_expression_nmf_analysis',
        "description": 'Performs Non-negative Matrix Factorization (NMF) on gene expression data to extract metagenes and their associated sample weights for tumor subtype identification.',
        "required_parameters": [
            {
                "name": 'expression_data_path',
                "type": 'str',
                "description": 'Path to a CSV or TSV file containing gene expression data with genes as rows and samples as columns. Values should be non-negative (e.g., normalized counts or expression values).',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'n_components',
                "type": 'int',
                "description": 'Number of metagenes (components) to extract.',
                "default": 10
            },
            {
                "name": 'normalize',
                "type": 'bool',
                "description": 'Whether to normalize the expression data before applying NMF.',
                "default": True
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save the output files.',
                "default": 'nmf_results'
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed for reproducibility.',
                "default": 42
            },
        ],
    },
    {
        "name": 'analyze_copy_number_purity_ploidy_and_focal_events',
        "description": 'CNVkit-based copy number workflow: CNV segmentation, purity/ploidy & HRD approximation, focal events. This function orchestrates a CNVkit-based copy number analysis workflow for tumor samples. It performs CNV segmentation, derives approximate purity & ploidy metrics, calculates a simplified HRD-style summary, and detects focal amplifications/deletions in key oncogenes / tumor suppressors.',
        "required_parameters": [
            {
                "name": 'tumor_bam',
                "type": 'str',
                "description": 'Path to tumor BAM (indexed)',
                "default": None
            },
            {
                "name": 'reference_genome',
                "type": 'str',
                "description": 'Path to reference FASTA (with index files present)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'normal_bam',
                "type": 'str',
                "description": 'Matched normal BAM (recommended for allele-specific & purity inference)',
                "default": None
            },
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory for all outputs',
                "default": 'cn_analysis_results'
            },
            {
                "name": 'targets_bed',
                "type": 'str',
                "description": 'BED of target regions (e.g. exome / panel) for CNVkit / gCNV',
                "default": None
            },
            {
                "name": 'antitargets_bed',
                "type": 'str',
                "description": 'BED of antitarget regions for CNVkit (if panel / exome)',
                "default": None
            },
            {
                "name": 'gene_bed',
                "type": 'str',
                "description": 'BED file with gene coordinates (chrom, start, end, gene). Used for focal event annotation',
                "default": None
            },
            {
                "name": 'focal_genes',
                "type": 'list[str]',
                "description": 'List of genes to highlight for focal amplification/deletion; defaults to ["MYC","ERBB2","CDKN2A"]',
                "default": None
            },
            {
                "name": 'log2_amp_threshold',
                "type": 'float',
                "description": 'Log2 ratio threshold to call focal amplification (~ >2x copy relative to baseline)',
                "default": 1.0
            },
            {
                "name": 'log2_del_threshold',
                "type": 'float',
                "description": 'Log2 ratio threshold to call focal deep deletion (~ homozygous loss)',
                "default": -1.0
            },
        ],
    },
    {
        "name": 'norm_chr',
        "description": 'Function norm_chr',
        "required_parameters": [
            {
                "name": 'x',
                "type": 'str',
                "description": 'Parameter x',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
