"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # EXTERNAL API - PREPROCESSING (sc.external.pp.*)
    # =============================================================================
    {
        "name": 'scRNA_ext_pp_bbknn',
        "description": 'Batch balanced KNN (BBKNN) for batch effect correction.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'batch_key',
                "type": 'str',
                "description": 'Batch key in obs.',
                "default": 'batch'
            },
            {
                "name": 'use_rep',
                "type": 'str',
                "description": 'Representation to use.',
                "default": 'X_pca'
            },
            {
                "name": 'approx',
                "type": 'bool',
                "description": 'Use approximate neighbors.',
                "default": True
            },
            {
                "name": 'n_pcs',
                "type": 'int',
                "description": 'Number of PCs.',
                "default": 50
            },
            {
                "name": 'trim',
                "type": 'int or None',
                "description": 'Trim neighbors.',
                "default": None
            },
            {
                "name": 'n_trees',
                "type": 'int',
                "description": 'Number of trees for Annoy.',
                "default": 10
            },
            {
                "name": 'use_annoy',
                "type": 'bool',
                "description": 'Use Annoy.',
                "default": True
            },
            {
                "name": 'metric',
                "type": 'str',
                "description": 'Distance metric.',
                "default": 'angular'
            },
            {
                "name": 'set_op_mix_ratio',
                "type": 'float',
                "description": 'UMAP set operation mix ratio.',
                "default": 1.0
            },
            {
                "name": 'local_connectivity',
                "type": 'int',
                "description": 'Local connectivity.',
                "default": 1
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
            {
                "name": 'neighbors_within_batch',
                "type": 'int',
                "description": 'Neighbors within batch. **kwargs Additional arguments.',
                "default": 3
            },
        ],
    },
    {
        "name": 'scRNA_ext_pp_harmony_integrate',
        "description": 'Harmony integration for batch correction.',
        "required_parameters": [
            {
                "name": 'key',
                "type": 'str',
                "description": 'Batch key in obs.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'basis',
                "type": 'str',
                "description": 'Embedding to correct.',
                "default": 'X_pca'
            },
            {
                "name": 'adjusted_basis',
                "type": 'str',
                "description": 'Key for corrected embedding.',
                "default": 'X_pca_harmony'
            },
            {
                "name": 'max_iter_harmony',
                "type": 'int',
                "description": 'Maximum iterations. **kwargs Additional arguments for harmonypy.',
                "default": 10
            },
        ],
    },
    {
        "name": 'scRNA_ext_pp_mnn_correct',
        "description": 'MNN correct for batch correction.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_ext_pp_scanorama_integrate',
        "description": 'Scanorama integration for batch correction.',
        "required_parameters": [
            {
                "name": 'key',
                "type": 'str',
                "description": 'Batch key in obs.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'basis',
                "type": 'str',
                "description": 'Embedding to correct.',
                "default": 'X_pca'
            },
            {
                "name": 'adjusted_basis',
                "type": 'str',
                "description": 'Key for corrected embedding. **kwargs Additional arguments for scanorama.',
                "default": 'X_scanorama'
            },
        ],
    },
    {
        "name": 'scRNA_ext_pp_hashsolo',
        "description": 'HashSolo for sample demultiplexing.',
        "required_parameters": [
            {
                "name": 'cell_hashing_columns',
                "type": 'Collection[str]',
                "description": 'Cell hashing columns in obs.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'priors',
                "type": 'tuple',
                "description": 'Prior probabilities for negative, singlet, doublet.',
                "default": (0.01, 0.8, 0.19)
            },
            {
                "name": 'pre_existing_clusters',
                "type": 'str or None',
                "description": 'Pre-existing clusters.',
                "default": None
            },
            {
                "name": 'number_of_noise_barcodes',
                "type": 'int or None',
                "description": 'Number of noise barcodes.',
                "default": None
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata inplace.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_ext_pp_dca',
        "description": 'Deep Count Autoencoder for denoising/imputation.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'mode',
                "type": 'str',
                "description": "Mode ('denoise' or 'latent').",
                "default": 'denoise'
            },
            {
                "name": 'ae_type',
                "type": 'str',
                "description": 'Autoencoder type.',
                "default": 'zinb-conddisp'
            },
            {
                "name": 'normalize_per_cell',
                "type": 'bool',
                "description": 'Normalize per cell.',
                "default": True
            },
            {
                "name": 'scale',
                "type": 'bool',
                "description": 'Scale data.',
                "default": True
            },
            {
                "name": 'log1p',
                "type": 'bool',
                "description": 'Log transform.',
                "default": True
            },
            {
                "name": 'hidden_size',
                "type": 'tuple',
                "description": 'Hidden layer sizes.',
                "default": (64, 32, 64)
            },
            {
                "name": 'hidden_dropout',
                "type": 'float',
                "description": 'Dropout rate.',
                "default": 0.0
            },
            {
                "name": 'batchnorm',
                "type": 'bool',
                "description": 'Batch normalization.',
                "default": True
            },
            {
                "name": 'activation',
                "type": 'str',
                "description": 'Activation function.',
                "default": 'relu'
            },
            {
                "name": 'init',
                "type": 'str',
                "description": 'Initialization.',
                "default": 'glorot_uniform'
            },
            {
                "name": 'network_kwds',
                "type": 'dict or None',
                "description": 'Network keywords.',
                "default": None
            },
            {
                "name": 'epochs',
                "type": 'int',
                "description": 'Training epochs.',
                "default": 300
            },
            {
                "name": 'reduce_lr',
                "type": 'int',
                "description": 'Reduce learning rate patience.',
                "default": 10
            },
            {
                "name": 'early_stop',
                "type": 'int',
                "description": 'Early stopping patience.',
                "default": 15
            },
            {
                "name": 'batch_size',
                "type": 'int',
                "description": 'Batch size.',
                "default": 32
            },
            {
                "name": 'optimizer',
                "type": 'str',
                "description": 'Optimizer.',
                "default": 'RMSprop'
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'threads',
                "type": 'int or None',
                "description": 'Number of threads.',
                "default": None
            },
            {
                "name": 'learning_rate',
                "type": 'float or None',
                "description": 'Learning rate.',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Verbose output.',
                "default": True
            },
            {
                "name": 'training_kwds',
                "type": 'dict or None',
                "description": 'Training keywords.',
                "default": None
            },
            {
                "name": 'return_model',
                "type": 'bool',
                "description": 'Return model.',
                "default": False
            },
            {
                "name": 'return_info',
                "type": 'bool',
                "description": 'Return info.',
                "default": False
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_pp_magic',
        "description": 'MAGIC imputation.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'name_list',
                "type": 'str or Collection[str] or None',
                "description": 'Genes to impute.',
                "default": None
            },
            {
                "name": 'k',
                "type": 'int',
                "description": 'Number of neighbors.',
                "default": 10
            },
            {
                "name": 'a',
                "type": 'int',
                "description": 'Adaptive kernel width.',
                "default": 15
            },
            {
                "name": 't',
                "type": 'int or str',
                "description": 'Diffusion time.',
                "default": 'auto'
            },
            {
                "name": 'n_pca',
                "type": 'int',
                "description": 'Number of PCs.',
                "default": 100
            },
            {
                "name": 'solver',
                "type": 'str',
                "description": "Solver ('exact' or 'approximate').",
                "default": 'exact'
            },
            {
                "name": 'knn_dist',
                "type": 'str',
                "description": 'KNN distance metric.',
                "default": 'euclidean'
            },
            {
                "name": 'random_state',
                "type": 'int or None',
                "description": 'Random seed.',
                "default": None
            },
            {
                "name": 'n_jobs',
                "type": 'int',
                "description": 'Number of jobs.',
                "default": 1
            },
            {
                "name": 'verbose',
                "type": 'int',
                "description": 'Verbosity.',
                "default": 1
            },
            {
                "name": 'copy',
                "type": 'bool or None',
                "description": 'Return copy. **kwargs Additional arguments.',
                "default": None
            },
        ],
    },
    # =============================================================================
    # EXTERNAL API - TOOLS (sc.external.tl.*)
    # =============================================================================
    {
        "name": 'scRNA_ext_tl_phate',
        "description": 'PHATE embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'n_components',
                "type": 'int',
                "description": 'Number of dimensions.',
                "default": 2
            },
            {
                "name": 'k',
                "type": 'int',
                "description": 'Number of neighbors.',
                "default": 5
            },
            {
                "name": 'a',
                "type": 'int',
                "description": 'Adaptive kernel width.',
                "default": 15
            },
            {
                "name": 'n_landmark',
                "type": 'int',
                "description": 'Number of landmarks.',
                "default": 2000
            },
            {
                "name": 't',
                "type": 'int or str',
                "description": 'Diffusion time.',
                "default": 'auto'
            },
            {
                "name": 'gamma',
                "type": 'float',
                "description": 'Informational distance.',
                "default": 1
            },
            {
                "name": 'n_pca',
                "type": 'int',
                "description": 'Number of PCs.',
                "default": 100
            },
            {
                "name": 'mds_solver',
                "type": 'str',
                "description": 'MDS solver.',
                "default": 'sgd'
            },
            {
                "name": 'knn_dist',
                "type": 'str',
                "description": 'KNN distance.',
                "default": 'euclidean'
            },
            {
                "name": 'mds_dist',
                "type": 'str',
                "description": 'MDS distance.',
                "default": 'euclidean'
            },
            {
                "name": 'mds',
                "type": 'str',
                "description": 'MDS type.',
                "default": 'metric'
            },
            {
                "name": 'n_jobs',
                "type": 'int',
                "description": 'Number of jobs.',
                "default": 1
            },
            {
                "name": 'random_state',
                "type": 'int or None',
                "description": 'Random seed.',
                "default": None
            },
            {
                "name": 'verbose',
                "type": 'int',
                "description": 'Verbosity.',
                "default": 1
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy. **kwargs Additional arguments.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_palantir',
        "description": 'Palantir for trajectory inference.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'n_components',
                "type": 'int',
                "description": 'Number of diffusion components.',
                "default": 10
            },
            {
                "name": 'knn',
                "type": 'int',
                "description": 'Number of neighbors.',
                "default": 30
            },
            {
                "name": 'dfmap_width',
                "type": 'float',
                "description": 'Diffusion map width.',
                "default": 0.1
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_palantir_results',
        "description": 'Compute Palantir results.',
        "required_parameters": [
            {
                "name": 'early_cell',
                "type": 'str',
                "description": 'Early cell index.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'ms_data',
                "type": 'DataFrame or None',
                "description": 'Multiscale data.',
                "default": None
            },
            {
                "name": 'terminal_states',
                "type": 'Collection[str] or None',
                "description": 'Terminal states.',
                "default": None
            },
            {
                "name": 'knn',
                "type": 'int',
                "description": 'Number of neighbors.',
                "default": 30
            },
            {
                "name": 'num_waypoints',
                "type": 'int',
                "description": 'Number of waypoints.',
                "default": 1200
            },
            {
                "name": 'n_jobs',
                "type": 'int',
                "description": 'Number of jobs.',
                "default": -1
            },
            {
                "name": 'scale_components',
                "type": 'bool',
                "description": 'Scale components.',
                "default": True
            },
            {
                "name": 'use_early_cell_as_start',
                "type": 'bool',
                "description": 'Use early cell as start.',
                "default": True
            },
            {
                "name": 'max_iterations',
                "type": 'int',
                "description": 'Maximum iterations.',
                "default": 25
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_trimap',
        "description": 'TriMap embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'n_components',
                "type": 'int',
                "description": 'Number of dimensions.',
                "default": 2
            },
            {
                "name": 'n_inliers',
                "type": 'int',
                "description": 'Number of inliers.',
                "default": 10
            },
            {
                "name": 'n_outliers',
                "type": 'int',
                "description": 'Number of outliers.',
                "default": 5
            },
            {
                "name": 'n_random',
                "type": 'int',
                "description": 'Number of random.',
                "default": 5
            },
            {
                "name": 'weight_adj',
                "type": 'float',
                "description": 'Weight adjustment.',
                "default": 500.0
            },
            {
                "name": 'n_iters',
                "type": 'int',
                "description": 'Number of iterations.',
                "default": 400
            },
            {
                "name": 'init',
                "type": 'str',
                "description": 'Initialization.',
                "default": 'random'
            },
            {
                "name": 'apply_pca',
                "type": 'bool',
                "description": 'Apply PCA first.',
                "default": True
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Verbose output.',
                "default": True
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_sam',
        "description": 'SAM (Self-Assembling Manifolds) embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'max_iter',
                "type": 'int',
                "description": 'Maximum iterations.',
                "default": 10
            },
            {
                "name": 'num_norm_avg',
                "type": 'int',
                "description": 'Number for normalization average.',
                "default": 50
            },
            {
                "name": 'k',
                "type": 'int',
                "description": 'Number of neighbors.',
                "default": 20
            },
            {
                "name": 'distance',
                "type": 'str',
                "description": 'Distance metric.',
                "default": 'correlation'
            },
            {
                "name": 'standardization',
                "type": 'str',
                "description": 'Standardization method.',
                "default": 'Normalizer'
            },
            {
                "name": 'weight_pcs',
                "type": 'bool',
                "description": 'Weight PCs.',
                "default": True
            },
            {
                "name": 'npcs',
                "type": 'int',
                "description": 'Number of PCs.',
                "default": 150
            },
            {
                "name": 'n_genes',
                "type": 'int',
                "description": 'Number of genes.',
                "default": 3000
            },
            {
                "name": 'projection',
                "type": 'str',
                "description": 'Projection method.',
                "default": 'umap'
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata inplace.',
                "default": True
            },
            {
                "name": 'verbose',
                "type": 'bool',
                "description": 'Verbose output.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_phenograph',
        "description": 'PhenoGraph clustering.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'clustering_algo',
                "type": 'str',
                "description": 'Clustering algorithm.',
                "default": 'leiden'
            },
            {
                "name": 'k',
                "type": 'int',
                "description": 'Number of neighbors.',
                "default": 30
            },
            {
                "name": 'directed',
                "type": 'bool',
                "description": 'Use directed graph.',
                "default": False
            },
            {
                "name": 'prune',
                "type": 'bool',
                "description": 'Prune graph.',
                "default": False
            },
            {
                "name": 'min_cluster_size',
                "type": 'int',
                "description": 'Minimum cluster size.',
                "default": 10
            },
            {
                "name": 'jaccard',
                "type": 'bool',
                "description": 'Use Jaccard index.',
                "default": True
            },
            {
                "name": 'primary_metric',
                "type": 'str',
                "description": 'Primary metric.',
                "default": 'euclidean'
            },
            {
                "name": 'n_jobs',
                "type": 'int',
                "description": 'Number of jobs.',
                "default": -1
            },
            {
                "name": 'q_tol',
                "type": 'float',
                "description": 'Q tolerance.',
                "default": 0.001
            },
            {
                "name": 'louvain_time_limit',
                "type": 'int',
                "description": 'Louvain time limit.',
                "default": 2000
            },
            {
                "name": 'nn_method',
                "type": 'str',
                "description": 'Nearest neighbor method.',
                "default": 'kdtree'
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_harmony_timeseries',
        "description": 'Harmony timeseries analysis.',
        "required_parameters": [
            {
                "name": 'tp',
                "type": 'str',
                "description": 'Timepoint key in obs.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'n_neighbors',
                "type": 'int',
                "description": 'Number of neighbors.',
                "default": 30
            },
            {
                "name": 'n_components',
                "type": 'int',
                "description": 'Number of components.',
                "default": 1000
            },
            {
                "name": 'augmentation',
                "type": 'int',
                "description": 'Augmentation factor.',
                "default": 4
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_wishbone',
        "description": 'Wishbone for trajectory inference.',
        "required_parameters": [
            {
                "name": 'start_cell',
                "type": 'str',
                "description": 'Start cell index.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'branch',
                "type": 'bool',
                "description": 'Detect branching.',
                "default": True
            },
            {
                "name": 'k',
                "type": 'int',
                "description": 'Number of neighbors.',
                "default": 15
            },
            {
                "name": 'components',
                "type": 'list',
                "description": 'Components to use.',
                "default": [1, 2, 3]
            },
            {
                "name": 'num_waypoints',
                "type": 'int',
                "description": 'Number of waypoints.',
                "default": 250
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_sandbag',
        "description": 'Sandbag for cell cycle phase assignment training.',
        "required_parameters": [
            {
                "name": 'annotation',
                "type": 'str',
                "description": 'Obs column with phase annotations.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'gene_names',
                "type": 'str',
                "description": 'Gene names column.',
                "default": 'index'
            },
            {
                "name": 'fraction',
                "type": 'float',
                "description": 'Fraction threshold.',
                "default": 0.5
            },
            {
                "name": 'filter_genes',
                "type": 'bool',
                "description": 'Filter genes.',
                "default": False
            },
            {
                "name": 'filter_cells',
                "type": 'bool',
                "description": 'Filter cells.',
                "default": False
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_tl_cyclone',
        "description": 'Cyclone for cell cycle phase prediction.',
        "required_parameters": [
            {
                "name": 'marker_pairs',
                "type": 'dict',
                "description": 'Marker pairs from sandbag.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'gene_names',
                "type": 'str',
                "description": 'Gene names column.',
                "default": 'index'
            },
            {
                "name": 'iterations',
                "type": 'int',
                "description": 'Number of iterations.',
                "default": 1000
            },
            {
                "name": 'min_iter',
                "type": 'int',
                "description": 'Minimum iterations.',
                "default": 100
            },
            {
                "name": 'min_pairs',
                "type": 'int',
                "description": 'Minimum pairs.',
                "default": 50
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    # =============================================================================
    # EXTERNAL API - PLOTTING (sc.external.pl.*)
    # =============================================================================
    {
        "name": 'scRNA_ext_pl_phate',
        "description": 'Plot PHATE embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'color',
                "type": 'str or Collection[str] or None',
                "description": 'Color by. ... (similar to scRNA_pl_umap)',
                "default": None
            },
            {
                "name": 'use_raw',
                "type": 'str',
                "description": 'Parameter use_raw',
                "default": None
            },
            {
                "name": 'layer',
                "type": 'str',
                "description": 'Parameter layer',
                "default": None
            },
            {
                "name": 'sort_order',
                "type": 'bool',
                "description": 'Parameter sort_order',
                "default": True
            },
            {
                "name": 'groups',
                "type": 'str',
                "description": 'Parameter groups',
                "default": None
            },
            {
                "name": 'components',
                "type": 'str',
                "description": 'Parameter components',
                "default": None
            },
            {
                "name": 'projection',
                "type": 'str',
                "description": 'Parameter projection',
                "default": '2d'
            },
            {
                "name": 'legend_loc',
                "type": 'str',
                "description": 'Parameter legend_loc',
                "default": 'right margin'
            },
            {
                "name": 'legend_fontsize',
                "type": 'str',
                "description": 'Parameter legend_fontsize',
                "default": None
            },
            {
                "name": 'legend_fontweight',
                "type": 'str',
                "description": 'Parameter legend_fontweight',
                "default": None
            },
            {
                "name": 'legend_fontoutline',
                "type": 'str',
                "description": 'Parameter legend_fontoutline',
                "default": None
            },
            {
                "name": 'color_map',
                "type": 'str',
                "description": 'Parameter color_map',
                "default": None
            },
            {
                "name": 'palette',
                "type": 'str',
                "description": 'Parameter palette',
                "default": None
            },
            {
                "name": 'frameon',
                "type": 'str',
                "description": 'Parameter frameon',
                "default": None
            },
            {
                "name": 'size',
                "type": 'str',
                "description": 'Parameter size',
                "default": None
            },
            {
                "name": 'title',
                "type": 'str',
                "description": 'Parameter title',
                "default": None
            },
            {
                "name": 'show',
                "type": 'str',
                "description": 'Parameter show',
                "default": None
            },
            {
                "name": 'save',
                "type": 'str',
                "description": 'Parameter save',
                "default": None
            },
            {
                "name": 'ax',
                "type": 'str',
                "description": 'Parameter ax',
                "default": None
            },
            {
                "name": 'ncols',
                "type": 'int',
                "description": 'Parameter ncols',
                "default": 4
            },
            {
                "name": 'wspace',
                "type": 'str',
                "description": 'Parameter wspace',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_ext_pl_trimap',
        "description": 'Plot TriMap embedding. Returns ------- Axes or list of Axes or None.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'color',
                "type": 'str',
                "description": 'Parameter color',
                "default": None
            },
            {
                "name": 'use_raw',
                "type": 'str',
                "description": 'Parameter use_raw',
                "default": None
            },
            {
                "name": 'layer',
                "type": 'str',
                "description": 'Parameter layer',
                "default": None
            },
            {
                "name": 'sort_order',
                "type": 'bool',
                "description": 'Parameter sort_order',
                "default": True
            },
            {
                "name": 'groups',
                "type": 'str',
                "description": 'Parameter groups',
                "default": None
            },
            {
                "name": 'components',
                "type": 'str',
                "description": 'Parameter components',
                "default": None
            },
            {
                "name": 'projection',
                "type": 'str',
                "description": 'Parameter projection',
                "default": '2d'
            },
            {
                "name": 'legend_loc',
                "type": 'str',
                "description": 'Parameter legend_loc',
                "default": 'right margin'
            },
            {
                "name": 'legend_fontsize',
                "type": 'str',
                "description": 'Parameter legend_fontsize',
                "default": None
            },
            {
                "name": 'legend_fontweight',
                "type": 'str',
                "description": 'Parameter legend_fontweight',
                "default": None
            },
            {
                "name": 'legend_fontoutline',
                "type": 'str',
                "description": 'Parameter legend_fontoutline',
                "default": None
            },
            {
                "name": 'color_map',
                "type": 'str',
                "description": 'Parameter color_map',
                "default": None
            },
            {
                "name": 'palette',
                "type": 'str',
                "description": 'Parameter palette',
                "default": None
            },
            {
                "name": 'frameon',
                "type": 'str',
                "description": 'Parameter frameon',
                "default": None
            },
            {
                "name": 'size',
                "type": 'str',
                "description": 'Parameter size',
                "default": None
            },
            {
                "name": 'title',
                "type": 'str',
                "description": 'Parameter title',
                "default": None
            },
            {
                "name": 'show',
                "type": 'str',
                "description": 'Parameter show',
                "default": None
            },
            {
                "name": 'save',
                "type": 'str',
                "description": 'Parameter save',
                "default": None
            },
            {
                "name": 'ax',
                "type": 'str',
                "description": 'Parameter ax',
                "default": None
            },
            {
                "name": 'ncols',
                "type": 'int',
                "description": 'Parameter ncols',
                "default": 4
            },
            {
                "name": 'wspace',
                "type": 'str',
                "description": 'Parameter wspace',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_ext_pl_sam',
        "description": 'Plot SAM embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'projection',
                "type": 'str',
                "description": 'Projection key.',
                "default": 'X_umap'
            },
            {
                "name": 'c',
                "type": 'str or None',
                "description": 'Color by.',
                "default": None
            },
            {
                "name": 'cmap',
                "type": 'str',
                "description": 'Colormap.',
                "default": 'Spectral_r'
            },
            {
                "name": 'linewidth',
                "type": 'float',
                "description": 'Line width.',
                "default": 0
            },
            {
                "name": 'edgecolor',
                "type": 'str',
                "description": 'Edge color.',
                "default": 'k'
            },
            {
                "name": 'axes',
                "type": 'Axes or None',
                "description": 'Axes.',
                "default": None
            },
            {
                "name": 'colorbar',
                "type": 'bool',
                "description": 'Show colorbar.',
                "default": True
            },
            {
                "name": 's',
                "type": 'int',
                "description": 'Point size.',
                "default": 10
            },
            {
                "name": 'vmin',
                "type": 'float or None',
                "description": 'Minimum value.',
                "default": None
            },
            {
                "name": 'vmax',
                "type": 'float or None',
                "description": 'Maximum value. **kwds Additional arguments.',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_ext_pl_wishbone_marker_trajectory',
        "description": 'Plot Wishbone marker trajectory.',
        "required_parameters": [
            {
                "name": 'markers',
                "type": 'Collection[str]',
                "description": 'Markers to plot.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'no_bins',
                "type": 'int',
                "description": 'Number of bins.',
                "default": 150
            },
            {
                "name": 'smoothing_factor',
                "type": 'float',
                "description": 'Smoothing factor.',
                "default": 1
            },
            {
                "name": 'min_delta',
                "type": 'float',
                "description": 'Minimum delta.',
                "default": 0.1
            },
            {
                "name": 'show_variance',
                "type": 'bool',
                "description": 'Show variance.',
                "default": False
            },
            {
                "name": 'figsize',
                "type": 'tuple or None',
                "description": 'Figure size.',
                "default": None
            },
            {
                "name": 'show',
                "type": 'bool or None',
                "description": 'Show plot.',
                "default": None
            },
            {
                "name": 'save',
                "type": 'str or bool or None',
                "description": 'Save figure.',
                "default": None
            },
        ],
    },
    # =============================================================================
    # EXTERNAL API - EXPORTING (sc.external.exporting.*)
    # =============================================================================
    {
        "name": 'scRNA_ext_exporting_spring_project',
        "description": 'Export to SPRING viewer format.',
        "required_parameters": [
            {
                "name": 'project_dir',
                "type": 'str or Path',
                "description": 'Project directory.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'embedding_method',
                "type": 'str',
                "description": 'Embedding method.',
                "default": 'umap'
            },
            {
                "name": 'subplot_name',
                "type": 'str or None',
                "description": 'Subplot name.',
                "default": None
            },
            {
                "name": 'cell_groupings',
                "type": 'Collection[str] or None',
                "description": 'Cell groupings.',
                "default": None
            },
            {
                "name": 'custom_color_tracks',
                "type": 'Collection[str] or None',
                "description": 'Custom color tracks.',
                "default": None
            },
            {
                "name": 'total_counts_key',
                "type": 'str',
                "description": 'Total counts key.',
                "default": 'n_counts'
            },
            {
                "name": 'overwrite',
                "type": 'bool',
                "description": 'Overwrite existing.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_exporting_cellbrowser',
        "description": 'Export to UCSC Cell Browser format.',
        "required_parameters": [
            {
                "name": 'data_dir',
                "type": 'str or Path',
                "description": 'Data directory.',
                "default": None
            },
            {
                "name": 'data_name',
                "type": 'str',
                "description": 'Dataset name.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'embedding_keys',
                "type": 'Collection[str] or None',
                "description": 'Embedding keys.',
                "default": None
            },
            {
                "name": 'annot_keys',
                "type": 'Collection[str] or None',
                "description": 'Annotation keys.',
                "default": None
            },
            {
                "name": 'cluster_field',
                "type": 'str',
                "description": 'Cluster field.',
                "default": 'louvain'
            },
            {
                "name": 'nb_marker',
                "type": 'int',
                "description": 'Number of markers.',
                "default": 50
            },
            {
                "name": 'skip_matrix',
                "type": 'bool',
                "description": 'Skip matrix export.',
                "default": False
            },
            {
                "name": 'html_dir',
                "type": 'str or None',
                "description": 'HTML directory.',
                "default": None
            },
            {
                "name": 'port',
                "type": 'int or None',
                "description": 'Port.',
                "default": None
            },
            {
                "name": 'do_debug',
                "type": 'bool',
                "description": 'Debug mode. **kwargs Additional arguments.',
                "default": False
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
