"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'scRNA_ext_cnmf_prepare',
        "description": 'Prepare data and parameters for cNMF analysis. This initializes the cNMF object and prepares the data for factorization. It handles normalization, gene selection, and saves intermediate files.',
        "required_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files.',
                "default": None
            },
            {
                "name": 'name',
                "type": 'str',
                "description": 'Name for this cNMF run (used as prefix for output files).',
                "default": None
            },
            {
                "name": 'counts_fn',
                "type": 'str',
                "description": 'Path to counts file. Supports: - .h5ad (scanpy/AnnData format, recommended for large datasets) - .txt/.tsv (tab-delimited text with cells as rows, genes as columns) - Path to 10x mtx directory (containing counts.mtx, barcodes.tsv, genes.tsv)',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'components',
                "type": 'list of int or range',
                "description": 'Values of K (number of components) to test.',
                "default": None
            },
            {
                "name": 'n_iter',
                "type": 'int',
                "description": 'Number of NMF iterations per K value.',
                "default": 100
            },
            {
                "name": 'seed',
                "type": 'int',
                "description": 'Random seed for reproducibility.',
                "default": 14
            },
            {
                "name": 'num_highvar_genes',
                "type": 'int',
                "description": 'Number of high-variance genes to use.',
                "default": 2000
            },
            {
                "name": 'genes_file',
                "type": 'str or None',
                "description": 'Path to file with gene list (one gene per line). If provided, uses these genes instead of selecting high-variance genes.',
                "default": None
            },
            {
                "name": 'tpm_fn',
                "type": 'str or None',
                "description": 'Path to TPM-normalized counts file. If not provided, will be computed from counts.',
                "default": None
            },
            {
                "name": 'densify',
                "type": 'bool',
                "description": 'If True, convert sparse matrix to dense. Use when data is not sparse.',
                "default": False
            },
            {
                "name": 'beta_loss',
                "type": 'str',
                "description": "Beta loss function for NMF ('frobenius' or 'kullback-leibler'). Frobenius is faster and recommended for most cases.",
                "default": 'frobenius'
            },
        ],
    },
    {
        "name": 'scRNA_ext_cnmf_factorize',
        "description": 'Run NMF factorization for cNMF. This performs the actual NMF decomposition. Can be parallelized across multiple workers for large datasets.',
        "required_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where cNMF was prepared.',
                "default": None
            },
            {
                "name": 'name',
                "type": 'str',
                "description": 'Name of the cNMF run.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'worker_index',
                "type": 'int',
                "description": 'Index of this worker (0-indexed). Use for parallelization.',
                "default": 0
            },
            {
                "name": 'total_workers',
                "type": 'int',
                "description": 'Total number of workers. Set to 1 for single-threaded execution.',
                "default": 1
            },
        ],
    },
    {
        "name": 'scRNA_ext_cnmf_combine',
        "description": 'Combine factorization results from all workers. After factorization (potentially from multiple workers), this combines all results into a single file for each K value.',
        "required_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where cNMF was run.',
                "default": None
            },
            {
                "name": 'name',
                "type": 'str',
                "description": 'Name of the cNMF run.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'skip_missing_files',
                "type": 'bool',
                "description": 'If True, skip incomplete factorization iterations instead of raising error. Useful if some workers failed.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_cnmf_k_selection_plot',
        "description": 'Generate K selection plot for choosing optimal number of components. Creates a diagnostic plot showing stability and error metrics for each K, helping to select the optimal number of gene expression programs.',
        "required_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where cNMF was run.',
                "default": None
            },
            {
                "name": 'name',
                "type": 'str',
                "description": 'Name of the cNMF run.',
                "default": None
            },
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_ext_cnmf_consensus',
        "description": 'Run consensus clustering to get final gene expression programs. After selecting optimal K from k_selection_plot, this performs consensus clustering on the NMF results to get robust gene expression programs.',
        "required_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where cNMF was run.',
                "default": None
            },
            {
                "name": 'name',
                "type": 'str',
                "description": 'Name of the cNMF run.',
                "default": None
            },
            {
                "name": 'k',
                "type": 'int',
                "description": 'Number of components (chosen from k_selection_plot).',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'density_threshold',
                "type": 'float',
                "description": 'Local density threshold for filtering outliers. Lower values are more stringent. 0.01-0.2 are typical values.',
                "default": 0.01
            },
            {
                "name": 'show_clustering',
                "type": 'bool',
                "description": 'If True, generate clustering diagnostic plot.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_ext_cnmf_load_results',
        "description": 'Load cNMF results after consensus clustering.',
        "required_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory where cNMF was run.',
                "default": None
            },
            {
                "name": 'name',
                "type": 'str',
                "description": 'Name of the cNMF run.',
                "default": None
            },
            {
                "name": 'k',
                "type": 'int',
                "description": 'Number of components.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'density_threshold',
                "type": 'float',
                "description": 'Density threshold used in consensus.',
                "default": 0.01
            },
            {
                "name": 'normalize_usage',
                "type": 'bool',
                "description": 'If True, normalize usage to sum to 1 per cell.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_ext_cnmf_preprocess_batch_correct',
        "description": 'Preprocess and batch-correct data for cNMF using Harmony adaptation. Uses an adaptation of Harmony that corrects the underlying count matrix rather than principal components, making it suitable for cNMF input.',
        "required_parameters": [
            {
                "name": 'harmony_vars',
                "type": 'list of str',
                "description": "List of column names in adata.obs to correct for (e.g., ['batch', 'sample']).",
                "default": None
            },
            {
                "name": 'save_output_base',
                "type": 'str',
                "description": 'Base path for saving output files.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'n_top_rna_genes',
                "type": 'int',
                "description": 'Number of top variable genes to select.',
                "default": 2000
            },
            {
                "name": 'librarysize_targetsum',
                "type": 'float',
                "description": 'Target sum for library size normalization (TPM = 1e6).',
                "default": 1000000.0
            },
            {
                "name": 'random_seed',
                "type": 'int',
                "description": 'Random seed for reproducibility.',
                "default": 14
            },
        ],
    },
    {
        "name": 'scRNA_ext_cnmf_run_full_pipeline',
        "description": 'Run the complete cNMF pipeline in one function. This is a convenience function that runs all cNMF steps sequentially. For large datasets, consider running steps individually with parallelization.',
        "required_parameters": [
            {
                "name": 'output_dir',
                "type": 'str',
                "description": 'Directory to save output files.',
                "default": None
            },
            {
                "name": 'name',
                "type": 'str',
                "description": 'Name for this cNMF run.',
                "default": None
            },
            {
                "name": 'counts_fn',
                "type": 'str',
                "description": 'Path to counts file (.h5ad, .txt, or 10x mtx directory).',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'components',
                "type": 'list of int or range',
                "description": 'Values of K to test.',
                "default": None
            },
            {
                "name": 'n_iter',
                "type": 'int',
                "description": 'Number of NMF iterations per K.',
                "default": 100
            },
            {
                "name": 'seed',
                "type": 'int',
                "description": 'Random seed.',
                "default": 14
            },
            {
                "name": 'num_highvar_genes',
                "type": 'int',
                "description": 'Number of high-variance genes.',
                "default": 2000
            },
            {
                "name": 'genes_file',
                "type": 'str or None',
                "description": 'Path to gene list file.',
                "default": None
            },
            {
                "name": 'tpm_fn',
                "type": 'str or None',
                "description": 'Path to TPM file.',
                "default": None
            },
            {
                "name": 'selected_k',
                "type": 'int or None',
                "description": 'Pre-selected K value. If None, will need to manually select after viewing k_selection_plot and call consensus separately.',
                "default": None
            },
            {
                "name": 'density_threshold',
                "type": 'float',
                "description": 'Density threshold for consensus clustering.',
                "default": 0.01
            },
            {
                "name": 'total_workers',
                "type": 'int',
                "description": 'Number of parallel workers for factorization.',
                "default": 1
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
