"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # TOOLS FUNCTIONS (sc.tl.*)
    # =============================================================================
    {
        "name": 'scRNA_tl_tsne',
        "description": 't-SNE embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'n_pcs',
                "type": 'int or None',
                "description": 'Number of PCs to use.',
                "default": None
            },
            {
                "name": 'use_rep',
                "type": 'str or None',
                "description": 'Representation to use.',
                "default": None
            },
            {
                "name": 'perplexity',
                "type": 'float',
                "description": 'Perplexity parameter.',
                "default": 30
            },
            {
                "name": 'early_exaggeration',
                "type": 'float',
                "description": 'Early exaggeration factor.',
                "default": 12
            },
            {
                "name": 'learning_rate',
                "type": 'float',
                "description": 'Learning rate.',
                "default": 1000
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'n_jobs',
                "type": 'int or None',
                "description": 'Number of jobs.',
                "default": None
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_tl_umap',
        "description": 'UMAP embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'min_dist',
                "type": 'float',
                "description": 'Minimum distance between points.',
                "default": 0.5
            },
            {
                "name": 'spread',
                "type": 'float',
                "description": 'Spread of embedded points.',
                "default": 1.0
            },
            {
                "name": 'n_components',
                "type": 'int',
                "description": 'Number of dimensions.',
                "default": 2
            },
            {
                "name": 'maxiter',
                "type": 'int or None',
                "description": 'Maximum iterations.',
                "default": None
            },
            {
                "name": 'alpha',
                "type": 'float',
                "description": 'Initial learning rate.',
                "default": 1.0
            },
            {
                "name": 'gamma',
                "type": 'float',
                "description": 'Repulsion strength.',
                "default": 1.0
            },
            {
                "name": 'negative_sample_rate',
                "type": 'int',
                "description": 'Negative sampling rate.',
                "default": 5
            },
            {
                "name": 'init_pos',
                "type": 'str',
                "description": 'Initial position.',
                "default": 'spectral'
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'a',
                "type": 'float or None',
                "description": 'UMAP parameter a.',
                "default": None
            },
            {
                "name": 'b',
                "type": 'float or None',
                "description": 'UMAP parameter b.',
                "default": None
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
            {
                "name": 'method',
                "type": 'str',
                "description": 'UMAP method.',
                "default": 'umap'
            },
            {
                "name": 'neighbors_key',
                "type": 'str or None',
                "description": 'Neighbors key.',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_tl_draw_graph',
        "description": 'Force-directed graph drawing.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'layout',
                "type": 'str',
                "description": "Layout algorithm ('fa', 'fr', 'kk', 'lgl', 'drl', 'rt').",
                "default": 'fa'
            },
            {
                "name": 'init_pos',
                "type": 'str or None',
                "description": 'Initial positions.',
                "default": None
            },
            {
                "name": 'root',
                "type": 'int or None',
                "description": 'Root node for tree layouts.',
                "default": None
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'n_jobs',
                "type": 'int or None',
                "description": 'Number of jobs.',
                "default": None
            },
            {
                "name": 'adjacency',
                "type": 'sparse matrix or None',
                "description": 'Adjacency matrix.',
                "default": None
            },
            {
                "name": 'key_added_ext',
                "type": 'str or None',
                "description": 'Extension to key.',
                "default": None
            },
            {
                "name": 'neighbors_key',
                "type": 'str or None',
                "description": 'Neighbors key.',
                "default": None
            },
            {
                "name": 'obsp',
                "type": 'str or None',
                "description": 'Obsp key.',
                "default": None
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy. **kwds Additional arguments.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_tl_diffmap',
        "description": 'Diffusion Maps embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'n_comps',
                "type": 'int',
                "description": 'Number of diffusion components.',
                "default": 15
            },
            {
                "name": 'neighbors_key',
                "type": 'str or None',
                "description": 'Neighbors key.',
                "default": None
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_tl_embedding_density',
        "description": 'Calculate density of cells in embedding.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'basis',
                "type": 'str',
                "description": 'Embedding basis.',
                "default": 'umap'
            },
            {
                "name": 'groupby',
                "type": 'str or None',
                "description": 'Group by obs column.',
                "default": None
            },
            {
                "name": 'key_added',
                "type": 'str or None',
                "description": 'Key to add.',
                "default": None
            },
            {
                "name": 'components',
                "type": 'str or None',
                "description": 'Components to use.',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_tl_leiden',
        "description": 'Leiden clustering.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'resolution',
                "type": 'float',
                "description": 'Resolution parameter.',
                "default": 1
            },
            {
                "name": 'restrict_to',
                "type": 'tuple or None',
                "description": 'Restrict to subset.',
                "default": None
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'key_added',
                "type": 'str',
                "description": 'Key to add.',
                "default": 'leiden'
            },
            {
                "name": 'adjacency',
                "type": 'sparse matrix or None',
                "description": 'Adjacency matrix.',
                "default": None
            },
            {
                "name": 'directed',
                "type": 'bool or None',
                "description": 'Use directed graph.',
                "default": None
            },
            {
                "name": 'use_weights',
                "type": 'bool',
                "description": 'Use edge weights.',
                "default": True
            },
            {
                "name": 'n_iterations',
                "type": 'int',
                "description": 'Number of iterations.',
                "default": -1
            },
            {
                "name": 'partition_type',
                "type": 'type or None',
                "description": 'Partition type.',
                "default": None
            },
            {
                "name": 'neighbors_key',
                "type": 'str or None',
                "description": 'Neighbors key.',
                "default": None
            },
            {
                "name": 'obsp',
                "type": 'str or None',
                "description": 'Obsp key.',
                "default": None
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
            {
                "name": 'flavor',
                "type": 'str',
                "description": "Clustering flavor. Must be 'igraph' or 'leidenalg'. Do NOT use 'leiden'. **clustering_args Additional arguments.",
                "default": 'igraph'
            },
        ],
    },
    {
        "name": 'scRNA_tl_dendrogram',
        "description": 'Compute hierarchical clustering dendrogram.',
        "required_parameters": [
            {
                "name": 'groupby',
                "type": 'str',
                "description": 'Categorical obs column.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'n_pcs',
                "type": 'int or None',
                "description": 'Number of PCs.',
                "default": None
            },
            {
                "name": 'use_rep',
                "type": 'str or None',
                "description": 'Representation to use.',
                "default": None
            },
            {
                "name": 'var_names',
                "type": 'Collection[str] or None',
                "description": 'Variable names.',
                "default": None
            },
            {
                "name": 'use_raw',
                "type": 'bool or None',
                "description": 'Use raw.',
                "default": None
            },
            {
                "name": 'cor_method',
                "type": 'str',
                "description": 'Correlation method.',
                "default": 'pearson'
            },
            {
                "name": 'linkage_method',
                "type": 'str',
                "description": 'Linkage method.',
                "default": 'complete'
            },
            {
                "name": 'optimal_ordering',
                "type": 'bool',
                "description": 'Optimal ordering.',
                "default": False
            },
            {
                "name": 'key_added',
                "type": 'str or None',
                "description": 'Key to add.',
                "default": None
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_tl_dpt',
        "description": 'Diffusion Pseudotime analysis.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'n_dcs',
                "type": 'int',
                "description": 'Number of diffusion components.',
                "default": 10
            },
            {
                "name": 'n_branchings',
                "type": 'int',
                "description": 'Number of branchings.',
                "default": 0
            },
            {
                "name": 'min_group_size',
                "type": 'float',
                "description": 'Minimum group size.',
                "default": 0.01
            },
            {
                "name": 'allow_hierarchical_clustering',
                "type": 'bool',
                "description": 'Allow hierarchical clustering.',
                "default": False
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_tl_paga',
        "description": 'PAGA - Partition-based graph abstraction.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'groups',
                "type": 'str or None',
                "description": 'Cluster key.',
                "default": None
            },
            {
                "name": 'use_rna_velocity',
                "type": 'bool',
                "description": 'Use RNA velocity.',
                "default": False
            },
            {
                "name": 'model',
                "type": 'str',
                "description": 'PAGA model version.',
                "default": 'v1.2'
            },
            {
                "name": 'neighbors_key',
                "type": 'str or None',
                "description": 'Neighbors key.',
                "default": None
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_tl_ingest',
        "description": 'Ingest labels from reference data.',
        "required_parameters": [
            {
                "name": 'adata_ref',
                "type": 'AnnData',
                "description": 'Reference data.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'obs',
                "type": 'str or Collection[str] or None',
                "description": 'Obs keys to transfer.',
                "default": None
            },
            {
                "name": 'embedding_method',
                "type": 'tuple',
                "description": 'Embedding methods.',
                "default": ('umap', 'pca')
            },
            {
                "name": 'labeling_method',
                "type": 'str',
                "description": 'Labeling method.',
                "default": 'knn'
            },
            {
                "name": 'neighbors_key',
                "type": 'str or None',
                "description": 'Neighbors key.',
                "default": None
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_tl_rank_genes_groups',
        "description": 'Rank genes for characterizing groups.',
        "required_parameters": [
            {
                "name": 'groupby',
                "type": 'str',
                "description": 'Grouping key.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'groups',
                "type": 'str or Collection[str]',
                "description": 'Groups to compare.',
                "default": 'all'
            },
            {
                "name": 'reference',
                "type": 'str',
                "description": 'Reference group.',
                "default": 'rest'
            },
            {
                "name": 'n_genes',
                "type": 'int or None',
                "description": 'Number of genes.',
                "default": None
            },
            {
                "name": 'rankby_abs',
                "type": 'bool',
                "description": 'Rank by absolute value.',
                "default": False
            },
            {
                "name": 'pts',
                "type": 'bool',
                "description": 'Compute fraction of cells expressing.',
                "default": False
            },
            {
                "name": 'key_added',
                "type": 'str or None',
                "description": 'Key to add.',
                "default": None
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
            {
                "name": 'method',
                "type": 'str or None',
                "description": "Statistical method ('t-test', 'wilcoxon', 'logreg').",
                "default": None
            },
            {
                "name": 'corr_method',
                "type": 'str',
                "description": 'Correction method.',
                "default": 'benjamini-hochberg'
            },
            {
                "name": 'tie_correct',
                "type": 'bool',
                "description": 'Tie correction for Wilcoxon.',
                "default": False
            },
            {
                "name": 'layer',
                "type": 'str or None',
                "description": 'Layer to use. **kwds Additional arguments.',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_tl_filter_rank_genes_groups',
        "description": 'Filter ranked genes.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'key',
                "type": 'str or None',
                "description": 'Key in uns.',
                "default": None
            },
            {
                "name": 'groupby',
                "type": 'str or None',
                "description": 'Grouping key.',
                "default": None
            },
            {
                "name": 'use_raw',
                "type": 'bool or None',
                "description": 'Use raw.',
                "default": None
            },
            {
                "name": 'key_added',
                "type": 'str',
                "description": 'Key to add.',
                "default": 'rank_genes_groups_filtered'
            },
            {
                "name": 'min_in_group_fraction',
                "type": 'float',
                "description": 'Minimum in-group fraction.',
                "default": 0.25
            },
            {
                "name": 'min_fold_change',
                "type": 'float',
                "description": 'Minimum fold change.',
                "default": 1
            },
            {
                "name": 'max_out_group_fraction',
                "type": 'float',
                "description": 'Maximum out-group fraction.',
                "default": 0.5
            },
            {
                "name": 'compare_abs',
                "type": 'bool',
                "description": 'Compare absolute values.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_tl_marker_gene_overlap',
        "description": 'Calculate overlap between marker genes and reference.',
        "required_parameters": [
            {
                "name": 'reference_markers',
                "type": 'dict',
                "description": 'Reference marker genes.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'key',
                "type": 'str',
                "description": 'Key in uns.',
                "default": 'rank_genes_groups'
            },
            {
                "name": 'method',
                "type": 'str',
                "description": "Method ('overlap_count', 'overlap_coef', 'jaccard').",
                "default": 'overlap_count'
            },
            {
                "name": 'normalize',
                "type": 'str or None',
                "description": 'Normalization method.',
                "default": None
            },
            {
                "name": 'top_n_markers',
                "type": 'int or None',
                "description": 'Top N markers.',
                "default": None
            },
            {
                "name": 'adj_pval_threshold',
                "type": 'float or None',
                "description": 'Adjusted p-value threshold.',
                "default": None
            },
            {
                "name": 'key_added',
                "type": 'str',
                "description": 'Key to add.',
                "default": 'marker_gene_overlap'
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_tl_score_genes',
        "description": 'Score a set of genes.',
        "required_parameters": [
            {
                "name": 'gene_list',
                "type": 'Collection[str]',
                "description": 'List of genes.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'ctrl_size',
                "type": 'int',
                "description": 'Control gene set size.',
                "default": 50
            },
            {
                "name": 'gene_pool',
                "type": 'Collection[str] or None',
                "description": 'Pool of genes.',
                "default": None
            },
            {
                "name": 'n_bins',
                "type": 'int',
                "description": 'Number of bins.',
                "default": 25
            },
            {
                "name": 'score_name',
                "type": 'str',
                "description": 'Name for score.',
                "default": 'score'
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy.',
                "default": False
            },
            {
                "name": 'use_raw',
                "type": 'bool or None',
                "description": 'Use raw.',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_tl_score_genes_cell_cycle',
        "description": 'Score cell cycle phases.',
        "required_parameters": [
            {
                "name": 's_genes',
                "type": 'Collection[str]',
                "description": 'S-phase genes.',
                "default": None
            },
            {
                "name": 'g2m_genes',
                "type": 'Collection[str]',
                "description": 'G2M-phase genes.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'copy',
                "type": 'bool',
                "description": 'Return copy. **kwargs Additional arguments.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_tl_sim',
        "description": 'Simulate gene expression data.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'model',
                "type": 'str',
                "description": "Simulation model ('krumsiek11' or 'toggleswitch').",
                "default": 'krumsiek11'
            },
            {
                "name": 't_max',
                "type": 'int',
                "description": 'Maximum time.',
                "default": 50
            },
            {
                "name": 'branching',
                "type": 'bool',
                "description": 'Allow branching.',
                "default": True
            },
            {
                "name": 'dim',
                "type": 'int',
                "description": 'Dimensionality.',
                "default": 11
            },
            {
                "name": 'seed',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
