"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # OTHER
    # =============================================================================
    {
        "name": 'scRNA_experimental_pp_normalize_pearson_residuals',
        "description": 'Normalize counts using analytic Pearson residuals.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'theta',
                "type": 'float',
                "description": 'Negative binomial overdispersion parameter.',
                "default": 100
            },
            {
                "name": 'clip',
                "type": 'float or None',
                "description": 'Clip residuals to this value.',
                "default": None
            },
            {
                "name": 'check_values',
                "type": 'bool',
                "description": 'Check if values are counts.',
                "default": True
            },
            {
                "name": 'layer',
                "type": 'str or None',
                "description": 'Layer to normalize.',
                "default": None
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata inplace.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_experimental_pp_normalize_pearson_residuals_pca',
        "description": 'Normalize using Pearson residuals and compute PCA.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'theta',
                "type": 'float',
                "description": 'Negative binomial overdispersion parameter.',
                "default": 100
            },
            {
                "name": 'clip',
                "type": 'float or None',
                "description": 'Clip residuals to this value.',
                "default": None
            },
            {
                "name": 'n_comps',
                "type": 'int',
                "description": 'Number of principal components.',
                "default": 50
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'kwargs_pca',
                "type": 'dict or None',
                "description": 'Additional PCA arguments.',
                "default": None
            },
            {
                "name": 'check_values',
                "type": 'bool',
                "description": 'Check if values are counts.',
                "default": True
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata inplace.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_experimental_pp_highly_variable_genes',
        "description": 'Select highly variable genes using Pearson residuals.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'theta',
                "type": 'float',
                "description": 'Negative binomial overdispersion parameter.',
                "default": 100
            },
            {
                "name": 'clip',
                "type": 'float or None',
                "description": 'Clip residuals to this value.',
                "default": None
            },
            {
                "name": 'n_top_genes',
                "type": 'int or None',
                "description": 'Number of highly variable genes to keep.',
                "default": None
            },
            {
                "name": 'batch_key',
                "type": 'str or None',
                "description": 'Batch key for batch-aware selection.',
                "default": None
            },
            {
                "name": 'chunksize',
                "type": 'int',
                "description": 'Chunk size for processing.',
                "default": 1000
            },
            {
                "name": 'flavor',
                "type": 'str',
                "description": 'Method flavor.',
                "default": 'pearson_residuals'
            },
            {
                "name": 'check_values',
                "type": 'bool',
                "description": 'Check if values are counts.',
                "default": True
            },
            {
                "name": 'layer',
                "type": 'str or None',
                "description": 'Layer to use.',
                "default": None
            },
            {
                "name": 'subset',
                "type": 'bool',
                "description": 'Subset to highly variable genes.',
                "default": False
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata inplace.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_experimental_pp_recipe_pearson_residuals',
        "description": 'Full preprocessing recipe using Pearson residuals.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'theta',
                "type": 'float',
                "description": 'Negative binomial overdispersion parameter.',
                "default": 100
            },
            {
                "name": 'clip',
                "type": 'float or None',
                "description": 'Clip residuals to this value.',
                "default": None
            },
            {
                "name": 'n_top_genes',
                "type": 'int',
                "description": 'Number of highly variable genes to keep.',
                "default": 1000
            },
            {
                "name": 'batch_key',
                "type": 'str or None',
                "description": 'Batch key for batch-aware selection.',
                "default": None
            },
            {
                "name": 'chunksize',
                "type": 'int',
                "description": 'Chunk size for processing.',
                "default": 1000
            },
            {
                "name": 'n_comps',
                "type": 'int',
                "description": 'Number of principal components.',
                "default": 50
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
            {
                "name": 'kwargs_pca',
                "type": 'dict or None',
                "description": 'Additional PCA arguments.',
                "default": None
            },
            {
                "name": 'check_values',
                "type": 'bool',
                "description": 'Check if values are counts.',
                "default": True
            },
            {
                "name": 'inplace',
                "type": 'bool',
                "description": 'Update adata inplace.',
                "default": True
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
