"""
Tool definitions for scanpy single-cell analysis functions.
Format follows Biomni tool description convention.

AUTO-GENERATED by generate_tool_registry.py - DO NOT EDIT MANUALLY
"""

description = [
    # =============================================================================
    # GET FUNCTIONS (sc.get.*)
    # =============================================================================
    {
        "name": 'scRNA_get_obs_df',
        "description": 'Get DataFrame of observations.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'keys',
                "type": 'Collection[str] or None',
                "description": 'Keys for obs or var_names.',
                "default": None
            },
            {
                "name": 'obsm_keys',
                "type": 'Collection[tuple] or None',
                "description": 'Obsm keys.',
                "default": None
            },
            {
                "name": 'layer',
                "type": 'str or None',
                "description": 'Layer to use.',
                "default": None
            },
            {
                "name": 'gene_symbols',
                "type": 'str or None',
                "description": 'Gene symbols column.',
                "default": None
            },
            {
                "name": 'use_raw',
                "type": 'bool',
                "description": 'Use raw attribute.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_get_var_df',
        "description": 'Get DataFrame of variables.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'keys',
                "type": 'Collection[str] or None',
                "description": 'Keys for var or obs_names.',
                "default": None
            },
            {
                "name": 'varm_keys',
                "type": 'Collection[tuple] or None',
                "description": 'Varm keys.',
                "default": None
            },
            {
                "name": 'layer',
                "type": 'str or None',
                "description": 'Layer to use.',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_get_rank_genes_groups_df',
        "description": 'Get DataFrame of ranked genes.',
        "required_parameters": [
            {
                "name": 'group',
                "type": 'str or Collection[str]',
                "description": 'Group(s).',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'key',
                "type": 'str',
                "description": 'Key in uns.',
                "default": 'rank_genes_groups'
            },
            {
                "name": 'pval_cutoff',
                "type": 'float or None',
                "description": 'P-value cutoff.',
                "default": None
            },
            {
                "name": 'log2fc_min',
                "type": 'float or None',
                "description": 'Minimum log2 fold change.',
                "default": None
            },
            {
                "name": 'log2fc_max',
                "type": 'float or None',
                "description": 'Maximum log2 fold change.',
                "default": None
            },
            {
                "name": 'gene_symbols',
                "type": 'str or None',
                "description": 'Gene symbols column.',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_get_aggregate',
        "description": 'Aggregate data by groups.',
        "required_parameters": [
            {
                "name": 'by',
                "type": 'str or Collection[str]',
                "description": 'Keys to group by.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'func',
                "type": 'str or callable',
                "description": "Aggregation function ('mean', 'sum', 'var', etc.).",
                "default": 'mean'
            },
            {
                "name": 'layer',
                "type": 'str or None',
                "description": 'Layer to aggregate.',
                "default": None
            },
            {
                "name": 'obsm',
                "type": 'str or None',
                "description": 'Obsm key to aggregate.',
                "default": None
            },
            {
                "name": 'varm',
                "type": 'str or None',
                "description": 'Varm key to aggregate.',
                "default": None
            },
        ],
    },
    # =============================================================================
    # QUERIES FUNCTIONS (sc.queries.*)
    # =============================================================================
    {
        "name": 'scRNA_queries_biomart_annotations',
        "description": 'Get BioMart annotations.',
        "required_parameters": [
            {
                "name": 'org',
                "type": 'str',
                "description": "Organism ('hsapiens', 'mmusculus').",
                "default": None
            },
            {
                "name": 'attrs',
                "type": 'Collection[str]',
                "description": 'Attributes.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'host',
                "type": 'str',
                "description": 'Host.',
                "default": 'www.ensembl.org'
            },
            {
                "name": 'use_cache',
                "type": 'bool',
                "description": 'Use cache.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_queries_gene_coordinates',
        "description": 'Get gene coordinates.',
        "required_parameters": [
            {
                "name": 'org',
                "type": 'str',
                "description": 'Organism.',
                "default": None
            },
            {
                "name": 'gene_name',
                "type": 'str',
                "description": 'Gene name.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'host',
                "type": 'str',
                "description": 'Host.',
                "default": 'www.ensembl.org'
            },
            {
                "name": 'use_cache',
                "type": 'bool',
                "description": 'Use cache.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_queries_mitochondrial_genes',
        "description": 'Get mitochondrial genes from Ensembl BioMart.',
        "required_parameters": [
            {
                "name": 'org',
                "type": 'str',
                "description": "Organism name. Use 'hsapiens' for human, 'mmusculus' for mouse, 'rnorvegicus' for rat.",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'attrname',
                "type": 'str',
                "description": "BioMart attribute for gene names. Valid values: 'external_gene_name' (recommended), 'hgnc_symbol' (human only), 'ensembl_gene_id'. Do NOT use 'gene_name' or 'gene_symbol'.",
                "default": 'external_gene_name'
            },
            {
                "name": 'host',
                "type": 'str',
                "description": 'Ensembl host URL.',
                "default": 'www.ensembl.org'
            },
            {
                "name": 'use_cache',
                "type": 'bool',
                "description": 'Use cached results if available.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_queries_enrich',
        "description": 'Gene set enrichment analysis using g:Profiler.',
        "required_parameters": [
            {
                "name": 'group',
                "type": 'str',
                "description": 'Group from rank_genes_groups.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'key',
                "type": 'str',
                "description": 'Key in uns.',
                "default": 'rank_genes_groups'
            },
            {
                "name": 'pval_cutoff',
                "type": 'float',
                "description": 'P-value cutoff for selecting genes.',
                "default": 0.05
            },
            {
                "name": 'log2fc_min',
                "type": 'float or None',
                "description": 'Minimum log2 fold change.',
                "default": None
            },
            {
                "name": 'log2fc_max',
                "type": 'float or None',
                "description": 'Maximum log2 fold change.',
                "default": None
            },
            {
                "name": 'gene_symbols',
                "type": 'str or None',
                "description": 'Gene symbols column.',
                "default": None
            },
            {
                "name": 'org',
                "type": 'str',
                "description": "Organism ('hsapiens', 'mmusculus').",
                "default": 'hsapiens'
            },
            {
                "name": 'gprofiler_kwargs',
                "type": 'dict or None',
                "description": 'Additional arguments for g:Profiler.',
                "default": None
            },
        ],
    },
    # =============================================================================
    # METRICS FUNCTIONS (sc.metrics.*)
    # =============================================================================
    {
        "name": 'scRNA_metrics_confusion_matrix',
        "description": 'Compute confusion matrix.',
        "required_parameters": [
            {
                "name": 'original',
                "type": 'Series',
                "description": 'Original labels.',
                "default": None
            },
            {
                "name": 'new',
                "type": 'Series',
                "description": 'New labels.',
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'normalize',
                "type": 'bool',
                "description": 'Normalize.',
                "default": True
            },
        ],
    },
    {
        "name": 'scRNA_metrics_gearys_c',
        "description": "Compute Geary's C statistic.",
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'vals',
                "type": 'array-like or None',
                "description": 'Values.',
                "default": None
            },
            {
                "name": 'use_graph',
                "type": 'str or None',
                "description": 'Graph to use.',
                "default": None
            },
            {
                "name": 'layer',
                "type": 'str or None',
                "description": 'Layer.',
                "default": None
            },
            {
                "name": 'obsm',
                "type": 'str or None',
                "description": 'Obsm key.',
                "default": None
            },
            {
                "name": 'obsp',
                "type": 'str or None',
                "description": 'Obsp key.',
                "default": None
            },
            {
                "name": 'use_raw',
                "type": 'bool',
                "description": 'Use raw.',
                "default": False
            },
        ],
    },
    {
        "name": 'scRNA_metrics_morans_i',
        "description": "Compute Moran's I statistic.",
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'vals',
                "type": 'array-like or None',
                "description": 'Values.',
                "default": None
            },
            {
                "name": 'use_graph',
                "type": 'str or None',
                "description": 'Graph to use.',
                "default": None
            },
            {
                "name": 'layer',
                "type": 'str or None',
                "description": 'Layer.',
                "default": None
            },
            {
                "name": 'obsm',
                "type": 'str or None',
                "description": 'Obsm key.',
                "default": None
            },
            {
                "name": 'obsp',
                "type": 'str or None',
                "description": 'Obsp key.',
                "default": None
            },
            {
                "name": 'use_raw',
                "type": 'bool',
                "description": 'Use raw.',
                "default": False
            },
        ],
    },
    # =============================================================================
    # DATASETS FUNCTIONS (sc.datasets.*)
    # =============================================================================
    {
        "name": 'scRNA_datasets_pbmc3k',
        "description": 'Load PBMC 3k dataset. Returns ------- AnnData 3k PBMCs from 10x Genomics.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_datasets_pbmc3k_processed',
        "description": 'Load processed PBMC 3k dataset. Returns ------- AnnData Processed 3k PBMCs.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_datasets_pbmc68k_reduced',
        "description": 'Load reduced PBMC 68k dataset. Returns ------- AnnData Reduced 68k PBMCs.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_datasets_paul15',
        "description": 'Load Paul et al. 2015 dataset. Returns ------- AnnData Paul et al. 2015 hematopoiesis data.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_datasets_krumsiek11',
        "description": 'Load Krumsiek et al. 2011 dataset. Returns ------- AnnData Simulated myeloid progenitors.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_datasets_blobs',
        "description": 'Generate blob dataset.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'n_observations',
                "type": 'int',
                "description": 'Number of observations.',
                "default": 640
            },
            {
                "name": 'n_variables',
                "type": 'int',
                "description": 'Number of variables.',
                "default": 11
            },
            {
                "name": 'n_centers',
                "type": 'int',
                "description": 'Number of centers.',
                "default": 5
            },
            {
                "name": 'cluster_std',
                "type": 'float',
                "description": 'Cluster standard deviation.',
                "default": 1.0
            },
            {
                "name": 'random_state',
                "type": 'int',
                "description": 'Random seed.',
                "default": 0
            },
        ],
    },
    {
        "name": 'scRNA_datasets_ebi_expression_atlas',
        "description": 'Load dataset from EBI Expression Atlas.',
        "required_parameters": [
            {
                "name": 'accession',
                "type": 'str',
                "description": "EBI Expression Atlas accession (e.g., 'E-MTAB-5061').",
                "default": None
            },
        ],
        "optional_parameters": [
            {
                "name": 'filter_cell_type',
                "type": 'str or None',
                "description": 'Filter by cell type.',
                "default": None
            },
        ],
    },
    {
        "name": 'scRNA_datasets_moignard15',
        "description": 'Load Moignard et al. 2015 dataset. Returns ------- AnnData Hematopoiesis in mouse embryos.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_datasets_toggleswitch',
        "description": 'Load toggleswitch simulation dataset. Returns ------- AnnData Simulated toggle switch data.',
        "required_parameters": [
        ],
        "optional_parameters": [
        ],
    },
    {
        "name": 'scRNA_datasets_visium_sge',
        "description": 'Load 10x Visium spatial gene expression dataset.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'sample_id',
                "type": 'str',
                "description": 'Sample ID to download.',
                "default": 'V1_Breast_Cancer_Block_A_Section_1'
            },
            {
                "name": 'include_hires_tiff',
                "type": 'bool',
                "description": 'Include high-resolution TIFF image.',
                "default": False
            },
        ],
    },
    # =============================================================================
    # SETTINGS FUNCTIONS
    # =============================================================================
    {
        "name": 'scRNA_set_figure_params',
        "description": 'Set figure parameters.',
        "required_parameters": [
        ],
        "optional_parameters": [
            {
                "name": 'scanpy',
                "type": 'bool',
                "description": 'Use scanpy defaults.',
                "default": True
            },
            {
                "name": 'dpi',
                "type": 'int',
                "description": 'DPI.',
                "default": 80
            },
            {
                "name": 'dpi_save',
                "type": 'int',
                "description": 'DPI for saving.',
                "default": 150
            },
            {
                "name": 'frameon',
                "type": 'bool',
                "description": 'Frame on.',
                "default": True
            },
            {
                "name": 'vector_friendly',
                "type": 'bool',
                "description": 'Vector friendly.',
                "default": True
            },
            {
                "name": 'fontsize',
                "type": 'int',
                "description": 'Font size.',
                "default": 14
            },
            {
                "name": 'figsize',
                "type": 'tuple or None',
                "description": 'Figure size.',
                "default": None
            },
            {
                "name": 'color_map',
                "type": 'str or None',
                "description": 'Color map.',
                "default": None
            },
            {
                "name": 'format',
                "type": 'str',
                "description": 'File format.',
                "default": 'pdf'
            },
            {
                "name": 'facecolor',
                "type": 'str or None',
                "description": 'Face color.',
                "default": None
            },
            {
                "name": 'transparent',
                "type": 'bool',
                "description": 'Transparent background.',
                "default": False
            },
            {
                "name": 'ipython_format',
                "type": 'str',
                "description": 'IPython format.',
                "default": 'png2x'
            },
        ],
    },
]

# Create a lookup dictionary for quick access
TOOL_LOOKUP = {tool["name"]: tool for tool in description}


def get_tool_names():
    """Return list of all tool names."""
    return [tool["name"] for tool in description]


def get_tool_by_name(name):
    """Get tool definition by name."""
    return TOOL_LOOKUP.get(name)
