#!/usr/bin/env python3
"""
Auto-generate an MCP server that exposes all tools from the tool registry.

This script creates an MCP server that can be used with Claude subagents
and other MCP-compatible AI systems.

Usage:
    python scripts/generate_mcp_server.py [--categories CATEGORY1,CATEGORY2]
    
    # Generate server for all tools:
    python scripts/generate_mcp_server.py
    
    # Generate server for specific categories only:
    python scripts/generate_mcp_server.py --categories external,singlecell
    
    # Generate server for literature tools only:
    python scripts/generate_mcp_server.py --categories external_literature
    
    # Generate one server per category (for granular Claude agent configuration):
    python scripts/generate_mcp_server.py --all-categories

After generation, run a server:
    python src/mcp_servers/literature.py
"""

import argparse
import json
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

# Output directory for category-wise servers
MCP_SERVERS_DIR = project_root / "src" / "mcp_servers"


def generate_mcp_server(categories: list[str] | None = None, server_name: str = "biomni-tools", in_subdir: bool = False):
    """Generate the MCP server code.
    
    Parameters
    ----------
    categories : list[str] | None
        If provided, only include tools from these categories.
        E.g., ['external_literature', 'external_genomics']
    server_name : str
        Name for the MCP server instance.
    in_subdir : bool
        If True, server is in src/mcp_servers/ and needs to go up two levels.
    """
    
    # Adjust path based on where the server file will be located
    parent_path = "Path(__file__).parent.parent.parent" if in_subdir else "Path(__file__).parent"
    
    server_code = f'''#!/usr/bin/env python3
"""
MCP Server for Tool Registry.

AUTO-GENERATED by generate_mcp_server.py

This server exposes tools from src/tool_registry to MCP-compatible
AI agents like Claude subagents.

Run with:
    python src/mcp_servers/{server_name.replace("biomni-", "")}.py
"""

import asyncio
import json
import sys
from pathlib import Path
from typing import Any

# MCP SDK imports
try:
    from mcp.server import Server
    from mcp.server.stdio import stdio_server
    from mcp.types import Tool, TextContent
except ImportError:
    print("Error: MCP SDK not installed. Install with: pip install mcp", file=sys.stderr)
    print("See: https://github.com/modelcontextprotocol/python-sdk", file=sys.stderr)
    sys.exit(1)

# Add project root to path
project_root = {parent_path}
sys.path.insert(0, str(project_root))

from src.tool_registry import (
    get_tools,
    execute_tool,
)


# =============================================================================
# MCP Server Setup
# =============================================================================

# Create server instance
server = Server("{server_name}")


def _convert_openai_schema_to_mcp(openai_tool: dict) -> Tool:
    """Convert OpenAI function calling format to MCP Tool format."""
    # Support both flat format (get_tools) and nested format (legacy)
    func = openai_tool.get("function") or openai_tool
    return Tool(
        name=func["name"],
        description=func.get("description", ""),
        inputSchema=func.get("parameters", {{"type": "object", "properties": {{}}}})
    )


@server.list_tools()
async def list_tools() -> list[Tool]:
    """Return all available tools in MCP format."""
'''
    
    # Add category filtering logic
    if categories:
        categories_str = repr(categories)
        server_code += f'''
    # Filter to specific categories: {categories_str}
    categories = {categories_str}
    openai_tools = []
    for cat in categories:
        openai_tools.extend(get_tools(cat))
'''
    else:
        server_code += '''
    # Get all tools
    openai_tools = get_tools()
'''
    
    server_code += '''
    return [_convert_openai_schema_to_mcp(t) for t in openai_tools]


@server.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    """Execute a tool and return its result."""
    try:
        # Execute the tool
        result = execute_tool(name, **arguments)
        
        # Convert result to string representation
        if isinstance(result, (dict, list)):
            result_str = json.dumps(result, indent=2, default=str)
        else:
            result_str = str(result)
        
        return [TextContent(type="text", text=result_str)]
    
    except ValueError as e:
        return [TextContent(type="text", text=f"Error: Tool not found - {e}")]
    except Exception as e:
        return [TextContent(type="text", text=f"Error executing tool: {type(e).__name__}: {e}")]


# =============================================================================
# Server Entry Point
# =============================================================================

async def run_stdio():
    """Run server using stdio transport."""
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())


def main():
    asyncio.run(run_stdio())


if __name__ == "__main__":
    main()
'''
    
    return server_code


def generate_claude_config_single(server_name: str, server_path: str) -> dict:
    """Generate Claude MCP configuration snippet for a single server."""
    return {
        server_name: {
            "command": "python",
            "args": [server_path],
            "cwd": str(project_root)
        }
    }


def generate_claude_config_all(servers: dict[str, str]) -> dict:
    """Generate Claude MCP configuration for multiple servers.
    
    Parameters
    ----------
    servers : dict[str, str]
        Mapping of server_name -> server_path
    """
    mcp_servers = {}
    for server_name, server_path in servers.items():
        mcp_servers[server_name] = {
            "command": "python",
            "args": [server_path],
            "cwd": str(project_root)
        }
    return {"mcpServers": mcp_servers}


def _category_to_server_name(category: str) -> str:
    """Convert category name to a clean server name.
    
    Examples:
        external_literature -> literature
        singlecell_preprocessing -> singlecell-preprocessing
    """
    # Remove common prefixes
    name = category
    if name.startswith("external_"):
        name = name[len("external_"):]
    elif name.startswith("singlecell_"):
        name = "singlecell-" + name[len("singlecell_"):]
    
    # Replace underscores with hyphens for cleaner names
    return name.replace("_", "-")


def main():
    parser = argparse.ArgumentParser(
        description="Generate MCP server from tool registry",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Generate server for all tools:
    python scripts/generate_mcp_server.py
    
    # Generate server for specific categories:
    python scripts/generate_mcp_server.py --categories external_literature,external_genomics
    
    # Generate one server per category (recommended for Claude agents):
    python scripts/generate_mcp_server.py --all-categories
    
    # List available categories:
    python scripts/generate_mcp_server.py --list-categories
"""
    )
    parser.add_argument(
        "--categories",
        type=str,
        default=None,
        help="Comma-separated list of categories to include (e.g., 'external_literature,singlecell')"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="mcp_server.py",
        help="Output path for generated server (default: mcp_server.py)"
    )
    parser.add_argument(
        "--all-categories",
        action="store_true",
        help="Generate one MCP server per category in src/mcp_servers/"
    )
    parser.add_argument(
        "--list-categories",
        action="store_true",
        help="List all available tool categories and exit"
    )
    
    args = parser.parse_args()
    
    # Import here to avoid issues if tool_registry has import errors
    from src.tool_registry import list_categories, get_registry_stats
    
    if args.list_categories:
        print("Available tool categories:")
        stats = get_registry_stats()
        for module, count in sorted(stats["by_module"].items()):
            print(f"  {module}: {count} tools")
        print(f"\nTotal: {stats['total_tools']} tools across {stats['modules']} modules")
        return
    
    # Handle --all-categories: generate one server per category
    if args.all_categories:
        print("Generating category-wise MCP servers...")
        
        # Create output directory
        MCP_SERVERS_DIR.mkdir(parents=True, exist_ok=True)
        
        # Create __init__.py for the package
        init_file = MCP_SERVERS_DIR / "__init__.py"
        init_file.write_text('"""Auto-generated MCP servers for each tool category."""\n')
        
        stats = get_registry_stats()
        generated_servers = {}
        
        for category, tool_count in sorted(stats["by_module"].items()):
            server_name = f"biomni-{_category_to_server_name(category)}"
            filename = f"{_category_to_server_name(category)}.py"
            output_path = MCP_SERVERS_DIR / filename
            
            # Generate server code for this category
            server_code = generate_mcp_server(
                categories=[category],
                server_name=server_name,
                in_subdir=True
            )
            
            with open(output_path, "w") as f:
                f.write(server_code)
            
            relative_path = f"src/mcp_servers/{filename}"
            generated_servers[server_name] = relative_path
            print(f"  ✅ {category} ({tool_count} tools) -> {relative_path}")
        
        print(f"\n✅ Generated {len(generated_servers)} MCP servers in {MCP_SERVERS_DIR}")
        
        # Generate Claude config snippet for all servers
        config = generate_claude_config_all(generated_servers)
        print("\n📋 Add to your Claude settings (~/.claude/settings.json or .claude/settings.local.json):")
        print(json.dumps(config, indent=2))
        return
    
    # Standard single-server generation
    categories = None
    if args.categories:
        categories = [c.strip() for c in args.categories.split(",")]
        print(f"Generating MCP server for categories: {categories}")
    else:
        print("Generating MCP server for ALL tools")
    
    # Generate server code
    server_code = generate_mcp_server(categories)
    
    # Write to file
    output_path = project_root / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, "w") as f:
        f.write(server_code)
    
    print(f"✅ Generated MCP server: {output_path}")
    
    # Generate Claude config snippet
    config = generate_claude_config_single("biomni-tools", args.output)
    print("\n📋 Add this to your Claude settings (~/.claude/settings.json or .claude/settings.local.json):")
    print(json.dumps({"mcpServers": config}, indent=2))


if __name__ == "__main__":
    main()

